objects/Account.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>A short name for the client, to be used in communications.</description>
        <inlineHelpText>A short name for the client, to be used in communications.</inlineHelpText>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The client account that this employee (whether or not actually employed) belongs to.</description>
        <inlineHelpText>The client account that this employee (whether or not actually employed) belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>AccountEmployees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ClientEmployeeID__c</fullName>
        <description>The employee ID used by the client in their system.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee ID used by the client in their system.</inlineHelpText>
        <label>Client Employee ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaskedSSNFormula__c</fullName>
        <formula>&apos;***-**-&apos; &amp; right(SSN__c,4)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formatted SSN shows the last 4 digits of the Social Security Number.</inlineHelpText>
        <label>Masked SSN</label>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>EntityLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the survey was taken</description>
        <inlineHelpText>The location where the survey was taken</inlineHelpText>
        <label>Entity Location</label>
        <referenceTo>EntityLocation__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReportedHireDate__c</fullName>
        <description>The hire date reported by the employee</description>
        <inlineHelpText>The hire date reported by the employee</inlineHelpText>
        <label>Reported Hire Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SurveyResultGenerated__c</fullName>
        <defaultValue>&apos;Did Not Qualify&apos;</defaultValue>
        <description>A summary of the result of this survey: qualified, did not qualify, or declined.</description>
        <inlineHelpText>A summary of the result of this survey: qualified, did not qualify, or declined.</inlineHelpText>
        <label>Survey Result</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>If applicable, the date the Employee ceased working for the Entity</description>
        <inlineHelpText>If applicable, the date the Employee ceased working for the Entity</inlineHelpText>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JobTitleName__c</fullName>
        <description>The Job Title of the Employee associated with this Employment Period</description>
        <inlineHelpText>The Job Title of the Employee associated with this Employment Period</inlineHelpText>
        <label>Job Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</description>
        <inlineHelpText>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</inlineHelpText>
        <label>Location of Hire</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReferenceID__c</fullName>
        <description>The reference number used to connect survey respondents and their documents with this system&apos;s employment periods.</description>
        <displayFormat>{0}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>The reference number used to connect survey respondents and their documents with this system&apos;s employment periods.</inlineHelpText>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The official start date of the Employee associated with this Employment Period</description>
        <inlineHelpText>The official start date of the Employee associated with this Employment Period</inlineHelpText>
        <label>Hire Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EntityLocation__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location that hires under this entity.</description>
        <inlineHelpText>Location that hires under this entity.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity Location</label>
    <nameField>
        <label>Entity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date that this location shut its doors and went out of business.</description>
        <inlineHelpText>The date that this location shut its doors and went out of business.</inlineHelpText>
        <label>Location Closing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The opening date of this location, when it first started hiring employees.</description>
        <inlineHelpText>The opening date of this location, when it first started hiring employees.</inlineHelpText>
        <label>Location Opening Date</label>
        <type>Date</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The program short name</description>
        <inlineHelpText>The program short name</inlineHelpText>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period that this program qualification is under.</description>
        <inlineHelpText>The employment period that this program qualification is under.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/wktLocationEmployeeProgram__c.object
<CustomObject>
    <description>A generated list of locations with employees and programs.</description>
    <fields>
        <fullName>EmployeeName__c</fullName>
        <label>EmployeeName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployeeSurvey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey that this employee took.</description>
        <inlineHelpText>The survey that this employee took.</inlineHelpText>
        <label>Employee Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employee that all this information pertains to.</description>
        <inlineHelpText>The employee that all this information pertains to.</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period in question.</description>
        <inlineHelpText>The employment period in question.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalProcessStageName__c</fullName>
        <description>The client-friendly name for this process stage.</description>
        <formula>QualificationProcessStage__r.ExternalName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The client-friendly name for this process stage.</inlineHelpText>
        <label>External Process Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program begin screened for at this location.</description>
        <inlineHelpText>The program begin screened for at this location.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>wkt Location Employee Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Location Employee Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>wkt Location Employee Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalEmployeeInfoController.cls
public with sharing class PortalEmployeeInfoController {
	private string empId;
	
	list<wktLocationEmployeeProgram__c> wktL	{get; set;}
	public string employeeLocationID 		{get; set;}
	public string employeeLocationName	{get; set;}
	public string employeeLastName			{get; set;}
	public string employeeFirstName			{get; set;}
	public string employeeFullName			{get; set;}
	//EMPLOYEE TABLE INFO
	public string EMP_name				{get; set;}
	public string EMP_accountName	{get; set;}
	public string EMP_id					{get; set;}
	public string EMP_ssn					{get; set;}
	public string EMP_refId				{get; set;}
	//EMPLOYMENT INFO
	public list<EMPLOYMENT_INFO> employmentList	{get; set;}
	//SURVEY INFO
	public list<SURVEY_INFO> surveyList	{get; set;}
	//QUALIFICATIONS
	public list<QUALIFICATIONS> qualificationList	{get; set;}
	
	/************************************/
	public PortalEmployeeInfoController(){
		empId = ApexPages.currentPage().getParameters().get('empId');
		employeeLocationID =ApexPages.currentPage().getParameters().get('locId');
		if(empId!=null) makeWktList();
		if(wktL!=null && wktL.size()>0){
			setupCrumbs();
			fillOutEMPLOYEEtableInfo();
			fillOutEMPLOYMENTholders();
			fillOutSURVEYStaken();
			fillOutQualifications();
		}	
	}
	/************************************/
	private void makeWktList(){
		wktL = [Select w.Program__r.ShortName__c, w.Program__r.Name, w.Program__c,
						w.Employee__r.LastName__c, w.Employee__r.FirstName__c,
						w.ExternalProcessStageName__c, w.Employment__r.ReferenceID__c, 
						w.Employment__r.Location__c, w.Employment__r.StartDate__c, 
						w.Employment__r.Id, w.Employment__c, w.Employment__r.Location__r.Name, 
						w.Employment__r.JobTitleName__c, w.Employment__r.EndDate__c, 
						w.Employee__r.MaskedSSNFormula__c, 
						w.Employee__r.Account__c, w.Employee__r.Id, w.Employee__c, w.Employee__r.Name,
						w.Employee__r.Account__r.ShortName__c, w.Employee__r.Account__r.Name, 
						w.Employee__r.ClientEmployeeID__c,
						w.EmployeeSurvey__r.EntityLocation__c, w.EmployeeSurvey__r.SurveyResultGenerated__c, 
						w.EmployeeSurvey__r.ReportedHireDate__c, w.EmployeeSurvey__r.CreatedDate, 
						w.EmployeeSurvey__c, w.EmployeeName__c, w.EmployeeSurvey__r.EntityLocation__r.Location__r.Name,
						w.EmployeeSurvey__r.SurveyDate__c,
						w.DocumentReplacementNeededText__c, w.DocumentReceivedText__c, w.DocumentNeededText__c,
						w.QualifiedCategoryText__c, w.Employee__r.FirstLastNameFormula__c, w.Employment__r.Status__c,
						w.ActionItemFormula__c, w.ProgramQualification__r.ProcessStage__r.ExternalName__c
						From wktLocationEmployeeProgram__c w
						where Employee__r.Id = :empId
						order by Employment__r.StartDate__c];
	}
	/************************************/
	private void setupCrumbs(){
		wktLocationEmployeeProgram__c wkt = wktL[0];
		employeeLastName = wkt.Employee__r.LastName__c;
		employeeFirstName = wkt.Employee__r.FirstName__c;
		employeeFullName = wkt.Employee__r.FirstLastNameFormula__c;
		if(employeeLocationID!=null){
			try{
				Location__c l = [select Name from Location__c where id =:employeeLocationID];
				employeeLocationName = l.Name;
			}
			catch(Exception e){}
		}
	}
	/************************************/
	private void fillOutEMPLOYEEtableInfo(){
		wktLocationEmployeeProgram__c wkt = wktL[0];
		EMP_name = wkt.Employee__r.Name;
		if(wkt.Employee__r.Account__r.ShortName__c!=null) EMP_accountName = wkt.Employee__r.Account__r.ShortName__c;
		else EMP_accountName = wkt.Employee__r.Account__r.Name;
		EMP_id = wkt.Employee__r.ClientEmployeeID__c;
		EMP_ssn = wkt.Employee__r.MaskedSSNFormula__c;
		EMP_refId = wkt.Employment__r.ReferenceID__c;
	}
	/************************************/
	private void fillOutEMPLOYMENTholders(){
		employmentList = new list<EMPLOYMENT_INFO>();
		for(wktLocationEmployeeProgram__c wkt : wktL){
			if(wkt.Employment__c != null) employmentList.add(new EMPLOYMENT_INFO(wkt));
		}
	}
	/************************************/
	private void fillOutSURVEYStaken(){
		surveyList = new list<SURVEY_INFO>();
		for(wktLocationEmployeeProgram__c wkt: wktL){
			if(wkt.EmployeeSurvey__c !=null) surveyList.add(new SURVEY_INFO(wkt));
		}
	}
	/************************************/
	private void fillOutQualifications(){
		qualificationList = new list<QUALIFICATIONS>();
		for(wktLocationEmployeeProgram__c wkt: wktL){
			if(wkt.Program__c !=null) qualificationList.add(new QUALIFICATIONS(wkt));
		}
	}
	/************************************/
	/***/
	public class EMPLOYMENT_INFO{
		public string startDate			{get; set;}
		public string location			{get; set;}
		public string jobTitle			{get; set;}
		public string endDate				{get; set;}
		
		public EMPLOYMENT_INFO(wktLocationEmployeeProgram__c wkt){
			//startDate = String.valueOf(wkt.Employment__r.StartDate__c.month())+'/'+String.valueOf(wkt.Employment__r.StartDate__c.day())+'/'+String.valueOf(wkt.Employment__r.StartDate__c.year());
			//location = wkt.Employment__r.Location__r.Name;
			//jobTitle = wkt.Employment__r.JobTitleName__c;
			//endDate = string.valueOf(wkt.Employment__r.EndDate__c);
			
			//ADDED BY BOB 4/25/12
            if(String.valueOf(wkt.Employment__r.StartDate__c.month())+'/'+String.valueOf(wkt.Employment__r.StartDate__c.day())+'/'+String.valueOf(wkt.Employment__r.StartDate__c.year()) == null || String.valueOf(wkt.Employment__r.StartDate__c.month())+'/'+String.valueOf(wkt.Employment__r.StartDate__c.day())+'/'+String.valueOf(wkt.Employment__r.StartDate__c.year()) == '') startDate = '—';
            else startDate = String.valueOf(wkt.Employment__r.StartDate__c.month())+'/'+String.valueOf(wkt.Employment__r.StartDate__c.day())+'/'+String.valueOf(wkt.Employment__r.StartDate__c.year());
            if(string.valueOf(wkt.Employment__r.EndDate__c) == null || string.valueOf(wkt.Employment__r.EndDate__c) == '') endDate = '—';
            else endDate = string.valueOf(wkt.Employment__r.EndDate__c.month())+'/'+string.valueOf(wkt.Employment__r.EndDate__c.day())+'/'+string.valueOf(wkt.Employment__r.EndDate__c.year());
            if(wkt.Employment__r.Location__r.Name == null || wkt.Employment__r.Location__r.Name == '') location = '—';
            else location = wkt.Employment__r.Location__r.Name;
            if(wkt.Employment__r.JobTitleName__c == null || wkt.Employment__r.JobTitleName__c == '') jobTitle = '—';
            else jobTitle = wkt.Employment__r.JobTitleName__c;
            if(string.valueOf(wkt.Employment__r.EndDate__c) == null || string.valueOf(wkt.Employment__r.EndDate__c) == '') endDate = '—';
            else endDate = string.valueOf(wkt.Employment__r.EndDate__c);
            
		}
	}
	/***/
	public class SURVEY_INFO{
		public string createdDate		{get; set;}
		public string location			{get; set;}
		public string results				{get; set;}
		public string hireDate			{get; set;}		
		
		public SURVEY_INFO(wktLocationEmployeeProgram__c wkt){
			//createdDate = String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.month())+'/'+String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.day())+'/'+String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.year());
			//location = wkt.EmployeeSurvey__r.EntityLocation__r.Location__r.Name;
			//results = wkt.EmployeeSurvey__r.SurveyResultGenerated__c;
			//hireDate = string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.month())+'/'+string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.day())+'/'+string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.year());
			
			
			if(String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.month())+'/'+String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.day())+'/'+String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.year()) == null || String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.month())+'/'+String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.day())+'/'+String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.year()) == '') createdDate = '—';
            else createdDate = String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.month())+'/'+String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.day())+'/'+String.valueOf(wkt.EmployeeSurvey__r.SurveyDate__c.year());
            if(wkt.EmployeeSurvey__r.EntityLocation__r.Location__r.Name == null || wkt.EmployeeSurvey__r.EntityLocation__r.Location__r.Name == '') location = '—';
            else location = wkt.EmployeeSurvey__r.EntityLocation__r.Location__r.Name;
            if(wkt.EmployeeSurvey__r.SurveyResultGenerated__c == null || wkt.EmployeeSurvey__r.SurveyResultGenerated__c == '') results = '—';
            else results = wkt.EmployeeSurvey__r.SurveyResultGenerated__c;
            if(string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.month())+'/'+string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.day())+'/'+string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.year()) == null || string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.month())+'/'+string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.day())+'/'+string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.year()) == '') hireDate = '—';
            else hireDate = string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.month())+'/'+string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.day())+'/'+string.valueOf(wkt.EmployeeSurvey__r.ReportedHireDate__c.year());
		}
	}
	/***/
	public class QUALIFICATIONS{
		public string programName		{get; set;}
		public string stageName			{get; set;}
		public string categoryText	{get; set;}
		public string docNeeded			{get; set;}
		public string docRec				{get; set;}
		public string empStatus		{get; set;}
		public string certStatus		{get; set;}
		public string qualTasks		{get; set;}
		
		public QUALIFICATIONS(wktLocationEmployeeProgram__c wkt){
			programName = wkt.Program__r.Name;
			//stageName = wkt.ExternalProcessStageName__c;
			//categoryText = 
			//docNeeded = makeDocNeeded(wkt);
			//docRec = makeDocRec(wkt);
			//if(wkt.QualifiedCategoryText__c==null) categoryText = '—';
			//else categoryText=wkt.QualifiedCategoryText__c;
			//if(wkt.ExternalProcessStageName__c == null || wkt.ExternalProcessStageName__c == '') stageName = '—';
            //else stageName = wkt.ExternalProcessStageName__c;
			//if(makeDocNeeded(wkt) == null || makeDocNeeded(wkt) == '') docNeeded = '—';
            //else docNeeded = makeDocNeeded(wkt);
            //if(makeDocNeeded(wkt) == null || makeDocNeeded(wkt) == '') docNeeded = '—';
            //else docNeeded = makeDocNeeded(wkt);
            //if(makeDocRec(wkt) == null || makeDocRec(wkt) == '') docRec = '—';
            //else docRec = makeDocRec(wkt);
            if(wkt.Employment__r.Status__c == null || wkt.Employment__r.Status__c == '') empStatus = '—';
            else empStatus = wkt.Employment__r.Status__c;
            if(wkt.ProgramQualification__r.ProcessStage__r.ExternalName__c == null || wkt.ProgramQualification__r.ProcessStage__r.ExternalName__c == '') certStatus = '—';
            else certStatus = wkt.ProgramQualification__r.ProcessStage__r.ExternalName__c;
            if(wkt.ActionItemFormula__c == null || wkt.ActionItemFormula__c == '') qualTasks = '—';
            else qualTasks = wkt.ActionItemFormula__c;
			
		}
		/************************/
		public string makeDocNeeded(wktLocationEmployeeProgram__c wkt){
			string rVal = '';
			string rep = '';
			if(wkt.DocumentNeededText__c !=null){
				rVal =  wkt.DocumentNeededText__c.replaceAll(';', ',');
				if(rVal.endsWith(',')) rVal = rVal.substring(0, rVal.length()-1);
				rVal = rVal+' ';
			}
			if(wkt.DocumentReplacementNeededText__c != null){
				rep = wkt.DocumentReplacementNeededText__c.replaceAll(';', ',');
				if(rep.endsWith(',')) rep = rep.substring(0, rep.length()-1);
				rep = 'Please replace: '+rep;
			} 
			return rVal+rep;
		}
		/************************/
		public string makeDocRec(wktLocationEmployeeProgram__c wkt){
			string rVal ='';
			if(wkt.DocumentReceivedText__c !=null){
					rVal =  wkt.DocumentReceivedText__c.replaceAll(';', ',');
					if(rVal.endsWith(',')) rVal = rVal.substring(0, rVal.length()-1);
			}
			return rVal;
		}
	}	
	/***/
}