objects/Account.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>A short name for the client, to be used in communications.</description>
        <inlineHelpText>A short name for the client, to be used in communications.</inlineHelpText>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The client account that this employee (whether or not actually employed) belongs to.</description>
        <inlineHelpText>The client account that this employee (whether or not actually employed) belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>AccountEmployees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>The employee&apos;s federal social security number.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee&apos;s federal social security number.</inlineHelpText>
        <label>SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>EntityLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the survey was taken</description>
        <inlineHelpText>The location where the survey was taken</inlineHelpText>
        <label>Entity Location</label>
        <referenceTo>EntityLocation__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <description>The Entity associated with this Employment Period</description>
        <inlineHelpText>The Entity associated with this Employment Period</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</description>
        <inlineHelpText>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</inlineHelpText>
        <label>Location of Hire</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The official start date of the Employee associated with this Employment Period</description>
        <inlineHelpText>The official start date of the Employee associated with this Employment Period</inlineHelpText>
        <label>Hire Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account, or client, that this entity belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>AccountEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EntityLocation__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <description>Entity that has this location.</description>
        <inlineHelpText>Entity that has this location.</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location that hires under this entity.</description>
        <inlineHelpText>Location that hires under this entity.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity Location</label>
    <nameField>
        <label>Entity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The opening date of this location, when it first started hiring employees.</description>
        <inlineHelpText>The opening date of this location, when it first started hiring employees.</inlineHelpText>
        <label>Location Opening Date</label>
        <type>Date</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>ProgramEndSummary__c</fullName>
        <description>The overall end date of the program, calculated as the latest end date of the program&apos;s periods.</description>
        <inlineHelpText>The overall end date of the program, calculated as the latest end date of the program&apos;s periods.</inlineHelpText>
        <label>Program Expiration</label>
        <summarizedField>ProgramPeriod__c.EndDate__c</summarizedField>
        <summaryForeignKey>ProgramPeriod__c.Program__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProgramStartSummary__c</fullName>
        <description>The overall start date of the program, calculated as the earliest start date of the program&apos;s periods.</description>
        <inlineHelpText>The overall start date of the program, calculated as the earliest start date of the program&apos;s periods.</inlineHelpText>
        <label>Program Inception</label>
        <summarizedField>ProgramPeriod__c.StartDate__c</summarizedField>
        <summaryForeignKey>ProgramPeriod__c.Program__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The program short name</description>
        <inlineHelpText>The program short name</inlineHelpText>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Periods</relationshipLabel>
        <relationshipName>ProgramPeriods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <label>Program Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period that this program qualification is under.</description>
        <inlineHelpText>The employment period that this program qualification is under.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramPeriod__c</fullName>
        <description>The program period that the employee qualifies under</description>
        <inlineHelpText>The program period that the employee qualifies under</inlineHelpText>
        <label>Program Period</label>
        <referenceTo>ProgramPeriod__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey qualified for this program</description>
        <inlineHelpText>The survey qualified for this program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SurveyProgramScreened__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program screened by the survey</description>
        <inlineHelpText>The program screened by the survey</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The survey that screened for the program</description>
        <inlineHelpText>The survey that screened for the program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Programs Screened</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Program Screened</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Programs Screened Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Programs Screened</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TEST_PQUpdateWKTLocationEmployeeProgram.cls
@isTest
private class TEST_PQUpdateWKTLocationEmployeeProgram {
		public SurveyProgramScreened__c sps;
		public Entity__c ent;
		public EntityLocation__c el;
		public Program__c p;
		public ProgramPeriod__c pp;
		public Program__c p2;
		public ProgramPeriod__c pp2;
		public Program__c p3;
		public ProgramPeriod__c pp3;
		public EmployeeSurvey__c es;
		public EmployeeSurvey__c es2;
		public EmployeeSurvey__c es3;
		public Account a;
		public Employee__c emp;
		public Location__c l;
		public Employment__c em;
		
		public TEST_PQUpdateWKTLocationEmployeeProgram(){
			a = new Account();
    	a.Name = 'testa';
    	insert a;
    	
    	emp = new Employee__c();
    	emp.Account__c = a.id;
    	emp.FirstName__c = 'test';
    	emp.LastName__c = 'testington';
    	emp.SSN__c = '000-00-1234';
    	insert emp;
    	
      l = new Location__c();
    	l.Account__c = a.id;
    	l.Name = 'test';
    	
    	ent = new Entity__c();
    	ent.Account__c = a.id;
    	ent.Name = 'test';
    	insert ent;
    	
    	el = new EntityLocation__c();
    	el.Entity__c = ent.id;
    	el.Location__c = l.id;
    	
    	p = new Program__c();
    	p.ShortName__c='t';
    	p.Name = 'test';
    	//p.ProgramStartSummary__c = Date.today();
    	//p.ProgramEndSummary__c = Date.today();
    	insert p;
    	
    	pp = new ProgramPeriod__c();
    	pp.Program__c = p.id;
    	pp.StartDate__c = Date.today().addDays(-1000);
    	pp.EndDate__c = Date.today().addDays(1000);
    	insert pp;
    	
    	p2 = new Program__c();
    	p2.ShortName__c='t2';
    	p2.Name = 'test2';
    	//p.ProgramStartSummary__c = Date.today();
    	//p.ProgramEndSummary__c = Date.today();
    	insert p2;
    	
    	pp2 = new ProgramPeriod__c();
    	pp2.Program__c = p2.id;
    	pp2.StartDate__c = Date.today().addDays(-1000);
    	pp2.EndDate__c = Date.today().addDays(1000);
    	insert pp2;
    	
    	p3 = new Program__c();
    	p3.ShortName__c='t3';
    	p3.Name = 'test3';
    	//p.ProgramStartSummary__c = Date.today();
    	//p.ProgramEndSummary__c = Date.today();
    	insert p3;
    	
    	pp3 = new ProgramPeriod__c();
    	pp3.Program__c = p3.id;
    	pp3.StartDate__c = Date.today().addDays(-1000);
    	pp3.EndDate__c = Date.today().addDays(1000);
    	insert pp3;
    	
    	em = new Employment__c();
    	em.Employee__c = emp.id;
    	em.Location__c = l.id;
    	em.StartDate__c = Date.today();
    	em.Entity__c = ent.id;
    	insert em;
    	
    	es = new EmployeeSurvey__c();
    	es.Name = 'test';
    	es.EmploymentPeriod__c = em.id;
    	es.EntityLocation__c = el.id;
    	insert es; 
    	
    	SurveyProgramScreened__c sps = new SurveyProgramScreened__c();
      sps.Survey__c = es.id;
      sps.Program__c = p.id;
      insert sps;
    	
    	es2 = new EmployeeSurvey__c();
    	es2.Name = 'test2';
    	es2.EmploymentPeriod__c = em.id;
    	es2.EntityLocation__c = el.id;
    	insert es2;
    	
    	es3 = new EmployeeSurvey__c();
    	es3.Name = 'test2';
    	es3.EmploymentPeriod__c = em.id;
    	es3.EntityLocation__c = el.id;
    	insert es3;
		}
		static testMethod void myUnitTest() {
			TEST_PQUpdateWKTLocationEmployeeProgram  t = new TEST_PQUpdateWKTLocationEmployeeProgram();
			test.startTest();
			list<ProgramQualification__c> pql = new list<ProgramQualification__c>();
			ProgramQualification__c pq = new ProgramQualification__c();
			pq.ProgramPeriod__c = t.pp.id;
			pq.Employment__c = t.em.id;
			pql.add(pq);
			//insert pq; 
			ProgramQualification__c pq2 = new ProgramQualification__c();
			pq2.ProgramPeriod__c = t.pp2.id;
			pq2.Employment__c = t.em.id;
			//insert pq;
			pql.add(pq2);
			ProgramQualification__c pq3 = new ProgramQualification__c();
			pq3.ProgramPeriod__c = t.pp3.id;
			pq3.Employment__c = t.em.id;
			//insert pq3;
			pql.add(pq3);
			insert pql;
			
			Employee__c emp = new Employee__c();
    	emp.Account__c = t.a.id;
    	emp.FirstName__c = 'test2';
    	emp.LastName__c = 'testington2';
    	emp.SSN__c = '000-00-3434';
    	insert emp;
    	Employment__c em = new Employment__c();
    	em.Employee__c = emp.id;
    	em.Location__c = t.l.id;
    	em.StartDate__c = Date.today().addDays(-400);
    	em.Entity__c = t.ent.id;
    	insert em;
    	
    	pql = new list<ProgramQualification__c>();
    	
    	ProgramQualification__c pqA = new ProgramQualification__c();
			pqA.ProgramPeriod__c = t.pp.id;
			pqA.Employment__c = em.id;
			//insert pqA;
			pql.add(pqA);
			ProgramQualification__c pqB = new ProgramQualification__c();
			pqB.ProgramPeriod__c = t.pp3.id;
			pqB.Employment__c = em.id;
			//insert pqA;
			pql.add(pqB);
 			
 			insert pql;
 			
			
			test.stopTest();
		}

}