objects/Account.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>A short name for the client, to be used in communications.</description>
        <inlineHelpText>A short name for the client, to be used in communications.</inlineHelpText>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/AccountHierarchyMember__c.object
<CustomObject>
    <label>Account Hierarchy Member</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Hierarchy Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The organizational level that this contact has access to, if the contact is a portal user.</description>
        <inlineHelpText>The organizational level that this contact has access to, if the contact is a portal user.</inlineHelpText>
        <label>Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExecutiveAccessBit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Contact can access all information related to his/her account in the portal.</description>
        <inlineHelpText>Contact can access all information related to his/her account in the portal.</inlineHelpText>
        <label>Executive Access</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/ContentModule__c.object
<CustomObject>
    <label>ContentModule</label>
    <nameField>
        <label>ContentModule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentModules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PortalNotificationContent__c.object
<CustomObject>
    <fields>
        <fullName>PortalNotificationModule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PortalNotificationModule</label>
        <referenceTo>PortalNotificationModule__c</referenceTo>
        <relationshipLabel>PortalNotificationContents</relationshipLabel>
        <relationshipName>PortalNotificationContents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PortalNotificationContent</label>
    <nameField>
        <label>PortalNotificationContent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PortalNotificationContents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PortalNotificationModule__c.object
<CustomObject>
    <fields>
        <fullName>ContentModule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ContentModule</label>
        <referenceTo>ContentModule__c</referenceTo>
        <relationshipLabel>PortalNotificationModules</relationshipLabel>
        <relationshipName>PortalNotificationModules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PortalNotificationSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PortalNotificationSchedule</label>
        <referenceTo>PortalNotificationSchedule__c</referenceTo>
        <relationshipLabel>PortalNotificationModules</relationshipLabel>
        <relationshipName>PortalNotificationModules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PortalNotificationModule</label>
    <nameField>
        <label>PortalNotificationModule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PortalNotificationModules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PortalNotificationSchedule__c.object
<CustomObject>
    <description>The schedule for each portal notification digest to be sent out to a contact.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact whose portal notification schedule this is.</description>
        <inlineHelpText>The contact whose portal notification schedule this is.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Notification Schedules</relationshipLabel>
        <relationshipName>PortalNotificationSchedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DigestType__c</fullName>
        <description>Specifies whether this is the next digest to be sent out is the first one, a continued one, the last one, or whether this digest frequency has ended for this contact. This informs the data period in the report.</description>
        <inlineHelpText>Specifies whether this is the next digest to be sent out is the first one, a continued one, the last one, or whether this digest frequency has ended for this contact. This informs the data period in the report.</inlineHelpText>
        <label>Digest Type</label>
        <picklist>
            <picklistValues>
                <fullName>First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NextDigestDate__c</fullName>
        <description>The next scheduled date that this digest will be sent out.</description>
        <inlineHelpText>The next scheduled date that this digest will be sent out.</inlineHelpText>
        <label>Next Digest Date</label>
        <type>Date</type>
    </fields>
    <label>Portal Notification Schedule</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Portal Notification Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Notification Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BATCH_ModuleEmailDigest.cls
global class BATCH_ModuleEmailDigest implements Database.Batchable<sObject>{
	/***********************************************/
  global database.querylocator start(Database.BatchableContext BC){
       return Database.getQueryLocator([Select p.ContentModule__c, 
       																	 p.ContentModule__r.Name,
       																	 p.PortalNotificationSchedule__c, 
       																	 p.PortalNotificationSchedule__r.DigestType__c, 
       																	 p.PortalNotificationSchedule__r.NextDigestDate__c,
       																	 p.Name,  
       																	 p.PortalNotificationSchedule__r.Contact__c,
																				 p.PortalNotificationSchedule__r.Contact__r.AccountHierarchyMember__c, 
																				 p.PortalNotificationSchedule__r.Contact__r.Id, 
																				 p.PortalNotificationSchedule__r.Contact__r.ExecutiveAccessBit__c, 
																				 p.PortalNotificationSchedule__r.Contact__r.AccountId, 
																				 p.PortalNotificationSchedule__r.Contact__r.Account.Name, 
																				 p.PortalNotificationSchedule__r.Contact__r.Name, 
																				 p.PortalNotificationSchedule__r.Contact__r.Email, 
																				 p.PortalNotificationSchedule__r.Contact__r.Account.ShortName__c
       																	 From PortalNotificationModule__c p
																				 where (PortalNotificationSchedule__r.NextDigestDate__c = :Date.today() or
																				(PortalNotificationSchedule__r.DigestType__c = 'First' 
																				and PortalNotificationSchedule__r.NextDigestDate__c = null))]);
  }
  /***********************************************/
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		
		list<String> pnsIds = new list<string>();
		for(PortalNotificationModule__c pnm : (list<PortalNotificationModule__c>)scope){
			pnsIds.add(pnm.PortalNotificationSchedule__c);
		}
		
		PortalModuleEmailHelper pme = new PortalModuleEmailHelper();
		map<string, list<PortalNotificationModule__c>> cToPnmMap = pme.makeContactToPNMMap((list<PortalNotificationModule__c>)scope);
		map<string, list<PortalNotificationContent__c>> cToPncMap = pme.makeContactToPNCMap(pnsIds);
		pme.generateAndSendEmailForEachContact(cToPncMap, cToPnmMap);
	}
	/***********************************************/
	global void finish(Database.BatchableContext BC){
		
	}
	/***********************************************/
	global static void runBatch(){
		BATCH_ModuleEmailDigest b = new BATCH_ModuleEmailDigest();
		Database.executeBatch(b);
	}

}