objects/Account.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>A short name for the client, to be used in communications.</description>
        <inlineHelpText>A short name for the client, to be used in communications.</inlineHelpText>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/AccountHierarchyMember__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentAccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy Member</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Hierarchy Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The organizational level that this contact has access to, if the contact is a portal user.</description>
        <inlineHelpText>The organizational level that this contact has access to, if the contact is a portal user.</inlineHelpText>
        <label>Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExecutiveAccessBit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Contact can access all information related to his/her account in the portal.</description>
        <inlineHelpText>Contact can access all information related to his/her account in the portal.</inlineHelpText>
        <label>Executive Access</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CityName__c</fullName>
        <description>The location&apos;s city.</description>
        <inlineHelpText>The location&apos;s city.</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LatitudeCode__c</fullName>
        <description>The latitude of a location&apos;s address.</description>
        <inlineHelpText>The latitude of a location&apos;s address.</inlineHelpText>
        <label>Latitude</label>
        <precision>15</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LocationEID__c</fullName>
        <description>The Enterprise ID for this Location.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this Location.</inlineHelpText>
        <label>Location EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LongitudeCode__c</fullName>
        <description>The longitude of a location&apos;s address.</description>
        <inlineHelpText>The longitude of a location&apos;s address.</inlineHelpText>
        <label>Longitude</label>
        <precision>15</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location state</description>
        <inlineHelpText>The location state</inlineHelpText>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <description>The location street address</description>
        <inlineHelpText>The location street address</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LocationProgram__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>The location associated with the program and launch date</description>
        <inlineHelpText>The location associated with the program and launch date</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>LocationProgramLaunches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program associated with the location and launch date</description>
        <inlineHelpText>The program associated with the location and launch date</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>LocationProgramLaunches</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location Program</label>
    <nameField>
        <label>Location Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PortalNotification__c.object
<CustomObject>
    <description>History of email notifications sent regularly from the portal to portal users.</description>
    <fields>
        <fullName>ContentBitGenerated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>States whether there is data in the report portion of the email notification.</description>
        <inlineHelpText>States whether there is data in the report portion of the email notification.</inlineHelpText>
        <label>Content Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DataEndDate__c</fullName>
        <description>The end date and time of the data in the report part of the email notification content.</description>
        <inlineHelpText>The starting date and time of the data in the report part of the email notification content.</inlineHelpText>
        <label>Data End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DataStartDate__c</fullName>
        <description>The starting date and time of the data in the report part of the email notification content.</description>
        <inlineHelpText>The starting date and time of the data in the report part of the email notification content.</inlineHelpText>
        <label>Data Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EmployeeCountGenerated__c</fullName>
        <description>The number of unique employees covered in this report across all programs and locations, not just the ones showing in the email notification content.</description>
        <inlineHelpText>The number of unique employees covered in this report across all programs and locations, not just the ones showing in the email notification content.</inlineHelpText>
        <label>Employee Count Generated</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LocationCountGenerated__c</fullName>
        <description>The number of locations covered in this report, not just the ones showing in the email notification content.</description>
        <inlineHelpText>The number of locations covered in this report, not just the ones showing in the email notification content.</inlineHelpText>
        <label>Location Count Generated</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PortalNotificationSchedule__c</fullName>
        <description>The schedule under which this portal notification email was sent.</description>
        <inlineHelpText>The schedule under which this portal notification email was sent.</inlineHelpText>
        <label>Portal Notification Schedule</label>
        <referenceTo>PortalNotificationSchedule__c</referenceTo>
        <relationshipLabel>Portal Notifications</relationshipLabel>
        <relationshipName>PortalNotifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Portal Notification</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Portal Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PortalNotificationSchedule__c.object
<CustomObject>
    <description>The schedule for each portal notification digest to be sent out to a contact.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact whose portal notification schedule this is.</description>
        <inlineHelpText>The contact whose portal notification schedule this is.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Notification Schedules</relationshipLabel>
        <relationshipName>PortalNotificationSchedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DigestType__c</fullName>
        <description>Specifies whether this is the next digest to be sent out is the first one, a continued one, the last one, or whether this digest frequency has ended for this contact. This informs the data period in the report.</description>
        <inlineHelpText>Specifies whether this is the next digest to be sent out is the first one, a continued one, the last one, or whether this digest frequency has ended for this contact. This informs the data period in the report.</inlineHelpText>
        <label>Digest Type</label>
        <picklist>
            <picklistValues>
                <fullName>First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>The frequency of this digest.</description>
        <inlineHelpText>The frequency of this digest.</inlineHelpText>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semiannually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NextDigestDate__c</fullName>
        <description>The next scheduled date that this digest will be sent out.</description>
        <inlineHelpText>The next scheduled date that this digest will be sent out.</inlineHelpText>
        <label>Next Digest Date</label>
        <type>Date</type>
    </fields>
    <label>Portal Notification Schedule</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Portal Notification Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Notification Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The program short name</description>
        <inlineHelpText>The program short name</inlineHelpText>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>StateAbbr__c</fullName>
        <label>State Abbreviation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalEmailDigestListCreate.cls
global class PortalEmailDigestListCreate {
	public Attachment a;
	public PortalNotification__c pn;
	public Datetime prevDate;
	public Messaging.SingleEmailMessage[] emailList;
	public list <PortalNotificationSchedule__c>pNotificationList;
	public list<PortalNotification__c> pnList;
	public list<Attachment> attachments;
	/***********************************************/
	public PortalEmailDigestListCreate(){
		emailList = new List<Messaging.SingleEmailMessage>();
		pNotificationList = new list<PortalNotificationSchedule__c>();
		pnList = new list<PortalNotification__c>();
		attachments = new list<Attachment>();
	}
	/***********************************************/
	public void sendUpdateAndInsertInfo(){
			Messaging.sendEmail(emailList);
			update pNotificationList;
			insert pnList;
			for(integer i=0; i<pnList.size(); i++){
				pn = pnList[i];
				a = attachments[i];
				a.ParentId = pn.id;
			}
			insert attachments;
		}
	/***********************************************/
	public void addToLists(PortalNotificationSchedule__c p){
		//setup Dates
		p.NextDigestDate__c = date.today();
		prevDate = setupSendingDates(p);
		//prevDate = prevDate.addYears(-91); //FOR TESTING!!!!!!!
		//map of program to location statistics
		map  <string, list<PortalExecutiveDashboardController.locationProgramWrapper>> locationStats = generateLocationMapStatistics(p, prevDate);//programList);
		//map of program to employees
		PortalEmailDigestHelper peh = new PortalEmailDigestHelper(locationStats);
		map<String, list<PortalEmailDigestHelper.employeeDigestSubClass>> employeeStatsMap = peh.generateEmployeeMap(prevDate.Date(), p.NextDigestDate__c);
		list<list<PortalEmailDigestHelper.employeeDigestSubClass>> eList = peh.generateSingleEmployeeLists(employeeStatsMap);
		//generateEmails
		portalEmailsCreator pec = new portalEmailsCreator(p, locationStats,eList);// employeeStatsMap);
		Messaging.SingleEmailMessage mail = pec.createEmail();
		emailList.add(mail);
		//update contact/employee send dates
		updatePortalNotificationInfo(p);
		pn = makePn(p, mail, prevDate, locationStats, employeeStatsMap);
		a = new Attachment();
		a.Body =  blob.valueOf(mail.getHtmlBody());
		a.ContentType = 'html';
		a.Name = string.valueOf(Date.today())+'_emaildigest';
		attachments.add(a);			
		pnList.add(pn);
		pNotificationList.add(p);
	}	
	/***********************************************/
	public PortalNotification__c makePn(PortalNotificationSchedule__c p, Messaging.SingleEmailMessage mail, Datetime prevDate,
		map <string, list<PortalExecutiveDashboardController.locationProgramWrapper>> locationStats, map<String, list<PortalEmailDigestHelper.employeeDigestSubClass>> employeeStatsMap ){
		PortalNotification__c pn = new PortalNotification__c();
		pn.PortalNotificationSchedule__c = p.id;
		pn.DataStartDate__c = prevDate;
		pn.DataEndDate__c = Datetime.now();
		if(mail.getHtmlBody().contains('There has been no tax incentive screening activity as of'))
			pn.ContentBitGenerated__c = false;
		else
			pn.ContentBitGenerated__c = true;
		pn.LocationCountGenerated__c = getLocCount(locationStats);
		pn.EmployeeCountGenerated__c = getEmployeeCount(employeeStatsMap);
		//pn.FrequencyTextGenerated__c = p.Frequency__c;
		return pn;
	}
	/***********************************************/
	public integer getEmployeeCount(map<String, list<PortalEmailDigestHelper.employeeDigestSubClass>> employeeStatsMap){
		if(employeeStatsMap == null) return 0;
		list<PortalEmailDigestHelper.employeeDigestSubClass> el;
		integer rVal = 0;
		Set<String> keys = employeeStatsMap.keySet();
		if(keys == null || keys.size()==0) return 0;
		for (string key:keys){
			el = employeeStatsMap.get(key);
			if(el!=null) rVal = rVal + el.size();
		}
		return rVal;
	}
	/***********************************************/
	public integer getLocCount(map <string, list<PortalExecutiveDashboardController.locationProgramWrapper>> locationStats){
		integer rVal =0;
		list<PortalExecutiveDashboardController.locationProgramWrapper> ll;
		Set<String> keys = locationStats.keySet();
		if (keys == null||keys.size()==0) return 0;
		for(String key: keys){
			ll=locationStats.get(key);
			if(ll!=null) rVal = rVal + ll.size();
		}
		return rVal;
	}
	/***********************************************/
	public void updatePortalNotificationInfo(PortalNotificationSchedule__c p){
		Date nextDate = Date.today();
			if(p.Frequency__c =='Daily') nextDate = nextDate.addDays(1);
			else if (p.Frequency__c=='Weekly')nextDate = nextDate.addDays(7);
			else if (p.Frequency__c =='Monthly')nextDate = nextDate.addMonths(1);
			else nextDate = nextDate.addMonths(3);
			p.NextDigestDate__c = nextDate;
			
			//check digest type
			if(p.DigestType__c == 'Last'){
				p.DigestType__c = 'Ended';
				p.NextDigestDate__c = null;
			}
			else
				p.DigestType__c = 'Continued';		
	}
	/***********************************************/
	public Datetime setupSendingDates(PortalNotificationSchedule__c p){
		//p.NextDigestDate__c = Date.today();
		Datetime prevDate = Datetime.now();
		return prevDate.addYears(-90);///CHANGE THIS FOR TESTING!!!!!!!
		if(p.Frequency__c =='Daily') return prevDate.addDays(-1);
		else if (p.Frequency__c=='Weekly')return prevDate.addDays(-7);
		else if (p.Frequency__c =='Monthly')return prevDate.addMonths(-1);
		else return prevDate.addMonths(-3);
	}
	/***********************************************/
	public set<String> setupAHMSet(PortalNotificationSchedule__c p){
		set<String> ahmSet = new Set<string>();
		list<String> childIdList;
		list <AccountHierarchyMember__c> childrenList;
		if(p.contact__r.AccountHierarchyMember__c == null &&(p.contact__r.ExecutiveAccessBit__c == null || p.contact__r.ExecutiveAccessBit__c == false)) return ahmSet; 
		
		childrenList = [select id, ParentAccountHierarchyMember__c, Account__c 
										from AccountHierarchyMember__c
										where ParentAccountHierarchyMember__c = :p.contact__r.AccountHierarchyMember__c
										and Account__c = :p.contact__r.Account.id];
    
    while(childrenList != null && childrenList.size()>0){
	    childIdList = new list<String>();										
			for(AccountHierarchyMember__c ahm : childrenList){
				childIdList.add(ahm.id);
				ahmSet.add(ahm.id);
			}
			childrenList = [select id, ParentAccountHierarchyMember__c 
											from AccountHierarchyMember__c
											where ParentAccountHierarchyMember__c in :childIdList
											and Account__c = :p.contact__r.Account.id];										
    }
		return ahmSet;
	}
	/***********************************************/
	public list<PortalExecutiveDashboardController.locationProgramWrapper> getLocationList(set<String>ahmSet, PortalNotificationSchedule__c p){
		list<PortalExecutiveDashboardController.locationProgramWrapper> rVal = new list<PortalExecutiveDashboardController.locationProgramWrapper>();
		     list<LocationProgram__c> ll = [Select Program__r.ShortName__c, Program__c, Location__c, Program__r.Name,
                                        Location__r.LongitudeCode__c,
                                        Location__r.LatitudeCode__c,
                                        Location__r.State__r.Name, Location__r.StreetAddressText__c, location__r.State__r.StateAbbr__c,
                                        Location__r.State__c, Location__r.Name, Location__r.LocationEID__c,
                                        Location__r.CityName__c, Location__r.AccountHierarchyMember__c
                                        From LocationProgram__c 
                                        where Location__r.AccountHierarchyMember__c in :ahmSet
                                        AND Location__r.Account__c = :p.contact__r.accountId
                                        order by Location__r.Name
                                        limit 1000//:max
                                        ]; 
		for(LocationProgram__c lp : ll){
			rVal.add(new PortalExecutiveDashboardController.locationProgramWrapper(lp,'white'));
		} 
		return rVal;
	}
	/***********************************************/
	public map <string, list<PortalExecutiveDashboardController.locationProgramWrapper>> generateLocationMapStatistics(PortalNotificationSchedule__c p, Datetime prevDate){//, list<String> programList){
		map <String, list<PortalExecutiveDashboardController.locationProgramWrapper>> rVal = new map <String, list<PortalExecutiveDashboardController.locationProgramWrapper>>();
		map <String, list<PortalExecutiveDashboardController.locationProgramWrapper>> rValFiltered = new map <String, list<PortalExecutiveDashboardController.locationProgramWrapper>>();
		list<PortalExecutiveDashboardController.locationProgramWrapper> locList;
		Date sd = prevDate.Date();
		Date ed =p.NextDigestDate__c;
		//setup AHMSet
		set<String> ahmSet = setupAHMSet(p);
		//get location list
		list<PortalExecutiveDashboardController.locationProgramWrapper> llList = getLocationList(ahmSet, p);
		//setup initial map
		for(PortalExecutiveDashboardController.locationProgramWrapper ll : llList){
			locList = rVal.get(ll.lp.Program__r.Name);//using program name rather than short_name
			if(locList == null)locList = new list<PortalExecutiveDashboardController.locationProgramWrapper>();
			locList.add(ll);
			rVal.put(ll.lp.Program__r.Name, locList);//using program name rather than short_name
		}
		//setupMap with stat values
		set<String> programList = rVal.keySet();
		for(String prog : programList){
			 locList = rVal.get(prog);
			 if(locList != null){
			 	PortalScreeningComplianceHelper.setupPSC(locList, sd, ed);
			 	locList = filterOutZeros(locList); //LINES TO COMMENT OUT FOR MARNELLO TESTING
			 	if(locList !=null && locList.size()>0) //THIS ONE TOO
			 	 rValFiltered.put(prog, locList);
			 }			 	
		}
	return rValFiltered;
	}
	/***********************************************/
	public list<PortalExecutiveDashboardController.locationProgramWrapper> filterOutZeros(list<PortalExecutiveDashboardController.locationProgramWrapper> locList){
		list<PortalExecutiveDashboardController.locationProgramWrapper> rVal = new list<PortalExecutiveDashboardController.locationProgramWrapper>();
		for(PortalExecutiveDashboardController.locationProgramWrapper lw : locList){
			if(lw.PortalScreeningComplianceDenom != null && lw.PortalScreeningComplianceDenom != 0) rVal.add(lw);
		}
		return rVal;
	}
	/***********************************************/
	public static testMethod void testLCreator() {
      BATCH_EmailDigest_TEST t = new BATCH_EmailDigest_TEST();
      t.insertInfo();
			list <PortalNotificationSchedule__c> pList = [ Select  p.NextDigestDate__c, p.Frequency__c, p.DigestType__c, p.Contact__c,
						p.Contact__r.AccountHierarchyMember__c,  p.Contact__r.Id, p.Contact__r.ExecutiveAccessBit__c, p.Contact__r.AccountId, 
						p.Contact__r.Account.Name, p.Contact__r.Name, p.Contact__r.Email, p.Contact__r.Account.ShortName__c
						From PortalNotificationSchedule__c p
						where id = :t.p.id];
      test.startTest();
     	PortalEmailDigestListCreate lc = new PortalEmailDigestListCreate();
      for(PortalNotificationSchedule__c port: pList){
      	lc.addToLists(port);
      }
      lc.sendUpdateAndInsertInfo();
      portalEmailsCreator pec = new portalEmailsCreator(pList[0], null, null);
      pec.emptyBodyTest();
      test.stopTest();
    }
}