objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountEID__c</fullName>
        <description>The Enterprise ID for this Account.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this Account.</inlineHelpText>
        <label>Account EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The client account that this employee (whether or not actually employed) belongs to.</description>
        <inlineHelpText>The client account that this employee (whether or not actually employed) belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>AccountEmployees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>The employee&apos;s federal social security number.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee&apos;s federal social security number.</inlineHelpText>
        <label>SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>If applicable, the date the Employee ceased working for the Entity</description>
        <inlineHelpText>If applicable, the date the Employee ceased working for the Entity</inlineHelpText>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <description>The Entity associated with this Employment Period</description>
        <inlineHelpText>The Entity associated with this Employment Period</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The official start date of the Employee associated with this Employment Period</description>
        <inlineHelpText>The official start date of the Employee associated with this Employment Period</inlineHelpText>
        <label>Hire Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account, or client, that this entity belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>AccountEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EntityEID__c</fullName>
        <description>The Enterprise ID of this Entity.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID of this Entity.</inlineHelpText>
        <label>Entity EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EntityLocation__c.object
<CustomObject>
    <fields>
        <fullName>AccountEID__c</fullName>
        <formula>Location__r.Account__r.AccountEID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EntityLocationEID__c</fullName>
        <description>The Enterprise ID for this Entity Location.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this Entity Location.</inlineHelpText>
        <label>Entity Location EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <description>Entity that has this location.</description>
        <inlineHelpText>Entity that has this location.</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity Location</label>
    <nameField>
        <label>Entity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wage__c.object
<CustomObject>
    <fields>
        <fullName>EmploymentPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period associated with this wage</description>
        <inlineHelpText>The employment period associated with this wage</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Wages</relationshipLabel>
        <relationshipName>Wages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Indicates when the wages for this employment period ended</description>
        <inlineHelpText>Indicates when the wages for this employment period ended</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Indicates when the wages for this employment period started</description>
        <inlineHelpText>Indicates when the wages for this employment period started</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WageAmount__c</fullName>
        <description>Indicates the wages earned between the start and end dates</description>
        <inlineHelpText>Indicates the wages earned between the start and end dates</inlineHelpText>
        <label>Wage Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Wage</label>
    <nameField>
        <label>Wage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PreventDuplicateWage_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
 
 @isTest
private class PreventDuplicateWage_TEST
{
 	private static Account account = [select id from Account where AccountEID__c = 227];
	private static Entity__c entity = [select Id from Entity__c where EntityEID__c = 681];
 	private static EntityLocation__c entityLoc = [select Id from EntityLocation__c where EntityLocationEID__c = 40086];
 	private static Employee__c employee;
 	private static Employment__c employment;
 	private static Wage__c wage;
 		
   	static
  	{	
  		employee = new Employee__c(FirstName__c = 'Test', LastName__c = 'Test', Account__c = account.Id, SSN__c = '111223333');
  		insert employee;
  		
  		employment = new Employment__c(Entity__c = entity.Id, Employee__c = employee.Id, StartDate__c = date.parse('06/01/2011') );
  		insert employment;
  		
  		wage = new Wage__c(StartDate__c = date.parse('06/01/2011'), EndDate__c = date.parse('12/01/2011'), WageAmount__c = 100, EmploymentPeriod__c = employment.Id);
  		insert wage;
  	}

	
	static testmethod void preventEntityDup()		
	{
		try
		{				
			Wage__c newWage = new Wage__c(StartDate__c = date.parse('06/01/2011'), EndDate__c = date.parse('12/01/2011'), WageAmount__c = 100, EmploymentPeriod__c = employment.Id);
			insert newWage;
		}
		catch(System.DMLException e)
        {
            System.assert(e.getMessage().contains('Duplicate wages found within same period'));
        }   
         
	}
	
}