objects/AccountHierarchyLevel__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Level</label>
        <referenceTo>AccountHierarchyLevel__c</referenceTo>
        <relationshipLabel>Account Hierarchy Levels</relationshipLabel>
        <relationshipName>AccountHierarchyLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy Levels</relationshipLabel>
        <relationshipName>AccountHierarchyLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LevelNumber__c</fullName>
        <label>Level Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Hierarchy Level</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Hierarchy Level ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AccountHierarchyMember__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Level</label>
        <referenceTo>AccountHierarchyLevel__c</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy Member</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Hierarchy Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The organizational level that this contact has access to, if the contact is a portal user.</description>
        <inlineHelpText>The organizational level that this contact has access to, if the contact is a portal user.</inlineHelpText>
        <label>Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExecutiveAccessBit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Contact can access all information related to his/her account in the portal.</description>
        <inlineHelpText>Contact can access all information related to his/her account in the portal.</inlineHelpText>
        <label>Executive Access</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The client account that this employee (whether or not actually employed) belongs to.</description>
        <inlineHelpText>The client account that this employee (whether or not actually employed) belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>AccountEmployees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ClientEmployeeID__c</fullName>
        <description>The employee ID used by the client in their system.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee ID used by the client in their system.</inlineHelpText>
        <label>Client Employee ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>The employee&apos;s federal social security number.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee&apos;s federal social security number.</inlineHelpText>
        <label>SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CityName__c</fullName>
        <description>The location&apos;s city.</description>
        <inlineHelpText>The location&apos;s city.</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location state</description>
        <inlineHelpText>The location state</inlineHelpText>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <description>The location street address</description>
        <inlineHelpText>The location street address</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalSearchPageController.cls
public with sharing class PortalSearchPageController {

	public boolean 		showError						{get; set;}
	public string 		searchVal						{get; set;}
	public string 		accountName					{get; set;}
	public string 		locId					{get; set;}
	public string 		empId					{get; set;}
	public list<EmployeeWrapper> ewList		{get; set;}
	public list<locationWrapper> lList		{get; set;}

	
	private double		levelNumber;
	private string 		contactId;
	private string 		accountId;
	private string 		userACM;
	
	public void setaccountId(String val){if(test.isRunningTest())accountId = val;}
	
/*****************************************************/
	public PortalSearchPageController(){
			searchVal = Apexpages.currentPage().getParameters().get('searchVal');
			try{
				string userId = Userinfo.getUserId();
				ContactId = [Select u.Contact.FirstName, u.Contact.LastName, u.ContactId From User u where id =:userId].contactId;
        Contact contact = [select AccountId, Account.Name,  AccountHierarchyMember__c, ExecutiveAccessBit__c from Contact where Id =:ContactId];            
        accountName=contact.Account.Name;
        accountId = contact.AccountId;
        if(contact.AccountHierarchyMember__c!=null){
					userACM = contact.AccountHierarchyMember__c;
					levelNumber = [Select AccountHierarchyLevel__r.LevelNumber__c, AccountHierarchyLevel__c From AccountHierarchyMember__c where Id = :userACM].AccountHierarchyLevel__r.LevelNumber__c;
        }
        boolean executiveAccessBit = contact.ExecutiveAccessBit__c;
        	
        if(contact != null && (userACM != null|| executiveAccessBit) && accountId != null)
					setupSearch();
				else 
					showError = true;
				}
      catch(exception e){  
      	//system.assert(false, e +'USER ID'+Userinfo.getUserId());   
      	//!!!!!!! FOR DEVELOPMENT                                               
        if(userinfo.getProfileId() == '00e30000001iwE7AAI'){
        	accountId ='0013000000qKxdW';
          userACM = 'a07S00000029ZNjIAM';//--California State
          Account accountObject = [SELECT Id, Name FROM Account WHERE Id =:accountId];
          accountName = accountObject.Name;
          if(!test.isRunningTest())
          	setupSearch();
         }
         else 
					showError = true;
				}
	}
/*****************************************************/
	public void setupSearch(){
		if(searchVal == null || searchVal.length()<=1)
			showError = true;
		else{
			showError = false;
			doSearch();
		}
	}
/*****************************************************/
	private void doSearch(){
		//double levelNumber = [Select AccountHierarchyLevel__r.LevelNumber__c, AccountHierarchyLevel__c From AccountHierarchyMember__c where Id = :userACM].AccountHierarchyLevel__r.LevelNumber__c;
		String searchQuery = '*'+searchVal+'*';
		List<List<SObject>> searchList = [FIND :searchQuery IN ALL FIELDS RETURNING 
																			Location__c(StreetAddressText__c, State__r.Name, State__c, Name, CityName__c, Account__c, Id
																									where Account__c = :accountId 
																									//and(AccountHierarchyMember__c = :userACM or AccountHierarchyMember__r.AccountHierarchyLevel__r.LevelNumber__c > :levelNumber)
																									order by Name limit 25), 
																			Employee__c(LastName__c, FirstName__c, ClientEmployeeID__c, SSN__c, Account__c
																									where Account__c = :accountId
																									order by LastName__c
																									limit 25)];
	list<Location__c>locationList = searchList[0];
	list<Employee__c>employeeList = searchList[1];																									
	makeWrappers(locationList, employeeList);
	}
/*****************************************************/
	public void makeWrappers(list<Location__c>locationList, list<Employee__c>employeeList){
		string color = 'white';
		if(locationList != null && locationList.size() > 0){
			lList = new list<locationWrapper>();
			for (Location__c l : locationList){
				lList.add(new locationWrapper(l, color));
				if(color =='white')
	      	color = 'lightgrey';
	      else
	      	color = 'white';
			}
		}
		if(employeeList != null && employeeList.size()>0){
			color = 'white';
			ewList = new list<EmployeeWrapper>();
			for(Employee__c e : employeeList){
	    	ewList.add(new EmployeeWrapper(e, color));
	      if(color =='white')
	      	color = 'lightgrey';
	      else
	       color = 'white';
	    }
		}   
	}
/*****************************************************/
public void previousLocations(){
	if(lList == null || lList.size()==0)
		return;
	String searchQuery = '*'+searchVal+'*';
	List<List<SObject>> searchList = [FIND :searchQuery IN ALL FIELDS RETURNING 
																		Location__c(StreetAddressText__c, State__r.Name, State__c, Name, CityName__c, Account__c 
																								where Account__c = :accountId 
																								and(AccountHierarchyMember__c = :userACM or AccountHierarchyMember__r.AccountHierarchyLevel__r.LevelNumber__c > :levelNumber)
																								and Name < :lList[0].loc.Name
																								order by Name limit 25)];
	list<Location__c>locationList = searchList[0];
	makeWrappers(locationList, null);																								
}
/*****************************************************/
public void nextLocations(){
	if(lList == null || lList.size()==0)
		return;
	String searchQuery = '*'+searchVal+'*';
	List<List<SObject>> searchList = [FIND :searchQuery IN ALL FIELDS RETURNING 
																		Location__c(StreetAddressText__c, State__r.Name, State__c, Name, CityName__c, Account__c 
																								where Account__c = :accountId 
																								and(AccountHierarchyMember__c = :userACM or AccountHierarchyMember__r.AccountHierarchyLevel__r.LevelNumber__c > :levelNumber)
																								and Name > :lList[lList.size()-1].loc.Name
																								order by Name limit 25)];
	list<Location__c>locationList = searchList[0];
	makeWrappers(locationList, null);
}
/*****************************************************/
public void previousEmployees(){
	if(ewList == null || ewList.size()==0)
		return;
	String searchQuery = '*'+searchVal+'*';
	List<List<SObject>> searchList = [FIND :searchQuery IN ALL FIELDS RETURNING 
																		Employee__c(LastName__c, FirstName__c, ClientEmployeeID__c, SSN__c, Account__c
																									where Account__c = :accountId
																									and LastName__c < :ewList[0].lastName
																									order by LastName__c
																									limit 25)];
	list<Employee__c>employeeList = searchList[0];																									

	makeWrappers(null, employeeList);

}
/*****************************************************/
public void nextEmployees(){
	if(ewList == null || ewList.size()==0)
		return;
	String searchQuery = '*'+searchVal+'*';
	List<List<SObject>> searchList = [FIND :searchQuery IN ALL FIELDS RETURNING 
																		Employee__c(LastName__c, FirstName__c, ClientEmployeeID__c, SSN__c, Account__c
																									where Account__c = :accountId
																									and LastName__c > :ewList[ewList.size()-1].lastName
																									order by LastName__c
																									limit 25)];
	list<Employee__c>employeeList = searchList[0];																									
	makeWrappers(null, employeeList);

}
/*****************************************************/
/*****************/
    public class locationWrapper{
        public Location__c loc{get; set;}
        public string background {get; set;}
        public String locId{get; set;}
        public locationWrapper(Location__c l, string bg){
            loc = l;
            background = bg;
            locId = loc.Id;
        }
    }
/*************/
    public class EmployeeWrapper{
        public String lastName{get; set;}
        public String firstName{get; set;}
        public String clientEmployeeId{get; set;}
        public String ssn {get; set;}
        public String id{get; set;}
        public string background{get; set;}
        
        public EmployeeWrapper(Employee__c e, string bg){
            if(e.SSN__c !=null && e.SSN__c.length()>=4)
                ssn = e.SSN__c.substring(e.SSN__c.length()-4, e.SSN__c.length());
            else
                ssn = 'none';
            lastName = e.LastName__c;
            firstName = e.FirstName__c;
            clientEmployeeId = e.clientEmployeeId__c;
            id = e.Id;
            background = bg;
        }
    }
/*************/
}