objects/AccountHierarchyLevel__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyLevelLabelName__c</fullName>
        <label>Level Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountHierarchyLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Level</label>
        <referenceTo>AccountHierarchyLevel__c</referenceTo>
        <relationshipLabel>Account Hierarchy Levels</relationshipLabel>
        <relationshipName>AccountHierarchyLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy Levels</relationshipLabel>
        <relationshipName>AccountHierarchyLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LevelNumber__c</fullName>
        <label>Level Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Hierarchy Level</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Hierarchy Level ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AccountHierarchyMember__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Level</label>
        <referenceTo>AccountHierarchyLevel__c</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountHierarchyMemberLabelName__c</fullName>
        <label>Member Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountHierarchyMemberName__c</fullName>
        <label>Member Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentAccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy Member</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Hierarchy Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account, or client, that this entity belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>AccountEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ClientEntityId__c</fullName>
        <description>The client provided id for the entity</description>
        <inlineHelpText>The client provided id for the entity</inlineHelpText>
        <label>Client Entity ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE2EntityId__c</fullName>
        <description>Stores the corp id from IE 2</description>
        <inlineHelpText>Stores the corp id from IE 2</inlineHelpText>
        <label>IE2EntityID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EntityLocation__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <description>Entity that has this location.</description>
        <inlineHelpText>Entity that has this location.</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location that hires under this entity.</description>
        <inlineHelpText>Location that hires under this entity.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity Location</label>
    <nameField>
        <label>Entity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CityName__c</fullName>
        <description>The location&apos;s city.</description>
        <inlineHelpText>The location&apos;s city.</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location state</description>
        <inlineHelpText>The location state</inlineHelpText>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <description>The location street address</description>
        <inlineHelpText>The location street address</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>StateAbbr__c</fullName>
        <label>State Abbreviation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountHierarchyController_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */

@isTest
private class AccountHierarchyController_TEST
{
   
      static testMethod void ControllerTest() 
    {
      
      Account a1 = new Account();
            a1.Name = 'TEST ACCOUNT';
            insert a1;
     AccountHierarchyLevel__c l1 = new AccountHierarchyLevel__c();
      l1.Account__c = a1.id;
      l1.AccountHierarchyLevelLabelName__c = 'test level 1';
      l1.LevelNumber__c = 1;
      insert l1;
      
      AccountHierarchyLevel__c l2 = new AccountHierarchyLevel__c();
      l2.Account__c = a1.id;
      l2.AccountHierarchyLevelLabelName__c = 'test level 2';
      l2.LevelNumber__c = 2;
      l2.AccountHierarchyLevel__c = l1.id;
      insert l2;
      
      AccountHierarchyMember__c ahm = new AccountHierarchyMember__c();
      ahm.AccountHierarchyMemberLabelName__c = 'State';
      //ahm.ParentAccountHierarchyMember__c='West';
      ahm.AccountHierarchyLevel__c=l1.Id;
      ahm.Account__c=a1.Id;
      ahm.AccountHierarchyMemberName__c='California';
      insert ahm;
      AccountHierarchyMember__c ahm2 = new AccountHierarchyMember__c();
      ahm2.AccountHierarchyMemberLabelName__c = 'State';
      //ahm.ParentAccountHierarchyMember__c='West';
      ahm2.AccountHierarchyLevel__c=l1.Id;
      ahm2.Account__c=a1.Id;
      ahm2.AccountHierarchyMemberName__c='California';
      insert ahm2;
      
      AccountHierarchyLevel__c l3 = new AccountHierarchyLevel__c();
            l3.Account__c = a1.id;
            l3.AccountHierarchyLevelLabelName__c = 'test level 2';
            l3.LevelNumber__c = 2;
            
            insert l3; 
            Entity__c Entity=new Entity__c(Account__c=a1.Id,ClientEntityId__c='test123',IE2EntityId__c=123);
            insert Entity;
              State__c state = new State__c();
      state.Name = 'test';
      state.StateAbbr__c = 'tst';
      insert state;
            Location__c loc1 = new Location__c();
      loc1.StreetAddressText__c = 'test';
      loc1.State__c = state.id;
      loc1.Name = 'test';
      loc1.CityName__c = 'test city';
      loc1.AccountHierarchyMember__c = ahm.id;
      loc1.Account__c = a1.id;
      insert loc1;
            EntityLocation__c EntityLocation=new EntityLocation__c(Entity__c=Entity.Id,Location__c=loc1.Id);
            insert EntityLocation;
            ApexPages.currentPage().getParameters().put('accountId',a1.Id);
            AccountHierarchyController acccon=new AccountHierarchyController();
      ApexPages.StandardController cont=new ApexPages.StandardController(ahm);
      AccountHierarchyController controller=new AccountHierarchyController(cont);
      controller.updateClientOrgId=ahm.id;
      controller.DeleteClientOrgId=l3.id;
    
    
    controller.accountHierarchyMemberFilter=ahm.Id;
    controller.EditClientOrg();
    controller.bindTreeView();
    controller.initializePage();
    controller.initControlList();
    controller.initLocationItems();
    controller.initSelectedItems();
    controller.initLevelName();
    controller.groupChange();
    controller.ParentOrgChange();
    controller.AddChildClientOrg();
    controller.AddLocation();
    controller.ResponseEditLevel();
    controller.ResponseNewLevel();
    controller.CloseModalWindow();
    controller.updateClientOrgId=ahm.Id;
    controller.updateClientOrg();
    controller.SaveClientOrg();
    controller.ClientOrgLevelNameRead ='';
    controller.SaveClientOrg();
    controller.deleteItem();
    controller.accountHierarchyLevelNewOrEdit='';
    String slst=ahm2.Id+';'+ahm.Id;
    
    controller.hdDeleteIDList=slst;
    controller.deleteItem();
    }
    
      
    }