objects/Account.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>A short name for the client, to be used in communications.</description>
        <inlineHelpText>A short name for the client, to be used in communications.</inlineHelpText>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/AccountHierarchyLevel__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyLevelLabelName__c</fullName>
        <label>Level Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountHierarchyLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Level</label>
        <referenceTo>AccountHierarchyLevel__c</referenceTo>
        <relationshipLabel>Account Hierarchy Levels</relationshipLabel>
        <relationshipName>AccountHierarchyLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy Levels</relationshipLabel>
        <relationshipName>AccountHierarchyLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LevelNumber__c</fullName>
        <label>Level Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Hierarchy Level</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Hierarchy Level ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AccountHierarchyMember__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Level</label>
        <referenceTo>AccountHierarchyLevel__c</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountHierarchyMemberLabelName__c</fullName>
        <label>Member Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountHierarchyMemberName__c</fullName>
        <label>Member Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentAccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Account Hierarchy Members</relationshipLabel>
        <relationshipName>AccountHierarchyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy Member</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Hierarchy Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The organizational level that this contact has access to, if the contact is a portal user.</description>
        <inlineHelpText>The organizational level that this contact has access to, if the contact is a portal user.</inlineHelpText>
        <label>Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CityName__c</fullName>
        <description>The location&apos;s city.</description>
        <inlineHelpText>The location&apos;s city.</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date that this location shut its doors and went out of business.</description>
        <inlineHelpText>The date that this location shut its doors and went out of business.</inlineHelpText>
        <label>Location Closing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The opening date of this location, when it first started hiring employees.</description>
        <inlineHelpText>The opening date of this location, when it first started hiring employees.</inlineHelpText>
        <label>Location Opening Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location state</description>
        <inlineHelpText>The location state</inlineHelpText>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <description>The location street address</description>
        <inlineHelpText>The location street address</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LocationProgram__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The end of the period that we administer the program for this location.</description>
        <inlineHelpText>The end of the period that we administer the program for this location.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The location associated with the program and launch date</description>
        <inlineHelpText>The location associated with the program and launch date</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>LocationProgramLaunches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program associated with the location and launch date</description>
        <inlineHelpText>The program associated with the location and launch date</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>LocationProgramLaunches</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The location program launch date</description>
        <inlineHelpText>The location program launch date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Location Program</label>
    <nameField>
        <label>Location Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>MaximumLifetimeBenefitAmount__c</fullName>
        <description>The maximum amount an employee can be worth in tax credits from this program over the employee&apos;s entire employment period with a company.</description>
        <inlineHelpText>The maximum amount an employee can be worth in tax credits from this program over the employee&apos;s entire employment period with a company.</inlineHelpText>
        <label>Maximum Lifetime Benefit</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The program short name</description>
        <inlineHelpText>The program short name</inlineHelpText>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>StateAbbr__c</fullName>
        <label>State Abbreviation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalExecutiveDashboardController_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PortalExecutiveDashboardController_TEST {
        
        public Account a1 {get; set;}
        public Contact c1 {get; set;}
        public AccountHierarchyLevel__c l1;
        public AccountHierarchyLevel__c l2;
        public AccountHierarchyLevel__c l3;
        public AccountHierarchyMember__c ahm1;
        public AccountHierarchyMember__c ahm2;
        public AccountHierarchyMember__c ahm3;
        public Location__c loc1;
        public Program__c prog1;
        public State__c state;
        public LocationProgram__c lp1;
        
        private  void setupTestData(){
            a1 = new Account();
            a1.Name = 'TEST ACCOUNT';
            insert a1;
            
            c1=new Contact();
            c1.FirstName = 'test';
            c1.LastName = 'tester';
            c1.AccountId = a1.id;
            insert c1;
            
            l1 = new AccountHierarchyLevel__c();
            l1.Account__c = a1.id;
            l1.AccountHierarchyLevelLabelName__c = 'test level 1';
            l1.LevelNumber__c = 1;
            insert l1;
            
            l2 = new AccountHierarchyLevel__c();
            l2.Account__c = a1.id;
            l2.AccountHierarchyLevelLabelName__c = 'test level 2';
            l2.LevelNumber__c = 2;
            l2.AccountHierarchyLevel__c = l1.id;
            insert l2;
            
            l3 = new AccountHierarchyLevel__c();
            l3.Account__c = a1.id;
            l3.AccountHierarchyLevelLabelName__c = 'test level 3';
            l3.LevelNumber__c = 3;
            l3.AccountHierarchyLevel__c = l2.id;
            insert l3;  
            
            ahm1 = new AccountHierarchyMember__c();
            ahm1.AccountHierarchyMemberName__c = 'test';
            ahm1.AccountHierarchyLevel__c = l1.id;
            ahm1.AccountHierarchyMemberLabelName__c = 'test';
            ahm1.Account__c = a1.id;
            insert ahm1;
            
            ahm2 = new AccountHierarchyMember__c();
            ahm2.ParentAccountHierarchyMember__c = ahm1.id;
            ahm2.AccountHierarchyMemberName__c = 'test2';
            ahm2.AccountHierarchyLevel__c = l2.id;
            ahm2.AccountHierarchyMemberLabelName__c = 'test';
            ahm2.Account__c = a1.id;
            insert ahm2;
            
            ahm3 = new AccountHierarchyMember__c();
            ahm3.ParentAccountHierarchyMember__c = ahm2.id;
            ahm3.AccountHierarchyMemberName__c = 'test3';
            ahm3.AccountHierarchyLevel__c = l3.id;
            ahm3.AccountHierarchyMemberLabelName__c = 'test';
            ahm3.Account__c = a1.id;
            insert ahm3;
            
        }
        
        private void addProgramAndLocation(){
            state = new State__c();
            state.Name = 'test';
            state.StateAbbr__c = 'tst';
            insert state;
            
            loc1 = new Location__c();
            loc1.StreetAddressText__c = 'test';
            loc1.State__c = state.id;
            loc1.Name = 'test';
            loc1.CityName__c = 'test city';
            loc1.AccountHierarchyMember__c = ahm3.id;
            loc1.Account__c = a1.id;
            insert loc1;
            
            prog1 = new Program__c();
            prog1.ShortName__c = 'PROG';
            prog1.MaximumLifetimeBenefitAmount__c = 123.0;
            insert prog1;
            
            lp1 = new LocationProgram__c();
            lp1.Location__c = loc1.id;
            lp1.Program__c = prog1.id;
            lp1.StartDate__c = Date.today().addDays(-4000);
            lp1.EndDate__c = Date.today().addDays(4000);
            insert lp1;
            
        }
        
    static testMethod void testConstructor() {
        PortalExecutiveDashboardController_TEST pct = new PortalExecutiveDashboardController_TEST();
        pct.setupTestData();
        Apexpages.currentPage().getParameters().put('id', pct.c1.id);
        PortalExecutiveDashboardController pc = new PortalExecutiveDashboardController();
        pc.accountId = pct.a1.id;
        pc.userACM = pct.ahm1.id;
        pc.setupTopNode();
        system.assert(pc.lwList.size()>0);
        pc.lwList[0].setSelectVal('pickle');
        pc.getDisplayValue();
        
        PortalExecutiveDashboardController.locationProgramWrapper lw = new PortalExecutiveDashboardController.locationProgramWrapper(pct.lp1, 'grey');
        lw.ValidScreens = 3;
        lw.ScreenTransfersOut = 7;
        lw.PortalScreeningComplianceDenom = 10;
        lw.PortalScreeningComplianceNum = 98;
        lw.PortalQualificationNum=30;
        lw.documentDenom = 8;
        lw.documentNum = 10;
        lw.getDocumentCompliancePCNT();
        lw.getQualificationRatePCNT();
        lw.getScreening();
        lw.getScreeningCompliancePCNT();
        
    }
        
    static testMethod void testNodeChanges() {
              PortalExecutiveDashboardController_TEST pct = new PortalExecutiveDashboardController_TEST();
        pct.setupTestData();
        Apexpages.currentPage().getParameters().put('id', pct.c1.id);
        PortalExecutiveDashboardController pc = new PortalExecutiveDashboardController();
        pc.accountId = pct.a1.id;
        pc.userACM = pct.ahm1.id;
        pc.setupTopNode();
        
        pc.lwList[0].selectVal = '--Select--';
        pc.updateNodeList();
        System.Assert(pc.lwList.size()!=0);
        
        pc.lwList[0].selectVal = pct.ahm1.id;
        pc.updateNodeList();
        System.Assert(pc.lwList.size()!=0, '!!!!!!'+pc.lwList.size());
        
        pc.lwList[1].selectVal = pct.ahm2.id;
        pc.updateNodeList();
        System.Assert(pc.lwList.size()==3);
        
        pc.lwList[2].selectVal = pct.ahm3.id;
        pc.updateNodeList();
        System.Assert(pc.lwList.size()==3);
        
        pc.lwList[1].selectVal = '--Select--';
        pc.updateNodeList();
        System.Assert(pc.lwList.size()!=0);
        
        
        }
        
 static testMethod void testNodeChangesWithPrograms(){
                PortalExecutiveDashboardController_TEST pct = new PortalExecutiveDashboardController_TEST();
        pct.setupTestData();
        pct.addProgramAndLocation();
        Apexpages.currentPage().getParameters().put('id', pct.c1.id);
        PortalExecutiveDashboardController pc = new PortalExecutiveDashboardController();
				pc.accountId = pct.a1.id;
        pc.userACM = pct.ahm1.id;
        pc.setupTopNode();       
       
        pc.lwList[0].selectVal = '--Select--';
        pc.updateNodeList();
        System.Assert(pc.lwList.size()!=0);
        
        pc.lwList[0].selectVal = pct.ahm1.id;
        pc.updateNodeList();
        System.Assert(pc.lwList.size()!=0, '!!!!!!'+pc.lwList.size());
        
        pc.lwList[1].selectVal = pct.ahm2.id;
        pc.updateNodeList();
        System.Assert(pc.lwList.size()==3);
        
        pc.lwList[2].selectVal = pct.ahm3.id;
        pc.updateNodeList();
        System.Assert(pc.lwList.size()==3);
        
        pc.lwList[1].selectVal = '--Select--';
        pc.updateNodeList();
        System.Assert(pc.lwList.size()!=0);
        
        //getters and setters
        String val = pc.getselectedMemberId();
        val = pc.getselectedProgram();
        pc.setselectedMemberId(val);
        pc.setSelectedProgram(val);
        System.Assert(pc.lwList.size()!=0);
            }
            
 static testMethod void testExtendedListLink(){
                PortalExecutiveDashboardController_TEST pct = new PortalExecutiveDashboardController_TEST();
        pct.setupTestData();
        pct.addProgramAndLocation();
        Apexpages.currentPage().getParameters().put('id', pct.c1.id);
        PortalExecutiveDashboardController pc = new PortalExecutiveDashboardController();
        pc.accountId = pct.a1.id;
        pc.userACM = pct.ahm1.id;
        pc.setupTopNode();
        pc.lwList[0].selectVal = pct.ahm1.id;
        pc.expandedLocationLink();
        System.assert(pc.lwList.size() >0);
        
        Apexpages.currentPage().getParameters().put('id', pct.c1.id);
        Apexpages.currentPage().getParameters().put('levelIds', pct.ahm1.id+':--Select--');
        pc = new PortalExecutiveDashboardController();
        pc.accountId = pct.a1.id;
        pc.userACM = pct.ahm1.id;
        pc.setupTopNode();
        pc.expandedLocationSetup();
        System.assert(pc.lwList.size()>1);
        
        pc.nextLLPage();
        pc.previousLLPage();
        System.assert(pc.lwList.size()>1);
				String arf = pc.getselectedProgram();
        pc.setSelectedProgram('arf');
        pc.getselectedMemberId();
        pc.setselectedMemberId('123');
				System.assert(arf!=null);
            }
}