objects/Account.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>A short name for the client, to be used in communications.</description>
        <inlineHelpText>A short name for the client, to be used in communications.</inlineHelpText>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/AccountHierarchyMember__c.object
<CustomObject>
    <label>Account Hierarchy Member</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Hierarchy Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AccountHierarchyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The organizational level that this contact has access to, if the contact is a portal user.</description>
        <inlineHelpText>The organizational level that this contact has access to, if the contact is a portal user.</inlineHelpText>
        <label>Account Hierarchy Member</label>
        <referenceTo>AccountHierarchyMember__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExecutiveAccessBit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Contact can access all information related to his/her account in the portal.</description>
        <inlineHelpText>Contact can access all information related to his/her account in the portal.</inlineHelpText>
        <label>Executive Access</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/PortalNotification__c.object
<CustomObject>
    <description>History of email notifications sent regularly from the portal to portal users.</description>
    <fields>
        <fullName>PortalNotificationSchedule__c</fullName>
        <description>The schedule under which this portal notification email was sent.</description>
        <inlineHelpText>The schedule under which this portal notification email was sent.</inlineHelpText>
        <label>Portal Notification Schedule</label>
        <referenceTo>PortalNotificationSchedule__c</referenceTo>
        <relationshipLabel>Portal Notifications</relationshipLabel>
        <relationshipName>PortalNotifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Portal Notification</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Portal Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PortalNotificationSchedule__c.object
<CustomObject>
    <description>The schedule for each portal notification digest to be sent out to a contact.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact whose portal notification schedule this is.</description>
        <inlineHelpText>The contact whose portal notification schedule this is.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Notification Schedules</relationshipLabel>
        <relationshipName>PortalNotificationSchedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DigestType__c</fullName>
        <description>Specifies whether this is the next digest to be sent out is the first one, a continued one, the last one, or whether this digest frequency has ended for this contact. This informs the data period in the report.</description>
        <inlineHelpText>Specifies whether this is the next digest to be sent out is the first one, a continued one, the last one, or whether this digest frequency has ended for this contact. This informs the data period in the report.</inlineHelpText>
        <label>Digest Type</label>
        <picklist>
            <picklistValues>
                <fullName>First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>The frequency of this digest.</description>
        <inlineHelpText>The frequency of this digest.</inlineHelpText>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semiannually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NextDigestDate__c</fullName>
        <description>The next scheduled date that this digest will be sent out.</description>
        <inlineHelpText>The next scheduled date that this digest will be sent out.</inlineHelpText>
        <label>Next Digest Date</label>
        <type>Date</type>
    </fields>
    <label>Portal Notification Schedule</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Portal Notification Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Notification Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BATCH_EmailDigest.cls
global class BATCH_EmailDigest implements Database.Batchable<sObject>{
  /***********************************************/
  global database.querylocator start(Database.BatchableContext BC){
       return Database.getQueryLocator([ Select  p.NextDigestDate__c, p.Frequency__c, p.DigestType__c, p.Contact__c,
						p.Contact__r.AccountHierarchyMember__c,  p.Contact__r.Id, p.Contact__r.ExecutiveAccessBit__c, p.Contact__r.AccountId, 
						p.Contact__r.Account.Name, p.Contact__r.Name, p.Contact__r.Email, p.Contact__r.Account.ShortName__c
						From PortalNotificationSchedule__c p
						where (NextDigestDate__c = :Date.today() or
						(DigestType__c = 'First' and NextDigestDate__c = null))]);
  }
  /***********************************************/
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		Attachment a;
		PortalNotification__c pn;
		Datetime prevDate;
		Messaging.SingleEmailMessage[] emailList;// = new List<Messaging.SingleEmailMessage>();
		list <PortalNotificationSchedule__c>pNotificationList;// = new list<PortalNotificationSchedule__c>();
		list<PortalNotification__c> pnList;// = new list<PortalNotification__c>();
		list<Attachment> attachments;// = new list<Attachment>();
		PortalEmailDigestListCreate lc = new PortalEmailDigestListCreate();
		for(PortalNotificationSchedule__c p :(list<PortalNotificationSchedule__c>)scope){
			lc.addToLists(p);
		}
		lc.sendUpdateAndInsertInfo();
	}
	/***********************************************/
	global void finish(Database.BatchableContext BC){
		
	}
	/***********************************************/
	global static void runBatch(){
		BATCH_EmailDigest b = new BATCH_EmailDigest();
		Database.executeBatch(b);
	}

}