objects/Account.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>A short name for the client, to be used in communications.</description>
        <inlineHelpText>A short name for the client, to be used in communications.</inlineHelpText>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The client account that this employee (whether or not actually employed) belongs to.</description>
        <inlineHelpText>The client account that this employee (whether or not actually employed) belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>AccountEmployees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>The employee&apos;s federal social security number.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee&apos;s federal social security number.</inlineHelpText>
        <label>SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>EmploymentPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period tied to this survey</description>
        <inlineHelpText>The employment period tied to this survey</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EntityLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the survey was taken</description>
        <inlineHelpText>The location where the survey was taken</inlineHelpText>
        <label>Entity Location</label>
        <referenceTo>EntityLocation__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <description>The Entity associated with this Employment Period</description>
        <inlineHelpText>The Entity associated with this Employment Period</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</description>
        <inlineHelpText>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</inlineHelpText>
        <label>Location of Hire</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The official start date of the Employee associated with this Employment Period</description>
        <inlineHelpText>The official start date of the Employee associated with this Employment Period</inlineHelpText>
        <label>Hire Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account, or client, that this entity belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>AccountEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EntityLocation__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <description>Entity that has this location.</description>
        <inlineHelpText>Entity that has this location.</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location that hires under this entity.</description>
        <inlineHelpText>Location that hires under this entity.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity Location</label>
    <nameField>
        <label>Entity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The opening date of this location, when it first started hiring employees.</description>
        <inlineHelpText>The opening date of this location, when it first started hiring employees.</inlineHelpText>
        <label>Location Opening Date</label>
        <type>Date</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>MaximumLifetimeBenefitAmount__c</fullName>
        <description>The maximum amount an employee can be worth in tax credits from this program over the employee&apos;s entire employment period with a company.</description>
        <inlineHelpText>The maximum amount an employee can be worth in tax credits from this program over the employee&apos;s entire employment period with a company.</inlineHelpText>
        <label>Maximum Lifetime Benefit</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProgramEndSummary__c</fullName>
        <description>The overall end date of the program, calculated as the latest end date of the program&apos;s periods.</description>
        <inlineHelpText>The overall end date of the program, calculated as the latest end date of the program&apos;s periods.</inlineHelpText>
        <label>Program Expiration</label>
        <summarizedField>ProgramPeriod__c.EndDate__c</summarizedField>
        <summaryForeignKey>ProgramPeriod__c.Program__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProgramStartSummary__c</fullName>
        <description>The overall start date of the program, calculated as the earliest start date of the program&apos;s periods.</description>
        <inlineHelpText>The overall start date of the program, calculated as the earliest start date of the program&apos;s periods.</inlineHelpText>
        <label>Program Inception</label>
        <summarizedField>ProgramPeriod__c.StartDate__c</summarizedField>
        <summaryForeignKey>ProgramPeriod__c.Program__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The program short name</description>
        <inlineHelpText>The program short name</inlineHelpText>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SurveyProgramScreened__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program screened by the survey</description>
        <inlineHelpText>The program screened by the survey</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Program Screened</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Programs Screened Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Programs Screened</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PortalEmployeeStatsTesting.cls
@istest
private class PortalEmployeeStatsTesting {
		public SurveyProgramScreened__c sps;
		public Entity__c ent;
		public EntityLocation__c el;
		public Program__c p;
		public EmployeeSurvey__c es;
		public Account a;
		public Employee__c emp;
		public Location__c l;

	static testMethod void testEmployeeStats(){
			PortalEmployeeStatsTesting tc= new PortalEmployeeStatsTesting();
			tc.setupTestData();
			Apexpages.currentPage().getParameters().put('locId',tc.l.id);
			PortalLocationEmployeeStatsController c = new PortalLocationEmployeeStatsController();
			c.updateEmployeeList();
			c.nextPage();
			c.previousPage();
			c.startDateFilter = date.today().addDays(-1000).format();
			c.endDateFilter = date.today().format();
			c.DateScreen();
			c.updateEmployeeList();
			system.assert(c.employeeList.size()>0); 
	}

	private void setupTestData(){
			a = new Account();
    	a.Name = 'testa';
    	insert a;
    	
    	emp = new Employee__c();
    	emp.Account__c = a.id;
    	emp.FirstName__c = 'test';
    	emp.LastName__c = 'testington';
    	emp.SSN__c = '000-00-1234';
    	insert emp;
    	
      l = new Location__c();
    	l.Account__c = a.id;
    	l.Name = 'test';
    	
    	ent = new Entity__c();
    	ent.Account__c = a.id;
    	ent.Name = 'test';
    	insert ent;
    	    	
    	el = new EntityLocation__c();
    	el.Entity__c = ent.id;
    	el.Location__c = l.id;
    	
    	p = new Program__c();
    	p.ShortName__c='t';
    	p.Name = 'test';
    	p.MaximumLifetimeBenefitAmount__c = 100;
    	//p.ProgramStartSummary__c = Date.today();
    	//p.ProgramEndSummary__c = Date.today();
    	insert p;
    	
    	 
    	Employment__c em = new Employment__c();
    	em.Employee__c = emp.id;
    	em.Location__c = l.id;
    	em.StartDate__c = Date.today();
    	em.Entity__c = ent.id;
    	insert em;
    	
    	es = new EmployeeSurvey__c();
    	es.Name = 'test';
    	es.EmploymentPeriod__c = em.id;
    	es.EntityLocation__c = el.id;
    	insert es; 
	}
}