objects/Agency__c.object
<CustomObject>
    <description>The government agencies to whom tax credit programs report.</description>
    <fields>
        <fullName>AgencyEmail__c</fullName>
        <description>The agency email address</description>
        <inlineHelpText>The agency email address</inlineHelpText>
        <label>Agency Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SignatoryName__c</fullName>
        <description>The agency signatory&apos;s name</description>
        <inlineHelpText>The agency signatory&apos;s name</inlineHelpText>
        <label>Signatory Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Agency</label>
    <nameField>
        <label>Agency Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Area__c.object
<CustomObject>
    <description>The geographic areas defined by each program.</description>
    <fields>
        <fullName>AreaDefinitionMethod__c</fullName>
        <description>The method by which we can determine whether an address is in this area.</description>
        <inlineHelpText>The method by which we can determine whether an address is in this area.</inlineHelpText>
        <label>Area Definition Method</label>
        <picklist>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State/Province</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County Equivalent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip/Postal Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explicit Address Range</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geospatial Polygon</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The program short name</description>
        <inlineHelpText>The program short name</inlineHelpText>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The agency associated with the program zone and area</description>
        <inlineHelpText>The agency associated with the program zone and area</inlineHelpText>
        <label>Agency</label>
        <referenceTo>Agency__c</referenceTo>
        <relationshipName>ProgramAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The area associated with the program zone and agency</description>
        <inlineHelpText>The area associated with the program zone and agency</inlineHelpText>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipName>ProgramAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Periods</relationshipLabel>
        <relationshipName>ProgramPeriods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The date this program zone, area, agency combination began</description>
        <inlineHelpText>The date this program zone, area, agency combination began</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <label>Program Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PreventDuplicateProgramPeriod_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PreventDuplicateProgramPeriod_TEST{

private static Program__c Prgm;
private static Area__c Area;
private static Agency__c Agcy;
private static ProgramPeriod__c prgp;

  static{
  Prgm=new Program__c(Name='TestProgram', ShortName__c='TP');
  insert Prgm;
  
  Area=new Area__c(Name='Fremont',AreaDefinitionMethod__c='Country');
  insert Area;
    
  Agcy=new Agency__c(Name='Test Agency Name',SignatoryName__c='Test George',AgencyEmail__c='Test.vonhoff@myflorida.com');
  insert Agcy;
    
  prgp=new ProgramPeriod__c(Name='Test1991',Program__c=Prgm.Id,Area__c=Area.Id,Agency__c=Agcy.Id,StartDate__c=Date.today());
  insert prgp;
  }

  static testmethod void preventProgramPeriodDup(){
  ProgramPeriod__c ProgramPeriod=new ProgramPeriod__c();
  date startdate= date.parse('1/25/2010');
  ProgramPeriod.Program__c=Prgm.Id;
  ProgramPeriod.Area__c=Area.Id;
  ProgramPeriod.Agency__c=Agcy.Id;
  ProgramPeriod.StartDate__c=startdate;
  
  insert ProgramPeriod;
  //update ProgramPeriod;
  
  }
}