objects/Area__c.object
<CustomObject>
    <description>The geographic areas defined by each program.</description>
    <fields>
        <fullName>AreaDefinitionMethod__c</fullName>
        <description>The method by which we can determine whether an address is in this area.</description>
        <inlineHelpText>The method by which we can determine whether an address is in this area.</inlineHelpText>
        <label>Area Definition Method</label>
        <picklist>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State/Province</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County Equivalent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip/Postal Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explicit Address Range</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geospatial Polygon</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The program short name</description>
        <inlineHelpText>The program short name</inlineHelpText>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramCategory__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program associated with this category</description>
        <inlineHelpText>The program associated with this category</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Categories</relationshipLabel>
        <relationshipName>ProgramCategories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The short name for this program category, for succinct reporting.</description>
        <inlineHelpText>The short name for this program category, for succinct reporting.</inlineHelpText>
        <label>Short Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Program Category</label>
    <nameField>
        <label>Program Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategoryPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <description>The area linked to this program category</description>
        <inlineHelpText>The area linked to this program category</inlineHelpText>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipName>ProgramCategoryAreas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProgramCategory__c</fullName>
        <description>The program category linked to this area</description>
        <inlineHelpText>The program category linked to this area</inlineHelpText>
        <label>Program Category</label>
        <referenceTo>ProgramCategory__c</referenceTo>
        <relationshipName>ProgramCategoryAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The date this program category and area combination began</description>
        <inlineHelpText>The date this program category and area combination began</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Category Period</label>
    <nameField>
        <label>Program Category Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Category Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PreventDupProgramCategoryPeriod_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PreventDupProgramCategoryPeriod_TEST{

private static program__c prg;
private static ProgramCategory__c Prgcat;
private static Area__c Area;
private static ProgramCategoryPeriod__c prgcatpriod;

  static{
  prg=new program__c(Name='TestProgram', ShortName__c='TP');
  insert prg;
  
  Prgcat=new ProgramCategory__c(Name='Test Program Category',Program__c=prg.Id);
  insert Prgcat;
  
  Area=new Area__c(Name='San Jose',AreaDefinitionMethod__c='State/Province'); 
  insert Area;
  
  prgcatpriod=new ProgramCategoryPeriod__c(Name='TestPQ9999',ProgramCategory__c=Prgcat.Id,Area__c=Area.Id,StartDate__c=Date.today());
  insert prgcatpriod;
  }
  static testmethod void PreventProgramCategoryPeriodDup(){
  ProgramCategoryPeriod__c ProgramCategoryPeriod=new ProgramCategoryPeriod__c();
  date startdate= date.parse('4/20/2011');
  ProgramCategoryPeriod.ProgramCategory__c=Prgcat.Id;
  ProgramCategoryPeriod.Area__c=Area.Id; 
  ProgramCategoryPeriod.Name='TestPCP786';
  ProgramCategoryPeriod.StartDate__c=startdate;
  
  insert ProgramCategoryPeriod;
  //update ProgramCategoryPeriod;  
  
  }
  }