objects/Audience__c.object
<CustomObject>
    <fields>
        <fullName>AudienceEID__c</fullName>
        <label>AudienceEID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContentModule__c.object
<CustomObject>
    <fields>
        <fullName>ContentModuleEID__c</fullName>
        <label>ContentModuleEID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>ContentModule</label>
    <nameField>
        <label>ContentModule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentModules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContentType__c.object
<CustomObject>
    <fields>
        <fullName>ContentTypeEID__c</fullName>
        <label>ContentTypeEID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>ContentType</label>
    <nameField>
        <label>ContentType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>LanguageEID__c</fullName>
        <label>LanguageEID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TESTDATA_makeEmailNotificationData.cls
public class TESTDATA_makeEmailNotificationData {
	public list<Language__c> lList;
	public list<Audience__c> aList;
	public list<ContentType__c> ctList;
	public list<ContentModule__c> cmList;

	public TESTDATA_makeEmailNotificationData(){}
	
	public void makeRequiredData(){
		//Languages
		lList = new list<Language__c>();
		Language__c l = new Language__c();
		l.Name = 'English';
		l.LanguageEID__c = 1;
		if(test.isRunningTest()) l.LanguageEID__c+=30000.78;
		lList.add(l);
		
		l = new Language__c();
		l.Name = 'Spanish';
		l.LanguageEID__c = 2;
		if(test.isRunningTest()) l.LanguageEID__c+=30000.78;
		lList.add(l);
		
		insert lList;
		
		//Audience
		aList = new list<Audience__c>();
		Audience__c a = new Audience__c();
		a.AudienceEID__c = 1;
		if(test.isRunningTest()) a.AudienceEID__c+=30000.78;
		a.Name = 'Employee';
		aList.add(a);

		a = new Audience__c();
		a.AudienceEID__c = 2;
		a.Name = 'Location Manager';
		if(test.isRunningTest()) a.AudienceEID__c+=30000.78;
		aList.add(a);
		
		a = new Audience__c();
		a.AudienceEID__c = 3;
		a.Name = 'District Manager';
		if(test.isRunningTest()) a.AudienceEID__c+=30000.78;
		aList.add(a);		
	
		a = new Audience__c();
		a.AudienceEID__c = 4;
		a.Name = 'Executive';
		if(test.isRunningTest()) a.AudienceEID__c+=30000.78;
		aList.add(a);
		
		a = new Audience__c();
		a.AudienceEID__c = 5;
		if(test.isRunningTest()) a.AudienceEID__c+=30000.78;
		a.Name = 'All';
		aList.add(a);
		
		insert aList;
		
		//ContentType
		ctList = new list<ContentType__c>();
		ContentType__c ct = new ContentType__c();
		ct.ContentTypeEID__c = 1;
		if(test.isRunningTest()) ct.ContentTypeEID__c+=30000.78;
		ct.Name = 'Intro';
		ctList.add(ct);
		
		ct = new ContentType__c();
		ct.ContentTypeEID__c = 2;
		if(test.isRunningTest()) ct.ContentTypeEID__c+=30000.78;
		ct.Name = 'Outro';
		ctList.add(ct);
		
		ct = new ContentType__c();
		ct.ContentTypeEID__c = 3;
		if(test.isRunningTest()) ct.ContentTypeEID__c+=30000.78;
		ct.Name = 'Preamble';
		ctList.add(ct);
		
		ct = new ContentType__c();
		ct.ContentTypeEID__c = 4;
		if(test.isRunningTest()) ct.ContentTypeEID__c+=30000.78;
		ct.Name = 'Footnote';
		ctList.add(ct);
		
		insert ctList;
		
		//ContentModules
		cmList = new list<ContentModule__c>();
		ContentModule__c cm = new ContentModule__c();
		cm.ContentModuleEID__c =1;
		if(test.isRunningTest()) cm.ContentModuleEID__c+=30000.78;
		cm.Name = 'Body';
		cmList.add(cm);
		
		cm = new ContentModule__c();
		cm.ContentModuleEID__c =2;
		if(test.isRunningTest()) cm.ContentModuleEID__c+=30000.78;
		cm.Name = 'Screening Needed';
		cmList.add(cm);
		
		cm = new ContentModule__c();
		cm.ContentModuleEID__c =3;
		if(test.isRunningTest()) cm.ContentModuleEID__c+=30000.78;
		cm.Name = 'Documents Needed';
		cmList.add(cm);
		
		cm = new ContentModule__c();
		cm.ContentModuleEID__c =4;
		if(test.isRunningTest()) cm.ContentModuleEID__c+=30000.78;
		cm.Name = 'Compliance Summary';
		cmList.add(cm);
		
		insert cmList;
	}
	
	private static testmethod void test(){
		TESTDATA_makeEmailNotificationData td = new TESTDATA_makeEmailNotificationData();
		td.makeRequiredData();
	}
}