objects/County__c.object
<CustomObject>
    <description>Counties by state. Currently only US counties, but can include non-US equivalents.</description>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The state where the county is located.</description>
        <inlineHelpText>The state where the county is located.</inlineHelpText>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Counties</relationshipLabel>
        <relationshipName>Counties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The client account that this employee (whether or not actually employed) belongs to.</description>
        <inlineHelpText>The client account that this employee (whether or not actually employed) belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>AccountEmployees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BirthDate__c</fullName>
        <description>The employee&apos;s date of birth.</description>
        <inlineHelpText>The employee&apos;s date of birth.</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlowSession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flow Session</label>
        <referenceTo>FlowSession__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MiddleName__c</fullName>
        <description>The employee&apos;s middle name. May be an initial. No punctuation needed.</description>
        <inlineHelpText>The employee&apos;s middle name. May be an initial. No punctuation needed.</inlineHelpText>
        <label>Middle Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>The employee&apos;s federal social security number.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee&apos;s federal social security number.</inlineHelpText>
        <label>SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EmployeeAddress__c.object
<CustomObject>
    <description>A history of addresses for each employee.</description>
    <fields>
        <fullName>CityName__c</fullName>
        <description>City name</description>
        <inlineHelpText>City name</inlineHelpText>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County name</description>
        <inlineHelpText>County name</inlineHelpText>
        <label>County</label>
        <referenceTo>County__c</referenceTo>
        <relationshipLabel>Employee Addresses</relationshipLabel>
        <relationshipName>CountyEmployeeAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <description>The date this address became the employee&apos;s address</description>
        <inlineHelpText>The date this address became the employee&apos;s address</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The employee associated with this address</description>
        <inlineHelpText>The employee associated with this address</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Addresses</relationshipLabel>
        <relationshipName>EmployeeAddresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FlowSession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flow Session</label>
        <referenceTo>FlowSession__c</referenceTo>
        <relationshipLabel>Employee Addresses</relationshipLabel>
        <relationshipName>EmployeeAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>15</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>15</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>State name</description>
        <inlineHelpText>State name</inlineHelpText>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Employee Addresses</relationshipLabel>
        <relationshipName>StateEmployeeAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <description>The employee&apos;s full street address including suite, apartment, etc.</description>
        <inlineHelpText>The employee&apos;s full street address including suite, apartment, etc.</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>Zip Code</description>
        <inlineHelpText>Zip Code</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Employee Address</label>
    <nameField>
        <label>Employee Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>DepartmentName__c</fullName>
        <description>The Department in which the Employee works</description>
        <inlineHelpText>The Department in which the Employee works</inlineHelpText>
        <label>Department</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <description>The Entity associated with this Employment Period</description>
        <inlineHelpText>The Entity associated with this Employment Period</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FlowSession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flow Session</label>
        <referenceTo>FlowSession__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>EmploymentPeriods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InitialHourlyRateAmount__c</fullName>
        <description>If applicable, the Initial Hourly Rate of the Employee associated with this Employment Period</description>
        <inlineHelpText>If applicable, the Initial Hourly Rate of the Employee associated with this Employment Period</inlineHelpText>
        <label>Initial Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The official start date of the Employee associated with this Employment Period</description>
        <inlineHelpText>The official start date of the Employee associated with this Employment Period</inlineHelpText>
        <label>Hire Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account, or client, that this entity belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>AccountEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CityName__c</fullName>
        <description>The location&apos;s city.</description>
        <inlineHelpText>The location&apos;s city.</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location county</description>
        <inlineHelpText>The location county</inlineHelpText>
        <label>County</label>
        <referenceTo>County__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The opening date of this location, when it first started hiring employees.</description>
        <inlineHelpText>The opening date of this location, when it first started hiring employees.</inlineHelpText>
        <label>Location Opening Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location state</description>
        <inlineHelpText>The location state</inlineHelpText>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <description>The location street address</description>
        <inlineHelpText>The location street address</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>The location zip</description>
        <inlineHelpText>The location zip</inlineHelpText>
        <label>Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SaveEmployeeInformationPlugin.cls
global class SaveEmployeeInformationPlugin implements Process.Plugin{

    global Process.PluginResult invoke(Process.PluginRequest request)
    {
        String AccountId = (String)request.inputParameters.get('AccountId');
        String EntityId = (String)request.inputParameters.get('EntityId');
        String LocationId = (String)request.inputParameters.get('LocationId');
        String FirstName = (String)request.inputParameters.get('FirstName');
        String MiddleName = (String)request.inputParameters.get('MiddleName');
        String LastName = (String)request.inputParameters.get('LastName');
        Date Birthday = Date.valueOf((Datetime)request.inputParameters.get('Birthday'));
        String SSN = (String)request.inputParameters.get('SSN');
        String SessionId  = (String)request.inputParameters.get('SessionId');
        
        String Street = (String)request.inputParameters.get('Street');
        String City = (String)request.inputParameters.get('City');
        String State = (String)request.inputParameters.get('State');
        String ZipCode = (String)request.inputParameters.get('ZipCode');
        String County = (String)request.inputParameters.get('County');
        Decimal Latitude = (Decimal)request.inputParameters.get('Latitude');
        Decimal Longitude = (Decimal)request.inputParameters.get('Longitude');
        
        Date HireDate = Date.valueOf((Datetime)request.inputParameters.get('HireDate'));
        Decimal HourlyWage = (Decimal)request.inputParameters.get('HourlyWage');
        String JobTitle = (String)request.inputParameters.get('JobTitle');
        String Department = (String)request.inputParameters.get('Department');
        
        string EmployeeSFID = '';
        string EmployeeAddressSFID = '';
        string EmploymentSFID = '';

        
        Employee__c emp = new Employee__c(Account__c = AccountId, 
                                        FirstName__c = FirstName, 
                                        LastName__c = LastName, 
                                        MiddleName__c = MiddleName, 
                                        BirthDate__c = Birthday,
                                        SSN__c = SSN,
                                        FlowSession__c = SessionId);
        insert emp;
        
        EmployeeSFID = emp.Id;
        
        EmployeeAddress__c eaddr = new EmployeeAddress__c(Employee__c = emp.Id, 
                                                    CityName__c = City,
                                                    County__c = County,
                                                    EffectiveDate__c = HireDate,
                                                    Latitude__c = Latitude,
                                                    Longitude__c = Longitude,
                                                    State__c = State,
                                                    StreetAddressText__c = Street,
                                                    ZipCode__c = ZipCode,
                                                    FlowSession__c = SessionId);
                                                    
        insert eaddr;
        
        EmployeeAddressSFID =  eaddr.Id;                                
        
        
        Employment__c hire = new Employment__c(Employee__c = emp.Id,
                                            DepartmentName__c = Department,
                                            Entity__c = EntityId,
                                            StartDate__c = HireDate,
                                            InitialHourlyRateAmount__c = HourlyWage,
                                            JobTitleName__c = JobTitle,
                                            Location__c = LocationId,
                                            FlowSession__c = SessionId,
                                            Status__c = 'Hired');
        
        insert hire;
        
        EmploymentSFID = hire.Id;
        

        
        
        
        
        
        Map<String, Object> result = new Map<String, Object>();
        result.put('EmployeeSFID',EmployeeSFID);
        result.put('EmployeeAddressSFID',EmployeeAddressSFID);
        result.put('EmploymentSFID',EmploymentSFID);
        
        return new Process.PluginResult(result);   
    }
    
    global Process.PluginDescribeResult describe(){
        
        Process.PluginDescribeResult  result = new Process.PluginDescribeResult();
        
        result.inputParameters = new List<Process.PluginDescribeResult.InputParameter>{
            new Process.PluginDescribeResult.InputParameter('AccountId', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('EntityId', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('LocationId', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('FirstName', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('MiddleName', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('LastName', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('Birthday', Process.PluginDescribeResult.ParameterType.DATETIME, true),
            new Process.PluginDescribeResult.InputParameter('SSN', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('Street', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('City', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('State', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('ZipCode', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('County', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('Latitude', Process.PluginDescribeResult.ParameterType.DECIMAL, true),
            new Process.PluginDescribeResult.InputParameter('Longitude', Process.PluginDescribeResult.ParameterType.DECIMAL, true),
           new Process.PluginDescribeResult.InputParameter('HireDate', Process.PluginDescribeResult.ParameterType.DATETIME, true),
            new Process.PluginDescribeResult.InputParameter('HourlyWage', Process.PluginDescribeResult.ParameterType.DECIMAL, true),
            new Process.PluginDescribeResult.InputParameter('JobTitle', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('Department', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('SessionId', Process.PluginDescribeResult.ParameterType.STRING, true)
            
        };
        
        result.outputParameters = new List<Process.PluginDescribeResult.OutputParameter>{
            new Process.PluginDescribeResult.OutputParameter('EmployeeSFID', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('EmployeeAddressSFID', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('EmploymentSFID', Process.PluginDescribeResult.ParameterType.STRING)
        };
        
        return result;            
    }       
}