objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>CreditEID__c</fullName>
        <description>The Enterprise ID for this Credit.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this Credit.</inlineHelpText>
        <label>Credit EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <description>The program qualification that this credit is valid under.</description>
        <inlineHelpText>The program qualification that this credit is valid under.</inlineHelpText>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The start date of the period over which this credit is valid.</description>
        <inlineHelpText>The start date of the period over which this credit is valid.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <label>Credit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey qualified for this program</description>
        <inlineHelpText>The survey qualified for this program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BATCH_RunUpdateOnCredit.cls
global class BATCH_RunUpdateOnCredit implements Database.Batchable<sObject>{
public String query{get; set;}
    
    global void setDefaultQuery(){
        this.query = 'Select StartDate__c From Credit__c';
        if(test.isRunningTest()) this.query = 'Select StartDate__c From Credit__c limit 50';
    }
    
    global database.querylocator start(Database.BatchableContext BC){
            return Database.getQueryLocator(query);
    }
    
  global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Credit__c> obs = new List<Credit__c>();
				Date sd;
        for(Credit__c s :(list<Credit__c>)scope){
          sd = s.StartDate__c;
          s.StartDate__c = sd;
         	//name = sps.Survey__c;
         	//sps.Survey__c = name;   
          obs.add(s);
        }

        update obs;
    }

    global void finish(Database.BatchableContext BC){
         
    }
	global static void runBatch(){
		BATCH_RunUpdateOnCredit b = new BATCH_RunUpdateOnCredit();
		b.setDefaultQuery();
		Database.executeBatch(b);
	}
	
    static testMethod void Test_BATCH_RunUpdateOnCredit() {
    		ProgramQualification__c pq = [select id from ProgramQualification__c limit 1];
    		Credit__c c = new Credit__c();
    		c.CreditEID__c = 123.1231;
    		c.ProgramQualification__c = pq.id;
    		insert c;
    		test.startTest();
    		
        BATCH_RunUpdateOnCredit.runBatch();
        test.stopTest();
    }	
}