objects/DocumentRequirement__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Document Requirements</relationshipLabel>
        <relationshipName>DocumentRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Requirement</label>
    <nameField>
        <label>Document Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The client account that this employee (whether or not actually employed) belongs to.</description>
        <inlineHelpText>The client account that this employee (whether or not actually employed) belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>AccountEmployees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MiddleName__c</fullName>
        <description>The employee&apos;s middle name. May be an initial. No punctuation needed.</description>
        <inlineHelpText>The employee&apos;s middle name. May be an initial. No punctuation needed.</inlineHelpText>
        <label>Middle Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>The employee&apos;s federal social security number.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee&apos;s federal social security number.</inlineHelpText>
        <label>SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <description>The Entity associated with this Employment Period</description>
        <inlineHelpText>The Entity associated with this Employment Period</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account, or client, that this entity belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>AccountEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The agency associated with the program zone and area</description>
        <inlineHelpText>The agency associated with the program zone and area</inlineHelpText>
        <label>Agency</label>
        <referenceTo>Agency__c</referenceTo>
        <relationshipName>ProgramAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The area associated with the program zone and agency</description>
        <inlineHelpText>The area associated with the program zone and agency</inlineHelpText>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipName>ProgramAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Periods</relationshipLabel>
        <relationshipName>ProgramPeriods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <label>Program Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period that this program qualification is under.</description>
        <inlineHelpText>The employment period that this program qualification is under.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramPeriod__c</fullName>
        <description>The program period that the employee qualifies under</description>
        <inlineHelpText>The program period that the employee qualifies under</inlineHelpText>
        <label>Program Period</label>
        <referenceTo>ProgramPeriod__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QualificationDocumentOption__c.object
<CustomObject>
    <fields>
        <fullName>RepositoryDocument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The repository document that fulfills this function for this employee</description>
        <inlineHelpText>The repository document that fulfills this function for this employee</inlineHelpText>
        <label>Repository Document</label>
        <referenceTo>RepositoryDocument__c</referenceTo>
        <relationshipLabel>Qualification Document Options</relationshipLabel>
        <relationshipName>QualificationDocumentOptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Qualification Document Option</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Qualification Document Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Document Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QualificationDocumentRequirement__c.object
<CustomObject>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipName>QualificationRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Qualification Document Requirement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Qualification Document Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Document Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RepositoryDocument__c.object
<CustomObject>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period to which this document belongs. If it is an employee document, it must be related to an employment period. If it applies across multiple hire dates, multiple records should be entered (this should happen only about 5% of the time).</description>
        <inlineHelpText>The employment period to which this document belongs. If it is an employee document, it must be related to an employment period. If it applies across multiple hire dates, multiple records should be entered (this should happen only about 5% of the time).</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Repository Documents</relationshipLabel>
        <relationshipName>RepositoryDocuments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Repository Document</label>
    <nameField>
        <label>Repository Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repository Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateRepositoryDocument_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CreateRepositoryDocument_Test {

	public static Account a;	
	public static Entity__c ent;
	public static Employee__c employee;
	public static Employment__c emplnt;
	public static Area__c area;
	public static Agency__c agcy;
	public static Program__c prog;
	public static ProgramPeriod__c prgperiod;
	public static ProgramQualification__c progQual;
	public static RepositoryDocument__c repDoc,repDoc2,repDoc3;
	public static List<RepositoryDocument__c> RepDocList;

	static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
		a = new Account(Name='Test Account');
		insert a;
		
		ent = new Entity__c(Account__c = a.Id, Name = 'TestEntity');
		insert ent;
		
		employee = new Employee__c(FirstName__c ='Emp1',Account__c = a.Id, LastName__c ='Lname',MiddleName__c = 'MName', SSN__c = '343532523');
		insert employee;
		
		emplnt = new Employment__c(Employee__c = employee.Id, Entity__c = ent.Id, Status__c = 'Hired',StartDate__c = System.today().addDays(-30));
		insert emplnt;
		
		area = new Area__c(Name='United States (50 states and DC)', AreaDescriptionText__c ='Test Area');
		insert area;
		
		Agcy = new Agency__c(Name='Test Agency');
		insert Agcy;
		
		prog = new Program__c(Name='Test Program');
		insert prog;
		
		prgperiod = new ProgramPeriod__c(Name='Test Program period',Program__c=prog.Id, Area__c=area.Id,Agency__c=Agcy.Id,StartDate__c=System.today().addDays(-40));
		insert prgperiod;
		
		progQual = new ProgramQualification__c(Name='TestProgramQualification',Employment__c = emplnt.Id, ProgramPeriod__c = prgperiod.Id);
		insert progQual;
		
		DocumentStatus__c  dst  = new DocumentStatus__c  (Name = 'Good' , RankOrder__c = 1);
		Insert dst;
		
		DocumentStatus__c  dst1  = new DocumentStatus__c  (Name = 'Test' , RankOrder__c = 1);
		Insert dst1;
		
		Program__c pr = new Program__c(Name='TestProgram');
		insert pr;
		
		DocumentRequirement__c docReq = new DocumentRequirement__c(Name = 'Address Verification', Program__c = pr.Id );
		insert docReq ;
		
		QualificationDocumentRequirement__c qualReq = new QualificationDocumentRequirement__c(ProgramQualification__c = progQual.Id, DocumentRequirement__c = docReq.Id);
		insert qualReq;            
		
		DocumentStep__c docrolestep = new DocumentStep__c(Name ='docRoleStep' , DocumentRequirement__c  = docReq.Id);       
		insert docrolestep;
		
		QualificationDocumentStep__c quarolestep =new QualificationDocumentStep__c(DocumentStep__c = docrolestep.Id, QualificationDocumentRequirement__c = qualReq.Id);
		insert quarolestep;
		
		Documenttype__c doctype = new Documenttype__c(Name ='Form 8850',DocumentTypeAbbr__c ='F8850',Usage__c = 'Active',/*Source__c = 'Client',*/DocumentationStage__c = 'Prerequisite');
		insert doctype;
		System.assertEquals('Form 8850', [select name from Documenttype__c where id =:doctype.id ].Name);
		
		DocumentOption__c docOpt = new DocumentOption__c(DocumentStep__c= docrolestep.Id,DocumentType__c = doctype.Id);
		insert docOpt ;
		 
		QualificationDocumentOption__c Qdo = new QualificationDocumentOption__c( DocumentOption__c = docOpt.Id, QualificationDocumentStep__c = quarolestep.Id );
		insert Qdo;
		 
		Documenttype__c doctype2 = new Documenttype__c(Name ='Form 8850',DocumentTypeAbbr__c ='F850',Usage__c = 'Active',/*Source__c = 'Client',*/DocumentationStage__c = 'Prerequisite');
		    insert doctype2;
		     
	    repDoc = new RepositoryDocument__c (Name ='Test 2',DocumentType__c =doctype.Id, LaserficheDocumentId__c = 6546575, Employment__c = emplnt.Id, DocumentStatus__c = dst.Id);
	    repDoc2 = new RepositoryDocument__c(Name ='Test 1',DocumentType__c =doctype2.Id, LaserficheDocumentId__c = 654575, Employment__c = emplnt.Id, DocumentStatus__c = dst.Id);
	  	repDoc3 = new RepositoryDocument__c(Name ='Test 2',DocumentType__c =doctype2.Id, LaserficheDocumentId__c = 654575, Employment__c = emplnt.Id, DocumentStatus__c = dst.Id);
	   	RepDocList = new List<RepositoryDocument__c>{repDoc,repDoc2,repDoc3};
	    insert RepDocList;
		     
	     test.starttest();
	     repDoc2.DocumentType__c = doctype.Id;      
	     update repDoc2;
	     
	     repDoc2.DocumentStatus__c = dst1.Id;
	     update repDoc2;
	     repDoc2.DocumentType__c = doctype2.Id;      
	     update repDoc2;
	      
	     repDoc.LaserficheDocumentId__c = 654575;      
	     update repDoc2;
	          
	     DocumentStatus__c  dst2  = [select Id from DocumentStatus__c where RankOrder__c = 3];           
	     Qdo.DocumentStatusGenerated__c = dst2.Id;
	     update Qdo;
	     test.stoptest();

         
         
    } 
}