objects/DocumentStatus__c.object
<CustomObject>
    <description>The document score and status for all levels of the document management process.</description>
    <fields>
        <fullName>DocumentStatusEID__c</fullName>
        <description>The Enterprise ID for this document status.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this document status.</inlineHelpText>
        <label>Document Status EID</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RankOrder__c</fullName>
        <description>The rank of importance of this document score.</description>
        <inlineHelpText>The rank of importance of this document score.</inlineHelpText>
        <label>Rank Order</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document Status</label>
    <nameField>
        <label>Document Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramCategoryQualification__c.object
<CustomObject>
    <label>Program Category Qualification</label>
    <nameField>
        <label>Program Category Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Category Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QualificationDocumentRequirement__c.object
<CustomObject>
    <fields>
        <fullName>DocumentStatusExternal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The document status as shown to the client, based on documents that are sourced from the employee.</description>
        <inlineHelpText>The document status as shown to the client, based on documents that are sourced from the employee.</inlineHelpText>
        <label>Document Status External</label>
        <referenceTo>DocumentStatus__c</referenceTo>
        <relationshipLabel>Qualification Document Requirements (Document Status External)</relationshipLabel>
        <relationshipName>QualificationDocumentRequirementExternal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocumentStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The status of this document requirement.</description>
        <inlineHelpText>The status of this document requirement.</inlineHelpText>
        <label>Document Status</label>
        <referenceTo>DocumentStatus__c</referenceTo>
        <relationshipLabel>Qualification Document Requirements</relationshipLabel>
        <relationshipName>QualificationDocumentRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramCategoryQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program category qualification associated with this requirement status</description>
        <inlineHelpText>The program category qualification associated with this requirement status</inlineHelpText>
        <label>Program Category Qualification</label>
        <referenceTo>ProgramCategoryQualification__c</referenceTo>
        <relationshipName>QualificationRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Qualification Document Requirement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Qualification Document Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Document Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BATCH_QDRUpdate.cls
global class BATCH_QDRUpdate implements Database.Batchable<sObject>{
  public string q{get; set;}
  /***********************************************/
	global void setDefaultQuery(){
		q = 'Select q.DocumentStatus__c, q.ProgramCategoryQualification__c From QualificationDocumentRequirement__c q where ProgramCategoryQualification__c != null';
		if(test.isRunningTest()) q = 'Select q.DocumentStatus__c, q.ProgramCategoryQualification__c From QualificationDocumentRequirement__c q limit 10'; 
	}
  /***********************************************/
  global database.querylocator start(Database.BatchableContext BC){
       return Database.getQueryLocator(q);
  }
  /***********************************************/
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		//make nonsenst Document status
			DocumentStatus__c ds = new DocumentStatus__c();
			ds.name = 'batch';
			ds.DocumentStatusEID__c =3.14444;
			ds.RankOrder__c = 1.0;
			insert ds;
			
			//make map of qdr ids to qdr.DocumentStatusEID__c value(for backup)
			//set doc status eid to nonsense value
			map<string, string> qdrEIDmap = new map<string, string>();
			list<QualificationDocumentRequirement__c> qdrList = new list<QualificationDocumentRequirement__c>();
			for(QualificationDocumentRequirement__c qdr : (list<QualificationDocumentRequirement__c>)scope){
				qdrEIDmap.put(qdr.id, qdr.DocumentStatus__c);
				qdr.DocumentStatusExternal__c = ds.id;	
				qdrList.add(qdr);	
			}
			update qdrList;
			
			//set QDRS to original values
			for(QualificationDocumentRequirement__c qdr : qdrList){
				qdr.DocumentStatusExternal__c = qdrEIDmap.get(qdr.id);		
			}
			update qdrList;
			
			//delete nonsense ds
			delete ds;	
	}
	/***********************************************/
	global void finish(Database.BatchableContext BC){
		
	}
	/***********************************************/
	global static void runBatch(){
		BATCH_QDRUpdate b = new BATCH_QDRUpdate();
		b.setDefaultQuery();
		Database.executeBatch(b, 100);
	}
	/***********************************************/
	static testMethod void Test_BATCH_RunUpdateOnCredit() {
    		test.startTest();
        BATCH_QDRUpdate.runBatch();
        test.stopTest();
    }	

}