objects/DocumentStatus__c.object
<CustomObject>
    <description>The document score and status for all levels of the document management process.</description>
    <fields>
        <fullName>DocumentStatusEID__c</fullName>
        <description>The Enterprise ID for this document status.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this document status.</inlineHelpText>
        <label>Document Status EID</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RankOrder__c</fullName>
        <description>The rank of importance of this document score.</description>
        <inlineHelpText>The rank of importance of this document score.</inlineHelpText>
        <label>Rank Order</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document Status</label>
    <nameField>
        <label>Document Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategoryQualification__c.object
<CustomObject>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the qualified program for an employee</description>
        <inlineHelpText>Indicates the qualified program for an employee</inlineHelpText>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipLabel>Program Category Qualifications</relationshipLabel>
        <relationshipName>ProgramCategoryQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Category Qualification</label>
    <nameField>
        <label>Program Category Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Category Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramPeriod__c.object
<CustomObject>
    <label>Program Period</label>
    <nameField>
        <label>Program Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period that this program qualification is under.</description>
        <inlineHelpText>The employment period that this program qualification is under.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramPeriod__c</fullName>
        <description>The program period that the employee qualifies under</description>
        <inlineHelpText>The program period that the employee qualifies under</inlineHelpText>
        <label>Program Period</label>
        <referenceTo>ProgramPeriod__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QualificationDocumentRequirement__c.object
<CustomObject>
    <fields>
        <fullName>DocumentStatusEIDFormula__c</fullName>
        <formula>DocumentStatus__r.DocumentStatusEID__c</formula>
        <label>Document Status EID Formula</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DocumentStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The status of this document requirement.</description>
        <inlineHelpText>The status of this document requirement.</inlineHelpText>
        <label>Document Status</label>
        <referenceTo>DocumentStatus__c</referenceTo>
        <relationshipLabel>Qualification Document Requirements</relationshipLabel>
        <relationshipName>QualificationDocumentRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramCategoryQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program category qualification associated with this requirement status</description>
        <inlineHelpText>The program category qualification associated with this requirement status</inlineHelpText>
        <label>Program Category Qualification</label>
        <referenceTo>ProgramCategoryQualification__c</referenceTo>
        <relationshipName>QualificationRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipName>QualificationRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Qualification Document Requirement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Qualification Document Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Document Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QualificationProcessStage__c.object
<CustomObject>
    <description>The stages that a qualification can be in.</description>
    <fields>
        <fullName>RankOrder__c</fullName>
        <description>The order of importance of this qualification process stage.</description>
        <inlineHelpText>The order of importance of this qualification process stage.</inlineHelpText>
        <label>Rank Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document Process Stage</label>
    <nameField>
        <label>Document Process Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Process Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/wktLocationEmployeeProgram__c.object
<CustomObject>
    <description>A generated list of locations with employees and programs.</description>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period in question.</description>
        <inlineHelpText>The employment period in question.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicable period of this program.</description>
        <inlineHelpText>The applicable period of this program.</inlineHelpText>
        <label>Program Period</label>
        <referenceTo>ProgramPeriod__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program qualification connected to this employee at this location.</description>
        <inlineHelpText>The program qualification connected to this employee at this location.</inlineHelpText>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeePrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QualificationProcessStage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The current process stage of this employee for this program.</description>
        <inlineHelpText>The current process stage of this employee for this program.</inlineHelpText>
        <label>Qualification Process Stage</label>
        <referenceTo>QualificationProcessStage__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeePrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>wkt Location Employee Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Location Employee Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>wkt Location Employee Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BATCH_QualificationDocumentTrigger.cls
global class BATCH_QualificationDocumentTrigger implements Database.Batchable<sObject>{
	public string q{get; set;}
	
	/***********************************************/
	global void setDefaultQuery(){
		q = 'Select Employment__c, QualificationProcessStage__c From wktLocationEmployeeProgram__c where QualificationProcessStage__c != null';
		if(test.isRunningTest()) q = 'Select Employment__c From wktLocationEmployeeProgram__c limit 10'; 
	}
	/***********************************************/
	global static void runBatch(){
      BATCH_QualificationDocumentTrigger b = new BATCH_QualificationDocumentTrigger();
      b.setDefaultQuery();
      Database.executeBatch(b, 50);
    }
	/***********************************************/
  global database.querylocator start(Database.BatchableContext BC){
  	return Database.getQueryLocator(q);
  }
 /***********************************************/
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		//get list of employee ids
		list<String> empIds = new list<string>();
		for(wktLocationEmployeeProgram__c wkt : (list<wktLocationEmployeeProgram__c>)scope){
			empIds.add(wkt.Employment__c);
		}
		
		//get QDRs that have pq referencing employments
		for(list<QualificationDocumentRequirement__c> qdrList : [Select q.ProgramQualification__r.Employment__c, q.ProgramQualification__c, 
																												q.ProgramCategoryQualification__r.ProgramQualification__r.Employment__c,
																												q.ProgramCategoryQualification__r.ProgramQualification__c, 
																												q.ProgramCategoryQualification__r.ProgramQualification__r.ProgramPeriod__c,
																												q.ProgramCategoryQualification__c, q.DocumentStatusEIDFormula__c, // QDR DOCUMENT STATUS
																												q.ProgramQualification__r.ProgramPeriod__c,
																												q.DocumentStatus__c   
																												From QualificationDocumentRequirement__c q
																												where ProgramQualification__r.Employment__c in :empIds 
																												or ProgramCategoryQualification__r.ProgramQualification__r.Employment__c in :empids]){
			//make map of employment + program period to one qdr for each employment
			/*map<String, QualificationDocumentRequirement__c> qdrMap = new map<String, QualificationDocumentRequirement__c>();
			QualificationDocumentRequirement__c qdrTest;
			string empS;
			string ppS;
			for(QualificationDocumentRequirement__c qdr : qdrList){
				//employeeId
				if(qdr.ProgramQualification__c != null && qdr.ProgramQualification__r.Employment__c!=null) empS = qdr.ProgramQualification__r.Employment__c;
				else if(qdr.ProgramCategoryQualification__c !=null && qdr.ProgramCategoryQualification__r.ProgramQualification__c!=null &&qdr.ProgramCategoryQualification__r.ProgramQualification__r.Employment__c != null) emps = qdr.ProgramCategoryQualification__r.ProgramQualification__r.Employment__c;
				else emps = null;
				//program period id
				if(qdr.ProgramQualification__c != null && qdr.ProgramQualification__r.ProgramPeriod__c!=null) ppS = qdr.ProgramQualification__r.ProgramPeriod__c;
				else if(qdr.ProgramCategoryQualification__c !=null && qdr.ProgramCategoryQualification__r.ProgramQualification__c!=null &&qdr.ProgramCategoryQualification__r.ProgramQualification__r.ProgramPeriod__c != null) pps = qdr.ProgramCategoryQualification__r.ProgramQualification__r.ProgramPeriod__c;
				else ppS = null;
				
				if(emps!=null && ppS != null){
					qdrTest = qdrMap.get(empS+ppS);
					if(qdrTest == null) qdrMap.put(empS+ppS, qdr);
				}
			}																												
			//get list of QDR to update
			set<String> qdrKeys = qdrMap.keySet();
			qdrList = new list<QualificationDocumentRequirement__c>();
			for(string key:qdrKeys){
				qdrList.add(qdrMap.get(key));
			}
			*/
			//make nonsenst Document status
			DocumentStatus__c ds = new DocumentStatus__c();
			ds.name = 'batch';
			ds.DocumentStatusEID__c =3.14444;
			ds.RankOrder__c = 1.0;
			insert ds;
			
			//make map of qdr ids to qdr.DocumentStatusEID__c value(for backup)
			//set doc status eid to nonsense value
			map<string, string> qdrEIDmap = new map<string, string>();
			for(QualificationDocumentRequirement__c qdr : qdrList){
				qdrEIDmap.put(qdr.id, qdr.DocumentStatus__c);
				qdr.DocumentStatus__c = ds.id;		
			}
			update qdrList;
			
			//set QDRS to original values
			for(QualificationDocumentRequirement__c qdr : qdrList){
				qdr.DocumentStatus__c = qdrEIDmap.get(qdr.id);		
			}
			update qdrList;
			
			//delete nonsense ds
			delete ds;
			if(test.isRunningTest()) break;
		}
	} 
	/***********************************************/
	global void finish(Database.BatchableContext BC){
		
	}
	/***********************************************/

}