objects/DocumentRequirement__c.object
<CustomObject>
    <fields>
        <fullName>DocumentRequirementAgencyCountSummary__c</fullName>
        <description>The number of agencies that have this document requirement. Zero signifies all agencies have the same requirement, meaning no agency is an exception.</description>
        <inlineHelpText>The number of agencies that have this document requirement. Zero signifies all agencies have the same requirement, meaning no agency is an exception.</inlineHelpText>
        <label>Agency Count Summary</label>
        <summaryForeignKey>DocumentRequirementAgency__c.DocumentRequirement__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProgramCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program category this documentation requirement fulfills</description>
        <inlineHelpText>The program category this documentation requirement fulfills</inlineHelpText>
        <label>Program Category</label>
        <referenceTo>ProgramCategory__c</referenceTo>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Requirement</label>
    <nameField>
        <label>Document Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DocumentRequirementAgency__c.object
<CustomObject>
    <description>Document requirements that are different by agency. If this table has no records for a particular document requirement, all agencies require the same document. If it does have records, only the agencies noted have the stated document requirement.</description>
    <fields>
        <fullName>AgencyEidFormula__c</fullName>
        <description>Agency EID</description>
        <formula>Agency__r.AgencyEID__c</formula>
        <inlineHelpText>Agency EID</inlineHelpText>
        <label>Agency Eid Formula</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DocumentRequirement__c</fullName>
        <description>The document requirement that this agency has.</description>
        <inlineHelpText>The document requirement that this agency has.</inlineHelpText>
        <label>Document Requirement</label>
        <referenceTo>DocumentRequirement__c</referenceTo>
        <relationshipLabel>Document Requirements by Agency</relationshipLabel>
        <relationshipName>DocumentRequirementsAgency</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Document Requirement by Agency</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Document Requirement Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requirements by Agency</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DocumentStep__c.object
<CustomObject>
    <fields>
        <fullName>DocumentRequirement__c</fullName>
        <description>The document requirement that applies to this document role step.</description>
        <inlineHelpText>The document requirement that applies to this document role step.</inlineHelpText>
        <label>Document Requirement</label>
        <referenceTo>DocumentRequirement__c</referenceTo>
        <relationshipLabel>Document Steps</relationshipLabel>
        <relationshipName>DocumentSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Document Step</label>
    <nameField>
        <label>Document Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategory__c.object
<CustomObject>
    <label>Program Category</label>
    <nameField>
        <label>Program Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategoryPeriod__c.object
<CustomObject>
    <fields>
        <fullName>ProgramCategory__c</fullName>
        <description>The program category linked to this area</description>
        <inlineHelpText>The program category linked to this area</inlineHelpText>
        <label>Program Category</label>
        <referenceTo>ProgramCategory__c</referenceTo>
        <relationshipName>ProgramCategoryAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Category Period</label>
    <nameField>
        <label>Program Category Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Category Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategoryQualification__c.object
<CustomObject>
    <fields>
        <fullName>PCQUpdateThroughBATCH__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PCQ Update Through BATCH</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PQAgencyEidFormula__c</fullName>
        <description>The agency connected with the program qualification.</description>
        <formula>ProgramQualification__r.ProgramPeriod__r.Agency__r.AgencyEID__c</formula>
        <inlineHelpText>The agency connected with the program qualification.</inlineHelpText>
        <label>PQAgencyEidFormula</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PQDocumentSourceEidGeneratedFormula__c</fullName>
        <description>Document Source from PQ</description>
        <formula>ProgramQualification__r.PQDocumentSourceEidGenerated__c</formula>
        <inlineHelpText>Document Source from PQ</inlineHelpText>
        <label>PQDocumentSourceEidGeneratedFormula</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramCategoryPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program category period associated with the program category qualification and program qualification</description>
        <inlineHelpText>The program category period associated with the program category qualification and program qualification</inlineHelpText>
        <label>Program Category Period</label>
        <referenceTo>ProgramCategoryPeriod__c</referenceTo>
        <relationshipLabel>Program Category Qualifications</relationshipLabel>
        <relationshipName>ProgramCategoryQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the qualified program for an employee</description>
        <inlineHelpText>Indicates the qualified program for an employee</inlineHelpText>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipLabel>Program Category Qualifications</relationshipLabel>
        <relationshipName>ProgramCategoryQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RankOrderofProgramcategory__c</fullName>
        <formula>ProgramCategoryPeriod__r.ProgramCategory__r.RankOrder__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rank Order of Program Category Formula</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program Category Qualification</label>
    <nameField>
        <label>Program Category Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Category Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QualificationDocumentRequirement__c.object
<CustomObject>
    <fields>
        <fullName>DocumentRequirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The document requirement used by this record.</description>
        <inlineHelpText>The document requirement used by this record.</inlineHelpText>
        <label>Document Requirement</label>
        <referenceTo>DocumentRequirement__c</referenceTo>
        <relationshipName>QualificationRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramCategoryQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program category qualification associated with this requirement status</description>
        <inlineHelpText>The program category qualification associated with this requirement status</inlineHelpText>
        <label>Program Category Qualification</label>
        <referenceTo>ProgramCategoryQualification__c</referenceTo>
        <relationshipName>QualificationRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipName>QualificationRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Qualification Document Requirement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Qualification Document Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Document Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QualificationDocumentStep__c.object
<CustomObject>
    <fields>
        <fullName>DocumentStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The document step used by this record.</description>
        <inlineHelpText>The document step used by this record.</inlineHelpText>
        <label>Document Step</label>
        <referenceTo>DocumentStep__c</referenceTo>
        <relationshipLabel>Qualification Document Steps</relationshipLabel>
        <relationshipName>QualificationRoleSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QualificationDocumentRequirement__c</fullName>
        <description>The document requirement associated with this document step for this employee</description>
        <inlineHelpText>The document requirement associated with this document step for this employee</inlineHelpText>
        <label>Qualification Document Requirement</label>
        <referenceTo>QualificationDocumentRequirement__c</referenceTo>
        <relationshipLabel>Qualification Document Steps</relationshipLabel>
        <relationshipName>QualificationFunctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Qualification Document Step</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Qualification Document Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Document Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateAsyncQualificationDocs.cls
/*This Batch is for ADDING New QDR's for the PCQ's when NEW DOCUMENT REQUIREMENTS are Inserted*/


global class CreateAsyncQualificationDocs implements DataBase.Batchable<Sobject>,Database.stateful {

          
         global List<ProgramCategoryQualification__c> pcqList  ;

global Database.QueryLocator start(Database.BatchableContext BC){

  return (Database.getQueryLocator([ select Id, Name,ProgramQualification__c,PQAgencyEidFormula__c,    
                    PQDocumentSourceEidGeneratedFormula__c,RankOrderofProgramcategory__c,
                    ProgramCategoryPeriod__r.ProgramCategory__c, ProgramCategoryPeriod__c from ProgramCategoryQualification__c where   
                    PCQUpdateThroughBATCH__c = true order by ProgramQualification__c])
                    );

}

global void execute(Database.BatchableContext info, List<sObject> pcqList1){
    
        List<string> programCategoryIdList = new List<string>();
        Map<Id,List<ProgramCategoryQualification__c>> pcqMap = new Map<Id,List<ProgramCategoryQualification__c>>();
        List<QualificationDocumentStep__c> qualRoleStep = new List<QualificationDocumentStep__c>();
        QualificationDocumentRequirement__c qr;
        QualificationDocumentStep__c qrs;
        List<QualificationDocumentRequirement__c> qualificationDocReqList = new List<QualificationDocumentRequirement__c>();
        List<QualificationDocumentStep__c> qualificationDocStepList = new List<QualificationDocumentStep__c>();
        Map<String,Integer> docReqAgencyMap = new Map<String,Integer>();
        Set<Id> docAgency = new Set<Id>();
        //List<string> programCategoryIdList = new List<string>();
        Set<Decimal> pcqAgencyIds = new Set<Decimal>();
        Map<string, List<DocumentRequirement__c>> documentRequirementMap = new Map<string, List<DocumentRequirement__c>>();
        List<DocumentRequirement__c> docReqsList;
        
        List<ProgramCategoryQualification__c> pcqsList ;
        pcqList = (List<ProgramCategoryQualification__c>) pcqList1;
       /**
       		Thr folllowing for deleting the existiing QDRs
       */
       List<QualificationDocumentRequirement__c> qdrToDelete =  [select id from QualificationDocumentRequirement__c where ProgramCategoryQualification__c in :pcqList ];
       if(qdrToDelete != null && qdrToDelete.size() > 0)
       		delete qdrToDelete;
       		//End Qdr Delete
       		  		
       		
       		
       		
       		 //The following loop populating PCQ's by PQ
        for(ProgramCategoryQualification__c pcq : pcqList){
            if(pcqMap.containsKey(pcq.ProgramQualification__c))
                pcqMap.get(pcq.ProgramQualification__c).add(pcq);
            else {
                pcqsList = new   List<ProgramCategoryQualification__c>();
                pcqsList.add(pcq);
                pcqMap.put(pcq.ProgramQualification__c,pcqsList);
            }
            programCategoryIdList.add(pcq.ProgramCategoryPeriod__r.ProgramCategory__c);
            pcqAgencyIds.add(pcq.PQAgencyEidFormula__c);
        }
        System.debug('pcqAgencyIds:'+pcqAgencyIds);
        
        //The following loop populating Document Req's by PC
        for(DocumentRequirement__c docReq : [select Id, Name,DocumentRequirementAgencyCountSummary__c, ProgramCategory__c, (Select Id, Name, DocumentRequirement__c From DocumentSteps__r) From DocumentRequirement__c
                                            where ProgramCategory__c =:programCategoryIdList]){
            if(documentRequirementMap.containsKey(docReq.ProgramCategory__c)&& documentRequirementMap.get(docReq.ProgramCategory__c) != null){
                documentRequirementMap.get(docReq.ProgramCategory__c).add(docReq);
                } else{
                    docReqsList = new List<DocumentRequirement__c>();
                    docReqsList.add(docReq);
                    documentRequirementMap.put(docReq.ProgramCategory__c, docReqsList);
                }
         // Logic of Inserting QDR's through AGENCY!
                if(docReq.DocumentRequirementAgencyCountSummary__c > 0)
                    docAgency.add(docReq.id);
            }
            System.debug('docAgency:'+docAgency);
           for(AggregateResult aggr : [select count(id) agencyCount,DocumentRequirement__c docReqId from  
                                        DocumentRequirementAgency__c where DocumentRequirement__c in :docAgency and 
                                        AgencyEidFormula__c in : pcqAgencyIds group by DocumentRequirement__c]) {
                docReqAgencyMap.put(String.valueOf(aggr.get('docReqId')),Integer.valueOf(aggr.get('agencyCount')));                                                 
                                                
          }
          System.debug('docReqAgencyMap:'+docReqAgencyMap);
          Map<Id,Set<Decimal>> agencyFormulas = new Map<Id,Set<Decimal>>();
          Set<Decimal> docAgencySet;
          for(DocumentRequirementAgency__c agency : [select AgencyEidFormula__c,DocumentRequirement__c from   
                                                    DocumentRequirementAgency__c where DocumentRequirement__c in 
                                                    :docReqAgencyMap.keySet()]){
                          if(agencyFormulas.containsKey(agency.DocumentRequirement__c)&&  agencyFormulas.get(agency.DocumentRequirement__c) != null){
                              agencyFormulas.get(agency.DocumentRequirement__c).add(agency.AgencyEidFormula__c);
                          }else {
                               docAgencySet = new Set<Decimal>();
                               docAgencySet.add(agency.AgencyEidFormula__c);
                               agencyFormulas.put(agency.DocumentRequirement__c,docAgencySet);
                          }                            
                      }
        
        for(ProgramCategoryQualification__c pcq : pcqList)
        {
            System.debug('pcq:'+pcq.id);
          List<DocumentRequirement__c> documentReqList = documentRequirementMap.get(pcq.ProgramCategoryPeriod__r.ProgramCategory__c);                    
               
               System.debug('documentReqList:'+documentReqList);         
            if(documentReqList != null && documentReqList.size() > 0) {
                pcqMap.remove(pcq.ProgramQualification__c);
                
            for(DocumentRequirement__c  dr : documentReqList){
                System.debug('dr id :'+dr.id);
                System.debug('agencyFormulas.get(dr.id):'+agencyFormulas.get(dr.id));
                if(dr.DocumentRequirementAgencyCountSummary__c == 0 || (agencyFormulas.containsKey(dr.id) && dr.DocumentRequirementAgencyCountSummary__c > 0 && agencyFormulas.get(dr.id).contains(pcq.PQAgencyEidFormula__c)) ){
                    QualificationDocumentRequirement__c qdr = new QualificationDocumentRequirement__c();
                    qdr.ProgramCategoryQualification__c = pcq.Id;
                    qdr.DocumentRequirement__c = dr.Id;
                    
                    qualificationDocReqList.add(qdr);     
                }
             }
       
            }                                
        }
    if(qualificationDocReqList != null && qualificationDocReqList.size()>0){
        QualificationDocReqHelper.qdrInsertFromPCQ = true ;     
        QualificationDocReqHelper.PQDocumentSourceEid = false ;      
        insert qualificationDocReqList;
    }
/************************************************/        
        Map<string, List<QualificationDocumentRequirement__c>> qdrMap = new Map<string, List<QualificationDocumentRequirement__c>>();
        List<QualificationDocumentRequirement__c> qdrs ;
        List<id> qdrIdList = new List<id>();
        for(QualificationDocumentRequirement__c qdr : qualificationDocReqList){
        
            if( qdrMap.get(qdr.ProgramCategoryQualification__c) != null)
                qdrMap.get(qdr.ProgramCategoryQualification__c).add(qdr);
                
            else {
                    qdrs = new  List<QualificationDocumentRequirement__c>();
                    qdrs.add(qdr);
                    qdrMap.put(qdr.ProgramCategoryQualification__c,  qdrs);
                }
            qdrIdList.add(qdr.DocumentRequirement__c);
            
        }
        System.debug('qdrMap:'+qdrMap);
        
        Map<string, List<DocumentStep__c>> documentStepMap = new Map<string, List<DocumentStep__c>>();
        List<DocumentStep__c> docStepList;
        
        for(DocumentStep__c docStep : [Select Id, Name, DocumentRequirement__c From DocumentStep__c where DocumentRequirement__c in :qdrIdList]){
            if(documentStepMap.containsKey(docStep.DocumentRequirement__c)&& documentStepMap.get(docStep.DocumentRequirement__c) != null){
                documentStepMap.get(docStep.DocumentRequirement__c).add(docStep);
            } else{
                docStepList = new List<DocumentStep__c>();
                docStepList.add(docStep);
                documentStepMap.put(docStep.DocumentRequirement__c, docStepList);
            }
        }  
        
        for(ProgramCategoryQualification__c pcq : pcqList){
                        
        List<QualificationDocumentRequirement__c> qdrList = qdrMap.get(pcq.id);   
        System.debug('documentReqList:'+qdrList);              
        if(qdrList != null && qdrList.size() > 0) {            
            
            for(QualificationDocumentRequirement__c  qdr : qdrList){
                    
                    List<DocumentStep__c> qdsList = documentStepMap.get(qdr.DocumentRequirement__c);
                        if(qdsList != null && qdsList.size() > 0){
                            System.debug('DocumentStep List :'+qdsList);
                            for(DocumentStep__c  drStep : qdsList){
                                QualificationDocumentStep__c qds = new QualificationDocumentStep__c();
                                qds.QualificationDocumentRequirement__c = qdr.Id;                   
                                qds.DocumentStep__c = drStep.Id;
                                //qdrMap.remove(dr.Id);   
                                qualificationDocStepList.add(qds);
                            }
                            System.debug('qualificationDocStepList:'+qualificationDocStepList);
                        } 
                    }  
                }                                
            }
        
    insert qualificationDocStepList;
      
    QualificationDocReqHelper.updateReadinessOnNoQDRs(pcqMap);
         
}

/************************************************/
    global void finish(Database.BatchableContext BC){
            
                for(ProgramCategoryQualification__c pcq : pcqList)  {
                          pcq.PCQUpdateThroughBATCH__c = false ;
            
        }
        Database.update(pcqList,false);
        
}   
  
}