objects/DocumentRequirement__c.object
<CustomObject>
    <fields>
        <fullName>ProgramCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program category this documentation requirement fulfills</description>
        <inlineHelpText>The program category this documentation requirement fulfills</inlineHelpText>
        <label>Program Category</label>
        <referenceTo>ProgramCategory__c</referenceTo>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Document Requirements</relationshipLabel>
        <relationshipName>DocumentRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Requirement</label>
    <nameField>
        <label>Document Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The client account that this employee (whether or not actually employed) belongs to.</description>
        <inlineHelpText>The client account that this employee (whether or not actually employed) belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>AccountEmployees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <description>The Entity associated with this Employment Period</description>
        <inlineHelpText>The Entity associated with this Employment Period</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account, or client, that this entity belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>AccountEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategory__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program associated with this category</description>
        <inlineHelpText>The program associated with this category</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Categories</relationshipLabel>
        <relationshipName>ProgramCategories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Category</label>
    <nameField>
        <label>Program Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategoryPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <description>The area linked to this program category</description>
        <inlineHelpText>The area linked to this program category</inlineHelpText>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipName>ProgramCategoryAreas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProgramCategory__c</fullName>
        <description>The program category linked to this area</description>
        <inlineHelpText>The program category linked to this area</inlineHelpText>
        <label>Program Category</label>
        <referenceTo>ProgramCategory__c</referenceTo>
        <relationshipName>ProgramCategoryAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Category Period</label>
    <nameField>
        <label>Program Category Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Category Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategoryQualification__c.object
<CustomObject>
    <fields>
        <fullName>ProcessStage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The process stage of this program category qualification.</description>
        <inlineHelpText>The process stage of this program category qualification.</inlineHelpText>
        <label>Process Stage</label>
        <referenceTo>QualificationProcessStage__c</referenceTo>
        <relationshipLabel>Program Category Qualifications</relationshipLabel>
        <relationshipName>ProgramCategoryQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramCategoryPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program category period associated with the program category qualification and program qualification</description>
        <inlineHelpText>The program category period associated with the program category qualification and program qualification</inlineHelpText>
        <label>Program Category Period</label>
        <referenceTo>ProgramCategoryPeriod__c</referenceTo>
        <relationshipLabel>Program Category Qualifications</relationshipLabel>
        <relationshipName>ProgramCategoryQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the qualified program for an employee</description>
        <inlineHelpText>Indicates the qualified program for an employee</inlineHelpText>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipLabel>Program Category Qualifications</relationshipLabel>
        <relationshipName>ProgramCategoryQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Category Qualification</label>
    <nameField>
        <label>Program Category Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Category Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The agency associated with the program zone and area</description>
        <inlineHelpText>The agency associated with the program zone and area</inlineHelpText>
        <label>Agency</label>
        <referenceTo>Agency__c</referenceTo>
        <relationshipName>ProgramAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The area associated with the program zone and agency</description>
        <inlineHelpText>The area associated with the program zone and agency</inlineHelpText>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipName>ProgramAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Periods</relationshipLabel>
        <relationshipName>ProgramPeriods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <label>Program Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period that this program qualification is under.</description>
        <inlineHelpText>The employment period that this program qualification is under.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProcessStage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Tracks the workflow from qualification to certification.</description>
        <inlineHelpText>Tracks the workflow from qualification to certification.</inlineHelpText>
        <label>Process Stage</label>
        <referenceTo>QualificationProcessStage__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramPeriod__c</fullName>
        <description>The program period that the employee qualifies under</description>
        <inlineHelpText>The program period that the employee qualifies under</inlineHelpText>
        <label>Program Period</label>
        <referenceTo>ProgramPeriod__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateAsyncQualificationDocs_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class CreateAsyncQualificationDocs_Test {
	
public static Account a;
 public static Entity__c Entity;
 public static Employee__c employee;
 public static Employment__c employment;
 public static Area__c area, area1;
 public static List<Area__c> areaList;
 public static Agency__c Agency;
 public static Program__c program;
 public static ProgramCategory__c pc, pc1, pc2, pc3; 
 public static List<ProgramCategory__c> programCategoryList;
 public static ProgramCategoryPeriod__c pcp, pcp1, pcp2, pcp3;
 public static List<ProgramCategoryPeriod__c> programCategoryPeriodList;
 public static ProgramQualification__c programQualification;
 public static ProgramPeriod__c programPeriod;
 public static QualificationProcessStage__c qualificationProcessStage;
 public static List<ProgramQualification__c> programQualificationList;
 public static QualificationReadiness__c qr, qr1;
 /*****************************************************************/   
 
 static {
    
    	/*loginUser = [select id from user where id='00530000004rW4R'];*/
        a = new Account(Name='Test Account');
        insert a;
        
        Entity  = new Entity__c(Account__c = a.Id, Name = 'TestEntity');
        insert Entity;
        
        employee = new Employee__c(FirstName__c ='Emp1',Account__c = a.Id, LastName__c ='Lname',MiddleName__c = 'MName', SSN__c = '343532523');
        insert employee;
        
        employment = new Employment__c(Employee__c = employee.Id, Entity__c = Entity.Id, Status__c = 'Hired',StartDate__c = System.today().addDays(-60));
        insert employment;
        
        // Area List
        area = new Area__c(Name='United States (50 states and DC)', AreaDescriptionText__c ='Test Area');
        area1 = new Area__c(Name='United States (50 states and DC)', AreaDescriptionText__c ='Test Area');
        areaList = new Area__c[] {area1,area};
        insert areaList ;  
        
        Agency = new Agency__c(Name='Test Agency');
        insert Agency;
        
        //Program
        program = new Program__c(Name='Test Program');
        insert program;
        
        // Program Category List      
        pc = new ProgramCategory__c(Program__c = program.Id, Name = 'Test program Category', RankOrder__c = 60);
        pc1 = new ProgramCategory__c(Program__c = program.Id, Name = 'Test  Category', RankOrder__c = 80);
        pc2 = new ProgramCategory__c(Program__c = program.Id, Name = 'Test  Category', RankOrder__c = 100); // Has 2 Document Requirements.
        pc3 = new ProgramCategory__c(Program__c = program.Id, Name = 'Testing program Category', RankOrder__c = 70);
        programCategoryList = new ProgramCategory__c []{pc , pc1, pc2, pc3}; 
        insert programCategoryList ; 
        
        // Program Category Period List   
        pcp = new ProgramCategoryPeriod__c(Name = 'TestProgramCategoryPeriod', ProgramCategory__c = programCategoryList[0].Id, Area__c = areaList[0].Id, StartDate__c = System.today().addDays(-90));
  		pcp1 = new ProgramCategoryPeriod__c(Name = 'TestProgramCategoryPeriod', ProgramCategory__c = programCategoryList[1].Id, Area__c = areaList[1].Id, StartDate__c = System.today().addDays(-70));
        pcp2 = new ProgramCategoryPeriod__c(Name = 'TestProgramCategoryPeriod', ProgramCategory__c = programCategoryList[2].Id, Area__c = areaList[1].Id, StartDate__c = System.today().addDays(-50)); // Can be used in PCQ!
        pcp3 = new ProgramCategoryPeriod__c(Name = 'TestProgramCategoryPeriod', ProgramCategory__c = programCategoryList[3].Id, Area__c = areaList[1].Id, StartDate__c = System.today().addDays(-80));
        programCategoryPeriodList = new ProgramCategoryPeriod__c[]{pcp, pcp1, pcp2, pcp3};
        insert programCategoryPeriodList; // Program Category Period List
        
        // Document Requirements
        
        DocumentRequirement__c drq = new DocumentRequirement__c(Name = 'Address Verification', Program__c = program.Id );
		DocumentRequirement__c drq1 = new DocumentRequirement__c(Name = 'Address Verification', ProgramCategory__c = programCategoryList[1].Id );
		DocumentRequirement__c drq2 = new DocumentRequirement__c(Name = 'Address Verification', ProgramCategory__c = programCategoryList[2].Id );
		DocumentRequirement__c drq3 = new DocumentRequirement__c(Name = 'Address Verification', ProgramCategory__c = programCategoryList[2].Id );
	   	List<DocumentRequirement__c> docsList = new List<DocumentRequirement__c>{drq,drq1,drq2,drq3};
	    insert docsList;
	    
        // Program Period 
        programPeriod = new ProgramPeriod__c(Name='Test Program period',Program__c=program.Id,  Area__c=areaList[0].Id, Agency__c = Agency.Id,StartDate__c=System.today().addDays(-200));
        insert programPeriod;
        
        // Qualification Process Stage
        
        qualificationProcessStage = new QualificationProcessStage__c (Name = 'Ready to Prepare Application' , RankOrder__c = 90 );
        insert qualificationProcessStage;  
        
        // Program Qualification List
        programQualification = new ProgramQualification__c(Name = 'Test Program Qualification', ProgramPeriod__c = programPeriod.Id, Employment__c = employment.Id, ProcessStage__c = qualificationProcessStage.Id );
        programQualificationList = new List<ProgramQualification__c>{programQualification};
        insert programQualificationList;
        
        // Qualification Readiness 
        qr = new QualificationReadiness__c(Name = 'Available', RankOrder__c = 1, QualificationReadinessEID__c = 9);
        insert qr;
        qr1 = new QualificationReadiness__c(Name = 'Disqualified Automatically', RankOrder__c = 2,QualificationReadinessEID__c = 8);
        insert qr1;
 } 
 
 /**********************************************/         
       static testMethod void myUnitTest1() {
       	test.starttest(); 
       	ProgramCategoryQualification__c pcq1 = new ProgramCategoryQualification__c(ProgramCategoryPeriod__c = programCategoryPeriodList[2].Id, 
        										ProgramQualification__c = programQualification.Id, PCQUpdateThroughBATCH__c = true);
        
        List<ProgramCategoryQualification__c> pcqList = new List<ProgramCategoryQualification__c>{pcq1};
        insert pcqList ; 
      	BATCH_QDRHelper.invokeBatch();
        test.stopTest();
          
        pcqList = [select ProcessStageEIDformula__c, ReadinessEid__c from ProgramCategoryQualification__c where id in :pcqList ];
        system.assertEquals(2.0,pcqList[0].ReadinessEid__c);
        system.assertEquals(26,pcqList[0].ProcessStageEIDformula__c);
        System.assertEquals(false ,[select PCQUpdateThroughBATCH__c from ProgramCategoryQualification__c where id in :pcqList  ].PCQUpdateThroughBATCH__c);
   	}
 
}