objects/DocumentStatus__c.object
<CustomObject>
    <description>The document score and status for all levels of the document management process.</description>
    <fields>
        <fullName>DocumentStatusEID__c</fullName>
        <description>The Enterprise ID for this document status.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this document status.</inlineHelpText>
        <label>Document Status EID</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Document Status</label>
    <nameField>
        <label>Document Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Documenttype__c.object
<CustomObject>
    <fields>
        <fullName>DocumentTypeEID__c</fullName>
        <description>The Enterprise ID for this Document Type.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this Document Type.</inlineHelpText>
        <label>Document Type EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Document Type</label>
    <nameField>
        <label>Document Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>AccountEIDFormula__c</fullName>
        <description>This is used to power the screen employee from employment record button.</description>
        <formula>Employee__r.Account__r.AccountEID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is used to power the screen employee from employment record button.</inlineHelpText>
        <label>Account EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReferenceID__c</fullName>
        <description>The reference number used to connect survey respondents and their documents with this system&apos;s employment periods.</description>
        <displayFormat>{0}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>The reference number used to connect survey respondents and their documents with this system&apos;s employment periods.</inlineHelpText>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RepositoryDocument__c.object
<CustomObject>
    <fields>
        <fullName>DocumentStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the validity of the document.</description>
        <inlineHelpText>Identifies the validity of the document.</inlineHelpText>
        <label>Document Status</label>
        <referenceTo>DocumentStatus__c</referenceTo>
        <relationshipLabel>Repository Documents</relationshipLabel>
        <relationshipName>RepositoryDocuments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This documents type</description>
        <inlineHelpText>This documents type</inlineHelpText>
        <label>Document Type</label>
        <referenceTo>Documenttype__c</referenceTo>
        <relationshipLabel>Repository Documents</relationshipLabel>
        <relationshipName>RepositoryDocuments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period to which this document belongs. If it is an employee document, it must be related to an employment period. If it applies across multiple hire dates, multiple records should be entered (this should happen only about 5% of the time).</description>
        <inlineHelpText>The employment period to which this document belongs. If it is an employee document, it must be related to an employment period. If it applies across multiple hire dates, multiple records should be entered (this should happen only about 5% of the time).</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Repository Documents</relationshipLabel>
        <relationshipName>RepositoryDocuments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScannedDate__c</fullName>
        <description>The date and time we scanned the document into the repository.</description>
        <inlineHelpText>The date and time we scanned the document into the repository.</inlineHelpText>
        <label>Scanned Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>wktDocument8850__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The automatically generated IRS Form 8850.</description>
        <inlineHelpText>The automatically generated IRS Form 8850.</inlineHelpText>
        <label>IRS Form 8850</label>
        <referenceTo>wktDocument8850__c</referenceTo>
        <relationshipLabel>Repository Documents</relationshipLabel>
        <relationshipName>RepositoryDocuments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Repository Document</label>
    <nameField>
        <label>Repository Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repository Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/wktDocument8850__c.object
<CustomObject>
    <description>Work table for generation of 8850&apos;s</description>
    <fields>
        <fullName>ElectronicSignatureText__c</fullName>
        <description>The electronic signature text</description>
        <inlineHelpText>The electronic signature text</inlineHelpText>
        <label>Electronic Signature Text</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>wktDocument8850</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IRS Form 8850</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>IRS Form 8850 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IRS Forms 8850</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FutureMethod8850.cls
public class FutureMethod8850{
	
	@future
	public static void CreateRepository(Set<Id> docIds){
	
	System.debug('DocIds :'+docIds);
		
		list<RepositoryDocument__c> rdList = new list<RepositoryDocument__c>();
		DocumentStatus__c PendingEv = [Select id, DocumentStatusEID__c From DocumentStatus__c where DocumentStatusEID__c = 0.0 ];
		Documenttype__c Form8850 = [Select Id, DocumentTypeEID__c From Documenttype__c where DocumentTypeEID__c = 241.0];
		
		for(wktDocument8850__c rec : [Select Id,Employment__r.AccountEIDFormula__c, Employment__r.ReferenceID__c, Employment__r.Id, Employment__c, ElectronicSignatureText__c 
		    								From wktDocument8850__c where id in :docIds ]){
		
		if(rec.Employment__c != null && rec.ElectronicSignatureText__c != null){    	
		RepositoryDocument__c rd = new RepositoryDocument__c(Name =  rec.Employment__r.AccountEIDFormula__c+'_'+'WOTC Form 8850'+'_'+ rec.Employment__r.ReferenceID__c , Employment__c = Rec.Employment__c , 
		                                    wktDocument8850__c = rec.id, DocumentStatus__c = PendingEv.id, ScannedDate__c = System.now(),
		                                    Documenttype__c = Form8850.Id);
		        
		        rdList.add(rd);
		        
		    }
		System.debug('rdList:'+rdList);   
		If(rdList.size() > 0 && rdList != null){
		
		insert rdList;
		}    
		}
	// EmploymentReferenceNumber_Form8850_AccountEID.
			
	}

}