objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EmployeeSurveyAnswer__c.object
<CustomObject>
    <description>Survey answers as chosen by survey taker.  Includes a field for user input text in case it is  allowed.</description>
    <fields>
        <fullName>EmployeeSurveyAnswerAmount__c</fullName>
        <description>Survey answer in numeric form.</description>
        <inlineHelpText>Survey answer in numeric form.</inlineHelpText>
        <label>Numeric Answer</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EmployeeSurveyAnswerDate__c</fullName>
        <description>Survey answer in date form.</description>
        <inlineHelpText>Survey answer in date form.</inlineHelpText>
        <label>Date Answer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmployeeSurveyAnswerText__c</fullName>
        <description>Survey answer in text form.</description>
        <inlineHelpText>Survey answer in text form.</inlineHelpText>
        <label>Text Answer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EmployeeSurvey__c</fullName>
        <label>Employee Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Employee Survey Answers</relationshipLabel>
        <relationshipName>EmployeeSurveyAnswers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <label>Survey Question</label>
        <referenceTo>SurveyQuestion__c</referenceTo>
        <relationshipName>Survey_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee Survey Answer</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Employee Survey Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SurveyQuestion__c.object
<CustomObject>
    <fields>
        <fullName>QuestionEID__c</fullName>
        <externalId>true</externalId>
        <label>Question EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SaveEmployeeSurveyAnswer.cls
global class SaveEmployeeSurveyAnswer implements Process.Plugin{
     
    global Process.PluginResult invoke(Process.PluginRequest request){
        String employeeSurveyId = (String)request.inputParameters.get('EmployeeSurveyId');  
        Decimal surveyQuestionEid = Decimal.valueOf((String)request.inputParameters.get('SurveyQuestionEID'));  
        String textAnswer = (String)request.inputParameters.get('TextAnswer');
        Datetime datetimeAnswer = (Datetime)request.inputParameters.get('DateAnswer');                   
        Decimal numericAnswer = (Decimal)request.inputParameters.get('NumericAnswer');
        Boolean isBlankAnswer = false;          
        Date dateAnswer;
        
        
       
        
        if(datetimeAnswer != null)
        {
            dateAnswer = Date.valueOf(datetimeAnswer);
        }
        
        Map<String, Object> result = new Map<String, Object>();
                  
        if(textAnswer == null && dateAnswer == null && numericAnswer == null)
        {
            isBlankAnswer = true;
        } 
        else if(textAnswer != null && textAnswer.trim() == '' && dateAnswer == null && numericAnswer == null)
        {
            isBlankAnswer = true;
        }  

                      
        SurveyQuestion__c surveyQuestion = [select Id from SurveyQuestion__c where QuestionEID__c =:surveyQuestionEid];
                               
        if(!isBlankAnswer)      
        {
            List<EmployeeSurveyAnswer__c> existingAnswer = [select Id, EmployeeSurveyAnswerDate__c, EmployeeSurveyAnswerAmount__c, EmployeeSurveyAnswerText__c from EmployeeSurveyAnswer__c where EmployeeSurvey__c=:employeeSurveyId and SurveyQuestion__c =:surveyQuestion.Id];
            
            if(existingAnswer == null || existingAnswer.size() == 0)
            {
            
                EmployeeSurveyAnswer__c empSurvey = new EmployeeSurveyAnswer__c(EmployeeSurvey__c = employeeSurveyId, SurveyQuestion__c = surveyQuestion.Id, EmployeeSurveyAnswerDate__c = dateAnswer, EmployeeSurveyAnswerAmount__c = numericAnswer, EmployeeSurveyAnswerText__c = textAnswer);       
            
                insert empSurvey;
            }
            else
            {
                for(EmployeeSurveyAnswer__c esa: existingAnswer)
                {
                    esa.EmployeeSurveyAnswerDate__c = dateAnswer;
                    esa.EmployeeSurveyAnswerAmount__c = numericAnswer;
                    esa.EmployeeSurveyAnswerText__c = textAnswer;
                }                    
                
                update existingAnswer;
            }
            
            result.put('Result','Success');
        }                      
        else
        {
            result.put('Result', 'Success');
        }
        
        return new Process.PluginResult(result);  
    }
    
    global Process.PluginDescribeResult describe(){
        
        Process.PluginDescribeResult  result = new Process.PluginDescribeResult();
        
        result.inputParameters = new List<Process.PluginDescribeResult.InputParameter>{
            new Process.PluginDescribeResult.InputParameter('EmployeeSurveyId', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('SurveyQuestionEID', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('TextAnswer', Process.PluginDescribeResult.ParameterType.STRING, false),
            new Process.PluginDescribeResult.InputParameter('DateAnswer ', Process.PluginDescribeResult.ParameterType.DATETIME, false),
            new Process.PluginDescribeResult.InputParameter('BooleanAnswer ', Process.PluginDescribeResult.ParameterType.BOOLEAN, false),
            new Process.PluginDescribeResult.InputParameter('NumericAnswer', Process.PluginDescribeResult.ParameterType.DECIMAL, false)
        };
        
        result.outputParameters = new List<Process.PluginDescribeResult.OutputParameter>{
            new Process.PluginDescribeResult.OutputParameter('Result', Process.PluginDescribeResult.ParameterType.STRING)
        };
        
        return result;
            
    }
}