objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <description>The Entity associated with this Employment Period</description>
        <inlineHelpText>The Entity associated with this Employment Period</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EntityStructure__c.object
<CustomObject>
    <fields>
        <fullName>EntityName__c</fullName>
        <inlineHelpText>The entity whose structure is being defined.</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Structure History</relationshipLabel>
        <relationshipName>EntityStructures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity Structure</label>
    <nameField>
        <label>Entity Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Structures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/wktDocument8850__c.object
<CustomObject>
    <description>Work table for generation of 8850&apos;s</description>
    <fields>
        <fullName>CongaWorkflowTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate IRS 8850</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>wktDocument8850</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EntityStructure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity Structure</label>
        <referenceTo>EntityStructure__c</referenceTo>
        <relationshipLabel>IRS Forms 8850</relationshipLabel>
        <relationshipName>IRSForms8850</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IRS Form 8850</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>IRS Form 8850 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IRS Forms 8850</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BATCH_wktDocument8850_entity.cls
global class BATCH_wktDocument8850_entity implements Database.Batchable<sObject>{
	
	public String query{get; set;}
	
	global void setDefaultQuery(){
		//query = 'Select w.EntityStructure__c, w.Employment__r.Entity__c, w.Employment__c From wktDocument8850__c w where EntityStructure__c = null';
		//if (test.isRunningTest()) query = 'Select w.EntityStructure__c, w.Employment__r.Entity__c, w.Employment__c From wktDocument8850__c w where EntityStructure__c = null limit 100';
		
		query = 'Select w.Id, w.CongaWorkflowTrigger__c,(Select Id From Attachments)  from wktDocument8850__c w limit 10000';
		if (test.isRunningTest()) query = 'Select w.Id, w.CongaWorkflowTrigger__c,(Select Id From Attachments) from wktDocument8850__c w limit 100';
		
	}
	    
	global database.querylocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(query);
	}
	    
	global void execute(Database.BatchableContext BC, List<sObject> scope)
	{
	  	list <String> entIds = new list<string>();
	  	list<wktDocument8850__c> wktl = new list<wktDocument8850__c>();
	  	list<Attachment> attl = new list<Attachment>();
	  	
	  	//get all entIds and make list of wkts
	  	for(wktDocument8850__c wkt : (list<wktDocument8850__c>)scope){
	  		wktl.add(wkt);
	  		
	  		if(wkt.Attachments.size() > 0)
	  		{
	  			for(Attachment a : wkt.Attachments)
	  			{
	  				attl.add(a);
	  			}
	  		}
	  		
	  		//entIds.add(wkt.Employment__r.Entity__c);
	  	}
	  	//get list of all EntityStructure__c
	  	//list<EntityStructure__c> esList =[Select e.EntityName__c, e.CreatedDate From EntityStructure__c e order by CreatedDate ASC];
	  	
	  	//set EntityStructure__c on wktDocument8850__c
	  	
	  	delete attl;
	  	
	  	for(wktDocument8850__c wkt : wktl)
	  	{
	  		
	  		/*
	  		for(EntityStructure__c es : esList){
	  			if(es.EntityName__c == wkt.Employment__r.Entity__c && wkt.EntityStructure__c == null){
	  				wkt.EntityStructure__c = es.id;
	  				break;
	  			}
	  		}
	  		*/
	  		
	  		wkt.CongaWorkflowTrigger__c = true;
	  	}
	  	
	  	update wktl;
	}
	 
  global void finish(Database.BatchableContext BC){
	         
  }

	global static void runBatch(){
		BATCH_wktDocument8850_entity b = new BATCH_wktDocument8850_entity();
		b.setDefaultQuery();
		Database.executeBatch(b);
	}	
	
	static testMethod void TEST_BATCH_wktDocument8850_entity() {
		test.startTest();
		BATCH_wktDocument8850_entity.runBatch();		
		test.stopTest();
  }    	

}