objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The client account that this employee (whether or not actually employed) belongs to.</description>
        <inlineHelpText>The client account that this employee (whether or not actually employed) belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>AccountEmployees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>The employee&apos;s federal social security number.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee&apos;s federal social security number.</inlineHelpText>
        <label>SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EmployeeAddress__c.object
<CustomObject>
    <description>A history of addresses for each employee.</description>
    <fields>
        <fullName>CityName__c</fullName>
        <description>City name</description>
        <inlineHelpText>City name</inlineHelpText>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The employee associated with this address</description>
        <inlineHelpText>The employee associated with this address</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Addresses</relationshipLabel>
        <relationshipName>EmployeeAddresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <description>The employee&apos;s full street address including suite, apartment, etc.</description>
        <inlineHelpText>The employee&apos;s full street address including suite, apartment, etc.</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>Zip Code</description>
        <inlineHelpText>Zip Code</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Employee Address</label>
    <nameField>
        <label>Employee Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PreventDuplicateEmployeeAddress_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PreventDuplicateEmployeeAddress_TEST {


  private static Account AccEmp;
  private static Employee__c Emp;
  private static EmployeeAddress__c Empadd;

       Static{    
       AccEmp = new Account(Name ='TestAccount1',Type='Press',Website='www.taxcreditco.com',BillingState ='GA',BillingPostalCode='30040',BillingStreet='Colchester Creek',BillingCity='PeachTree',BillingCountry='United States');
       insert AccEmp;
       
       Emp= new Employee__c(FirstName__c='Steve',LastName__c='Jobs',SSN__c='999-64-1098',Account__c=AccEmp.Id);
       insert Emp;
         
       Empadd = new EmployeeAddress__c(StreetAddressText__c='2490 Mariner Square Loop',CityName__c='SanJose',ZipCode__c='98712',Employee__c=Emp.Id);
       insert Empadd;   
     
       }
        
       static testmethod void PreventEmployeeAddressDup(){                    
           EmployeeAddress__c EmpAddress=new EmployeeAddress__c();
           EmpAddress.Employee__c=Emp.Id;
           EmpAddress.CityName__c='Los Vegas';
           EmpAddress.StreetAddressText__c='South Burnside';
           EmpAddress.ZipCode__c='98123';
        
       insert EmpAddress;
       update EmpAddress;
      
     }   

}