objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The official start date of the Employee associated with this Employment Period</description>
        <inlineHelpText>The official start date of the Employee associated with this Employment Period</inlineHelpText>
        <label>Hire Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BATCH_RunUpdateOnEmployment.cls
global class BATCH_RunUpdateOnEmployment implements Database.Batchable<sObject>{

    global static void runBatch(){
      BATCH_RunUpdateOnEmployment b = new BATCH_RunUpdateOnEmployment ();
      b.setDefaultQuery();
      Database.executeBatch(b);
    }


    public String query{get; set;}
      
      global void setDefaultQuery(){
          this.query = 'Select StartDate__c From Employment__c';
          if(test.isRunningTest()) this.query = 'Select StartDate__c From Employment__c limit 50';
      }
      
      
      global database.querylocator start(Database.BatchableContext BC){
              return Database.getQueryLocator(query);
      }
      
      global void execute(Database.BatchableContext BC, List<sObject> scope){
          List<Employment__c> obs = new List<Employment__c>();
            date sd;
          
          for(Employment__c s :(list<Employment__c>)scope){
              sd = s.StartDate__c ;
              s.StartDate__c = sd;
              obs.add(s);
          }
 
          update obs;
    }
   
      global void finish(Database.BatchableContext BC){
           
      }

    
    static testMethod void TEST_BATCH_RunUpdateOnEmployment() {
    		test.startTest();
        BATCH_RunUpdateOnEmployment.runBatch();
        test.stopTest();
    }
    

}