objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>ElectronicSignatureDateTime__c</fullName>
        <label>Electronic Signature Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/wktDocument8850__c.object
<CustomObject>
    <description>Work table for generation of 8850&apos;s</description>
    <fields>
        <fullName>ElectronicSignatureDateTime__c</fullName>
        <description>The date and time the employee electronically signed the 8850</description>
        <inlineHelpText>The date and time the employee electronically signed the 8850</inlineHelpText>
        <label>Electronic Signature Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EmployeeSurvey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipName>wktDocument8850</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IRS Form 8850</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>IRS Form 8850 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IRS Forms 8850</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Update8850EsignatureDateTimePlugin.cls
global class Update8850EsignatureDateTimePlugin implements Process.Plugin{

    global Process.PluginResult invoke(Process.PluginRequest request){
    
        String employeeSurveyId = (String)request.inputParameters.get('EmployeeSurveyId');
        String stringDateTime = (String)request.inputParameters.get('StringDateTime');
        
        DateTime currentDateTime = DateTime.parse(stringDateTime);
        
        wktDocument8850__c es = [select Id, ElectronicSignatureDateTime__c from wktDocument8850__c where EmployeeSurvey__c=:employeeSurveyId];
        es.ElectronicSignatureDateTime__c = currentDateTime;
        update es;        
        
        
        Map<String, Object> result = new Map<String, Object>();
        result.put('Result', 'Success');
        
        return new Process.PluginResult(result);    
    }
    
    global Process.PluginDescribeResult describe(){
        
        Process.PluginDescribeResult  result = new Process.PluginDescribeResult();
        
        result.inputParameters = new List<Process.PluginDescribeResult.InputParameter>{
            new Process.PluginDescribeResult.InputParameter('StringDateTime', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('EmployeeSurveyId', Process.PluginDescribeResult.ParameterType.STRING, true)
        };
        result.outputParameters = new List<Process.PluginDescribeResult.OutputParameter>{
            new Process.PluginDescribeResult.OutputParameter('Result', Process.PluginDescribeResult.ParameterType.STRING)
        };
        
        return result;
            
    }
}