objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>DeclinedSurveyBit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Did the employee decline to take the survey?</description>
        <inlineHelpText>Did the employee decline to take the survey?</inlineHelpText>
        <label>Declined Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SurveyResultGenerated__c</fullName>
        <defaultValue>&apos;Did Not Qualify&apos;</defaultValue>
        <description>A summary of the result of this survey: qualified, did not qualify, or declined.</description>
        <inlineHelpText>A summary of the result of this survey: qualified, did not qualify, or declined.</inlineHelpText>
        <label>Survey Result</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey qualified for this program</description>
        <inlineHelpText>The survey qualified for this program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BATCH_UpdateEmployeeSurvey_NoPQFill.cls
global class BATCH_UpdateEmployeeSurvey_NoPQFill implements Database.Batchable<sObject>{
public String query{get; set;}
    
    global void setDefaultQuery(){
        this.query = 'Select SurveyResultGenerated__c, DeclinedSurveyBit__c, (Select Id From ProgramQualifications__r) From EmployeeSurvey__c ';
        if(test.isRunningTest()) this.query = 'Select SurveyResultGenerated__c, DeclinedSurveyBit__c, (Select Id From ProgramQualifications__r) From EmployeeSurvey__c limit 100';
    }
    
    global database.querylocator start(Database.BatchableContext BC){
            return Database.getQueryLocator(query);
    }
    
  global void execute(Database.BatchableContext BC, List<sObject> scope){
        list<EmployeeSurvey__c> esList = new list <EmployeeSurvey__c>();
        for(EmployeeSurvey__c es : (list<EmployeeSurvey__c>)scope){
        	if(es.ProgramQualifications__r == null || es.ProgramQualifications__r.size() == 0){
						es.SurveyResultGenerated__c = 'Did Not Qualify';
						esList.add(es);
        	}
        }
    	update esList;
    }
    

    global void finish(Database.BatchableContext BC){
         
    }
	global static void runBatch(){
		BATCH_UpdateEmployeeSurvey_NoPQFill b = new BATCH_UpdateEmployeeSurvey_NoPQFill();
		b.setDefaultQuery();
		Database.executeBatch(b);
	}
	
    static testMethod void BATCH_UpdateEmployeeSurvey_NoPQFillTEST() {
    		test.startTest();
        BATCH_UpdateEmployeeSurvey_NoPQFill.runBatch();
        test.stopTest();
    }	
}

/*
list<EmployeeSurvey__c> l = [Select e.SurveyResultGenerated__c, e.DeclinedSurveyBit__c, (Select Id From ProgramQualifications__r) From EmployeeSurvey__c e limit 999];
for(EmployeeSurvey__c es:l){
	if(es.ProgramQualifications__r.size() == 0) system.assert(false, 'ITS ZERO!!!');
}
*/