objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>ElectronicSignatureDateTime__c</fullName>
        <label>Electronic Signature Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ElectronicSignatureText__c</fullName>
        <label>Electronic Signature Text</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ElectronicSignatureValidatedBit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Electronic Signature Validated Bit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EmployeeSSNFormula__c</fullName>
        <formula>EmploymentPeriod__r.Employee__r.SSN__c</formula>
        <label>Employee SSN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmploymentPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period tied to this survey</description>
        <inlineHelpText>The employment period tied to this survey</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EntityLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the survey was taken</description>
        <inlineHelpText>The location where the survey was taken</inlineHelpText>
        <label>Entity Location</label>
        <referenceTo>EntityLocation__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Five9SessionID__c</fullName>
        <externalId>true</externalId>
        <label>Five9 Session ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EntityLocation__c.object
<CustomObject>
    <label>Entity Location</label>
    <nameField>
        <label>Entity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/wktDocument8850__c.object
<CustomObject>
    <description>Work table for generation of 8850&apos;s</description>
    <fields>
        <fullName>CongaWorkflowTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate IRS 8850</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ElectronicSignatureDateTime__c</fullName>
        <description>The date and time the employee electronically signed the 8850</description>
        <inlineHelpText>The date and time the employee electronically signed the 8850</inlineHelpText>
        <label>Electronic Signature Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ElectronicSignatureText__c</fullName>
        <description>The electronic signature text</description>
        <inlineHelpText>The electronic signature text</inlineHelpText>
        <label>Electronic Signature Text</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ElectronicSignatureValidatedBit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if the electronic signature was validated by the employee over the phone</description>
        <inlineHelpText>Determines if the electronic signature was validated by the employee over the phone</inlineHelpText>
        <label>Electronic Signature Validated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EmployeeSurvey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipName>wktDocument8850</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IRS Form 8850</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>IRS Form 8850 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IRS Forms 8850</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/esignatureevalidate_controller.cls
public with sharing class esignatureevalidate_controller {
    public boolean validate {get; set;}
    private string ssn;
    private string sessionId;
    private list<EmployeeSurvey__c> esList; 
    /************/
    public esignatureevalidate_controller(){
        validate = false;
        sessionId = Apexpages.currentPage().getParameters().get('sessionId');
        ssn = Apexpages.currentPage().getParameters().get('ssn');
        if(ssn != null && sessionId != null){
        	
        	// No longer validating in real-time. Just grab the correct record based on session        	
            esList = [Select Id
                     From EmployeeSurvey__c e
                     where Five9SessionID__c=:sessionId];
			
			if(esList != null && esList.size()>0)
			{
				 validate = true;
			}                                                                             
            
        }
    }
    
    /************/
    public void updateIfValid()
    {
        if(validate ==true && esList !=null && esList.size()>0)
        {
            List<string> documentIdList = new List<string>();
            
            List<wktDocument8850__c> documents = [select id, 
            											ElectronicSignatureText__c, 
            											ElectronicSignatureDateTime__c, 
            											ElectronicSignatureValidatedBit__c,
            											CongaWorkflowTrigger__c
            										from wktDocument8850__c 
            										where EmployeeSurvey__c in:esList];
            										
			if(documents != null && documents.size() > 0)
			{            										
				for(wktDocument8850__c doc: documents){
                	doc.ElectronicSignatureText__c = ssn;
                	doc.ElectronicSignatureDateTime__c = datetime.now();
                	doc.ElectronicSignatureValidatedBit__c = true;
                	doc.CongaWorkflowTrigger__c = true;
                
                	documentIdList.add(doc.Id);
            	}
            	update documents;
			}
        }
    }
    
    
    /************/
    private static testmethod void test_esVal(){
        Test_EmployeeSurveyInsert_Trigger t = new Test_EmployeeSurveyInsert_Trigger();
        t.insertData();
        EmployeeSurvey__c es = new EmployeeSurvey__c();
        es.Name = 'test';
        es.EmploymentPeriod__c = t.em.id;
        es.EntityLocation__c = t.el.id;
        es.Five9SessionID__c = '111222333';
        insert es;
        
        es = [select Id, EmployeeSSNFormula__c, Five9SessionID__c  from EmployeeSurvey__c where Five9SessionID__c = '111222333'];
        
        wktDocument8850__c ee = new wktDocument8850__c();
        ee.EmployeeSurvey__c = es.id;
        insert ee;
        
        test.startTest();
        	apexpages.currentPage().getParameters().put('ssn', es.EmployeeSSNFormula__c);
        	apexpages.currentPage().getParameters().put('sessionId', es.Five9SessionID__c);
        	esignatureevalidate_controller sc = new esignatureevalidate_controller();
        	sc.updateIfValid();
        	system.assert(sc.validate);
        test.stopTest();
    }
}