objects/Employment__c.object
<CustomObject>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/wktDocument8850__c.object
<CustomObject>
    <description>Work table for generation of 8850&apos;s</description>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>wktDocument8850</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IRS Form 8850</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>IRS Form 8850 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IRS Forms 8850</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/wktDocumentEDDRelease__c.object
<CustomObject>
    <description>Work table to be used to auto-populate the EDD Release document from the survey, portal, or inside Salesforce.</description>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period that this form relates to.</description>
        <inlineHelpText>The employment period that this form relates to.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>wktDocumentEDDRelease</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EDD Release</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>EDD Release Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EDD Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PORTAL_EmploymentDownload.cls
public with sharing class PORTAL_EmploymentDownload {

	private string employmentId;
	private wktDocument8850__c w8850;
	private wktDocumentEDDRelease__c wEdd;
	public Attachment a8850 {get; set;}
	public Attachment aEdd	{get; set;}
	public boolean r8850		{get; set;}
	public boolean rEdd			{get; set;}
	private list<string> pIdList;
	/*************************************************************************************/
	public PORTAL_EmploymentDownload(){
		pIdList = new list<String>();		
		this.employmentId = Apexpages.currentPage().getParameters().get('eId');
		r8850 = false;
		rEdd = false;
		if(employmentId != null){
			setupWKTS();
			setupAttachments();	
		}
	}
	/*************************************************************************************/
	private void setupWKTS(){
		list <wktDocument8850__c> w8850List = [Select w.Employment__c  
																						From wktDocument8850__c w 
																						where Employment__c = :employmentId];
		if(w8850List != null && w8850List.size()>0){
				 r8850 = true;
				 w8850 = w8850List[0];
				 pIdList.add(w8850.id);
		}
																										
		list <wktDocumentEDDRelease__c> wEddList=[Select w.Employment__c 
																								From wktDocumentEDDRelease__c w 
																								where Employment__c = :employmentId];	
		if(wEddList != null && wEddList.size() >0){
				 rEdd = true;
				 wEdd = wEddList[0];
				 pIdList.add(wEdd.id);
		}	
	}
	/*************************************************************************************/
	private void setupAttachments(){
		list<Attachment> aList = [Select a.ParentId, a.Name, a.Description,
														 a.CreatedDate, a.ContentType, a.BodyLength, 
														 a.Body From Attachment a
														 where ParentId in :pIdList
														 order by CreatedDate];	
		if(aList != null && aList.size()>0){														 
			if(w8850!= null) a8850 = findAttachment(w8850.id, aList);
			if(wEdd != null) aEdd = findAttachment(wEdd.id, aList);
		}														 
	}
	/*************************************************************************************/
	private Attachment findAttachment(string wId, list<Attachment> aList){
		for(Attachment a : aList){
			if(a.ParentId == wId){
				return a;
			}
		}
		return null;
	}
	/*************************************************************************************/
}