objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>ClientEmployeeID__c</fullName>
        <description>The employee ID used by the client in their system.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee ID used by the client in their system.</inlineHelpText>
        <label>Client Employee ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>The employee&apos;s federal social security number.</description>
        <externalId>true</externalId>
        <inlineHelpText>The employee&apos;s federal social security number.</inlineHelpText>
        <label>SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>EmploymentPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period tied to this survey</description>
        <inlineHelpText>The employment period tied to this survey</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EntityLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the survey was taken</description>
        <inlineHelpText>The location where the survey was taken</inlineHelpText>
        <label>Entity Location</label>
        <referenceTo>EntityLocation__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</description>
        <inlineHelpText>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</inlineHelpText>
        <label>Location of Hire</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EntityLocation__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location that hires under this entity.</description>
        <inlineHelpText>Location that hires under this entity.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity Location</label>
    <nameField>
        <label>Entity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Hour__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>Indicates the location where the hours were worked</description>
        <inlineHelpText>Indicates the location where the hours were worked</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Hours</relationshipLabel>
        <relationshipName>Hours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wage__c</fullName>
        <description>The wage record associated with this hour record</description>
        <inlineHelpText>The wage record associated with this hour record</inlineHelpText>
        <label>Wage</label>
        <referenceTo>Wage__c</referenceTo>
        <relationshipLabel>Hours</relationshipLabel>
        <relationshipName>Hours</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Hour</label>
    <nameField>
        <label>Hour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wage__c.object
<CustomObject>
    <fields>
        <fullName>EmploymentPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period associated with this wage</description>
        <inlineHelpText>The employment period associated with this wage</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Wages</relationshipLabel>
        <relationshipName>Wages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wage</label>
    <nameField>
        <label>Wage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalLocationEmployeesController.cls
public with sharing class PortalLocationEmployeesController {

    public Location__c loc {get; set;}
    public list <EmployeeWrapper> ewList    {get; set;}
    public integer ewListSize   {get; set;}
    private string locationID;
		private set <String> employeeIdSet;
		public set<String> getemployeeIdSet(){
			if(test.isRunningTest())
				return employeeIdSet;
			else
				return null;
		}    
    
    /*************/
    public class EmployeeWrapper{
        public String lastName{get; set;}
        public String firstName{get; set;}
        public String clientEmployeeId{get; set;}
        public String ssn {get; set;}
        public String id{get; set;}
        public string background{get; set;}
        
        public EmployeeWrapper(Employee__c e, string bg){
            if(e.SSN__c !=null && e.SSN__c.length()>=4)
                ssn = e.SSN__c.substring(e.SSN__c.length()-4, e.SSN__c.length());
            else
                ssn = 'none';
            lastName = e.LastName__c;
            firstName = e.FirstName__c;
            clientEmployeeId = e.clientEmployeeId__c;
            id = e.Id;
            background = bg;
        }
    }
    /*************/


    /****************************************************************/
    public PortalLocationEmployeesController(){
        locationID = Apexpages.currentPage().getParameters().get('locId');
        if(locationId == null)
        	return;
        list <Location__c> llist = [select Name, id from Location__c where id = :locationID];
        if(llist!=null && llist.size()>0)
            loc = llist[0];
        
        list <Hour__c> hrs = [Select Wage__c, Location__c From Hour__c where Location__c = :locationID];
				set<String> wIds = new set<String>();
				for(Hour__c h : hrs){
					wIds.add(h.Wage__c);
				}
				list<Wage__c> wages = [Select EmploymentPeriod__r.Employee__c, EmploymentPeriod__c
															 From Wage__c
															 where id in :wIds];
	
        employeeIdSet = new set<String>();
        for(Wage__c w: wages){
            employeeIdSet.add(w.EmploymentPeriod__r.Employee__c);
        }
        
        list<EmployeeSurvey__c> esList = [Select EntityLocation__r.Location__c, EntityLocation__c, 
                                          EmploymentPeriod__r.Employee__c, EmploymentPeriod__c 
                                          From EmployeeSurvey__c 
                                          Where EntityLocation__r.Location__c = :locationID];
        
        for(EmployeeSurvey__c es : esList){
            employeeIdSet.add(es.EmploymentPeriod__r.Employee__c);
        }
        
        
        list<Employee__c> employees = [Select Name, LastName__c, FirstName__c, ClientEmployeeID__c, SSN__c, Id //last 4 digits of SSN 
                     From Employee__c
                     where id in :employeeIdSet
                     order by LastName__c limit 50];
                                 
        ewList = new list<EmployeeWrapper>();
        string color ='white';
        for(Employee__c e : employees){
            ewList.add(new EmployeeWrapper(e, color));
            if(color =='white')
            	color = 'white';//'lightgrey';
            else
            	color = 'white';
        }   
        ewListSize = employeeIdSet.Size();                      
    }
    /****************************************************************/
    public void nextPage(){
    	if(ewList == null || ewList.size()==0)
    		return;
    	list<Employee__c> employees = [Select Name, LastName__c, FirstName__c, ClientEmployeeID__c, SSN__c, Id //last 4 digits of SSN 
                     From Employee__c
                     where id in :employeeIdSet
                     and LastName__c > :ewList[ewList.size()-1].lastName
                     order by LastName__c limit 50];	
    	if(employees == null || employees.size() == 0)
    		return;
    	string color ='white';
	    for(Employee__c e : employees){
	        ewList.add(new EmployeeWrapper(e, color));
	        if(color =='white')
	        	color = 'white';//'lightgrey';
	        else
	        	color = 'white';
	    }	
    }
    /****************************************************************/
    public void previousPage(){
    	if(ewList == null || ewList.size()==0)
    		return;
    	list<Employee__c> employees = [Select Name, LastName__c, FirstName__c, ClientEmployeeID__c, SSN__c, Id //last 4 digits of SSN 
                     From Employee__c
                     where id in :employeeIdSet
                     and LastName__c < :ewList[0].lastName
                     order by LastName__c limit 50];	
    	if(employees == null || employees.size() == 0)
    		return;
    	string color ='white';
	    for(Employee__c e : employees){
	        ewList.add(new EmployeeWrapper(e, color));
	        if(color =='white')
	        	color = 'white';//'lightgrey';
	        else
	        	color = 'white';
	    }
    }
}