objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>EmploymentPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period tied to this survey</description>
        <inlineHelpText>The employment period tied to this survey</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SurveyProgramScreened__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program screened by the survey</description>
        <inlineHelpText>The program screened by the survey</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SurveyProgramScreenedEID__c</fullName>
        <description>The Enterprise ID for this Survey Program Screened record.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this Survey Program Screened record.</inlineHelpText>
        <label>Survey Program Screened EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The survey that screened for the program</description>
        <inlineHelpText>The survey that screened for the program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Programs Screened</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Program Screened</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Programs Screened Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Programs Screened</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Batch_UpdateSPS.cls
global class Batch_UpdateSPS implements Database.Batchable<sObject>{
  public string q{get; set;}
  /***********************************************/
	global void setDefaultQuery(){
		q = 'Select s.SurveyProgramScreenedEID__c, s.Survey__c, s.Program__c, s.Survey__r.EmploymentPeriod__r.Employee__c From SurveyProgramScreened__c s where Survey__r.EmploymentPeriod__r.Employee__c != null';
		if(test.isRunningTest()) q = 'Select s.SurveyProgramScreenedEID__c, s.Survey__c, s.Program__c From SurveyProgramScreened__c s limit 100'; 
	}
  /***********************************************/
  global database.querylocator start(Database.BatchableContext BC){
       return Database.getQueryLocator(q);
  }
  /***********************************************/
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		list<SurveyProgramScreened__c> spsList = new list<SurveyProgramScreened__c>();
		double val;
		for(SurveyProgramScreened__c sps : (list<SurveyProgramScreened__c>)scope){
			val = sps.SurveyProgramScreenedEID__c;
			sps.SurveyProgramScreenedEID__c = val;
			spsList.add(sps);
		}
		update spsList;
	}
	/***********************************************/
	global void finish(Database.BatchableContext BC){
		
	}
	/***********************************************/
	global static void runBatch(){
		Batch_UpdateSPS b = new Batch_UpdateSPS();
		b.setDefaultQuery();
		Database.executeBatch(b, 100);
	}
	/***********************************************/
	static testMethod void Test_Batch_UpdateSPS() {
    		test.startTest();
        Batch_UpdateSPS.runBatch();
        test.stopTest();
    }	

}