objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>EntityLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the survey was taken</description>
        <inlineHelpText>The location where the survey was taken</inlineHelpText>
        <label>Entity Location</label>
        <referenceTo>EntityLocation__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReportedHireDate__c</fullName>
        <description>The hire date reported by the employee</description>
        <inlineHelpText>The hire date reported by the employee</inlineHelpText>
        <label>Reported Hire Date</label>
        <type>Date</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EntityLocation__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location that hires under this entity.</description>
        <inlineHelpText>Location that hires under this entity.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity Location</label>
    <nameField>
        <label>Entity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date that this location shut its doors and went out of business.</description>
        <inlineHelpText>The date that this location shut its doors and went out of business.</inlineHelpText>
        <label>Location Closing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The opening date of this location, when it first started hiring employees.</description>
        <inlineHelpText>The opening date of this location, when it first started hiring employees.</inlineHelpText>
        <label>Location Opening Date</label>
        <type>Date</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LocationProgram__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The end of the period that we administer the program for this location.</description>
        <inlineHelpText>The end of the period that we administer the program for this location.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The location associated with the program and launch date</description>
        <inlineHelpText>The location associated with the program and launch date</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>LocationProgramLaunches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program associated with the location and launch date</description>
        <inlineHelpText>The program associated with the location and launch date</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>LocationProgramLaunches</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The location program launch date</description>
        <inlineHelpText>The location program launch date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Location Program</label>
    <nameField>
        <label>Location Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>ProgramEID__c</fullName>
        <description>The Enterprise ID for this Program.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this Program.</inlineHelpText>
        <label>Program EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SurveyProgramScreened__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program screened by the survey</description>
        <inlineHelpText>The program screened by the survey</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The survey that screened for the program</description>
        <inlineHelpText>The survey that screened for the program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Programs Screened</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Program Screened</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Programs Screened Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Programs Screened</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GetLocationPrograms.cls
global class GetLocationPrograms implements Process.Plugin{

    global Process.PluginResult invoke(Process.PluginRequest request){
        
        String entityLocationId = (String)request.inputParameters.get('EntityLocationId');          
        String employeeSurveyId = (String)request.inputParameters.get('EmployeeSurveyId');           
                
        Map<String, Object> result = new Map<String, Object>();
        
        EmployeeSurvey__c es = [select Id, ReportedHireDate__c from EmployeeSurvey__c where Id =:employeeSurveyId];
        Date hireDate = es.ReportedHireDate__c ;
        
        List<Program__c> progList = [SELECT Id, ProgramEID__c, (select Program__c from LocationProgramLaunches__r where Location__c in(select Location__c from EntityLocation__c where Id =:entityLocationId) and (StartDate__c <=:hireDate or StartDate__c >=:hireDate or StartDate__c = null) and (EndDate__c >=:hireDate or EndDate__c <=:hireDate or EndDate__c = null)) FROM Program__c];
                
        for(Program__c prog : progList)
        {
            String varName = 'ProgramId' + prog.ProgramEID__c;
            
            
            if(prog.LocationProgramLaunches__r.size() > 0)
            {
                List<SurveyProgramScreened__c> existingScreened = [select Id from SurveyProgramScreened__c where Survey__c =:employeeSurveyId and Program__c =:prog.Id];
                
                if(existingScreened.size() == 0)
                {
                    SurveyProgramScreened__c programScreened = new SurveyProgramScreened__c(Survey__c = employeeSurveyId, Program__c = prog.Id);
                    insert programScreened;
                }
                
                result.put(varName,'Yes');                       
                    
            }
            else
            {
                result.put(varName,'No');
            }
        }
        
        return new Process.PluginResult(result);    
    }
    
    global Process.PluginDescribeResult describe(){
        
        Process.PluginDescribeResult  result = new Process.PluginDescribeResult();
        
        result.inputParameters = new List<Process.PluginDescribeResult.InputParameter>{
            new Process.PluginDescribeResult.InputParameter('EntityLocationId', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('EmployeeSurveyId', Process.PluginDescribeResult.ParameterType.STRING, true)
        };
        
        result.outputParameters = new List<Process.PluginDescribeResult.OutputParameter>{
            new Process.PluginDescribeResult.OutputParameter('ProgramId1', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('ProgramId2', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('ProgramId3', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('ProgramId4', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('ProgramId5', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('ProgramId6', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('ProgramId7', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('ProgramId8', Process.PluginDescribeResult.ParameterType.STRING),                                    
            new Process.PluginDescribeResult.OutputParameter('ProgramId9', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('ProgramId10', Process.PluginDescribeResult.ParameterType.STRING),            
            new Process.PluginDescribeResult.OutputParameter('ProgramId11', Process.PluginDescribeResult.ParameterType.STRING),   
            new Process.PluginDescribeResult.OutputParameter('ProgramId12', Process.PluginDescribeResult.ParameterType.STRING),  
            new Process.PluginDescribeResult.OutputParameter('ProgramId13', Process.PluginDescribeResult.ParameterType.STRING),    
            new Process.PluginDescribeResult.OutputParameter('ProgramId14', Process.PluginDescribeResult.ParameterType.STRING),    
            new Process.PluginDescribeResult.OutputParameter('ProgramId15', Process.PluginDescribeResult.ParameterType.STRING),    
            new Process.PluginDescribeResult.OutputParameter('ProgramId16', Process.PluginDescribeResult.ParameterType.STRING),    
            new Process.PluginDescribeResult.OutputParameter('ProgramId17', Process.PluginDescribeResult.ParameterType.STRING),    
            new Process.PluginDescribeResult.OutputParameter('ProgramId18', Process.PluginDescribeResult.ParameterType.STRING),    
            new Process.PluginDescribeResult.OutputParameter('ProgramId19', Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('ProgramId21', Process.PluginDescribeResult.ParameterType.STRING)    
        };
        
        return result;
            
    }
}