objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>LastUpdatedDate__c</fullName>
        <description>When the respondent last submitted the survey</description>
        <inlineHelpText>When the respondent last submitted the survey</inlineHelpText>
        <label>Last Updated Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SurveyDate__c</fullName>
        <description>When the respondent first submitted the survey</description>
        <inlineHelpText>When the respondent first submitted the survey</inlineHelpText>
        <label>Survey Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateSurveyDateTimePlugin.cls
global class UpdateSurveyDateTimePlugin implements Process.Plugin{

    global Process.PluginResult invoke(Process.PluginRequest request){
    
        String employeeSurveyId = (String)request.inputParameters.get('EmployeeSurveyId');
        String stringDateTime = (String)request.inputParameters.get('StringDateTime');
        
        DateTime currentDateTime = DateTime.parse(stringDateTime);
        
        EmployeeSurvey__c es = [select Id, SurveyDate__c, LastUpdatedDate__c from EmployeeSurvey__c where Id=:employeeSurveyId];
        es.SurveyDate__c = currentDateTime;
        es.LastUpdatedDate__c = currentDateTime;
        update es;
        
        
        
        Map<String, Object> result = new Map<String, Object>();
        result.put('Result', 'Success');
        
        return new Process.PluginResult(result);    
    }
    
    global Process.PluginDescribeResult describe(){
        
        Process.PluginDescribeResult  result = new Process.PluginDescribeResult();
        
        result.inputParameters = new List<Process.PluginDescribeResult.InputParameter>{
            new Process.PluginDescribeResult.InputParameter('StringDateTime', Process.PluginDescribeResult.ParameterType.STRING, true),
            new Process.PluginDescribeResult.InputParameter('EmployeeSurveyId', Process.PluginDescribeResult.ParameterType.STRING, true)
        };
        result.outputParameters = new List<Process.PluginDescribeResult.OutputParameter>{
            new Process.PluginDescribeResult.OutputParameter('Result', Process.PluginDescribeResult.ParameterType.STRING)
        };
        
        return result;
            
    }
}