objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>DeclinedSurveyBit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Did the employee decline to take the survey?</description>
        <inlineHelpText>Did the employee decline to take the survey?</inlineHelpText>
        <label>Declined Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EmploymentPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period tied to this survey</description>
        <inlineHelpText>The employment period tied to this survey</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyResultGenerated__c</fullName>
        <defaultValue>&apos;Did Not Qualify&apos;</defaultValue>
        <description>A summary of the result of this survey: qualified, did not qualify, or declined.</description>
        <inlineHelpText>A summary of the result of this survey: qualified, did not qualify, or declined.</inlineHelpText>
        <label>Survey Result</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveySource__c</fullName>
        <description>The source of the survey</description>
        <inlineHelpText>The source of the survey</inlineHelpText>
        <label>Survey Source</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hot Seat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey qualified for this program</description>
        <inlineHelpText>The survey qualified for this program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BATCH_UpdateSurvey_SurveyResutsGenerated.cls
global class BATCH_UpdateSurvey_SurveyResutsGenerated implements Database.Batchable<sObject>{
public String query{get; set;}
    
    global void setDefaultQuery(){
        this.query = 'Select survey__c from ProgramQualification__c';
        if(test.isRunningTest()) this.query = 'Select survey__c from ProgramQualification__c limit 100';
    }
    
    global database.querylocator start(Database.BatchableContext BC){
            return Database.getQueryLocator(query);
    }
    
  global void execute(Database.BatchableContext BC, List<sObject> scope){
        list<string>sids = new list<String>();
        for(ProgramQualification__c pq : (list<ProgramQualification__c>)scope){
        	sids.add(pq.Survey__c);
        }
    		for(list<EmployeeSurvey__c>esList : [Select e.SurveyResultGenerated__c From EmployeeSurvey__c e where id in :sIds]){
    			for(EmployeeSurvey__c es: esList){
						es.SurveyResultGenerated__c = 'Qualified';
					}																		
					update esList;	
    		}
    }

    global void finish(Database.BatchableContext BC){
         
    }
	global static void runBatch(){
		BATCH_UpdateSurvey_SurveyResutsGenerated b = new BATCH_UpdateSurvey_SurveyResutsGenerated();
		b.setDefaultQuery();
		Database.executeBatch(b);
	}
	
    static testMethod void BATCH_UpdateSurvey_SurveyResutsGenerated() {
    		test.startTest();
        BATCH_UpdateSurvey_SurveyResutsGenerated.runBatch();
        test.stopTest();
    }	
}
/*
list<EmployeeSurvey__c> l = [Select e.SurveySource__c, e.SurveyResultGenerated__c, e.EmploymentPeriod__c, e.DeclinedSurveyBit__c, (Select Id From ProgramQualifications__r) From EmployeeSurvey__c e  where SurveyResultGenerated__c =''];
for(EmployeeSurvey__c es:l){
	system.debug('$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'+es.ProgramQualifications__r.size());
}
*/