objects/Employee__c.object
<CustomObject>
    <description>Everyone who has an employee relationship with any of our clients, whether they took the survey during the application process, or were hired.</description>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The employee&apos;s first (given) name.</description>
        <inlineHelpText>The employee&apos;s first (given) name.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name (surname) of the employee.</description>
        <inlineHelpText>The last name (surname) of the employee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</description>
        <inlineHelpText>The location where this employee was hired, regardless of the locations where the employee worked and was paid.</inlineHelpText>
        <label>Location of Hire</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Employment Periods</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>CityName__c</fullName>
        <description>The location&apos;s city.</description>
        <inlineHelpText>The location&apos;s city.</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location state</description>
        <inlineHelpText>The location state</inlineHelpText>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <description>The location street address</description>
        <inlineHelpText>The location street address</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The program short name</description>
        <inlineHelpText>The program short name</inlineHelpText>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/wktLocationEmployeeProgram__c.object
<CustomObject>
    <description>A generated list of locations with employees and programs.</description>
    <fields>
        <fullName>DocumentNeededText__c</fullName>
        <description>A list of documents that are still needed in order to document this program for at least one category.</description>
        <inlineHelpText>A list of documents that are still needed in order to document this program for at least one category.</inlineHelpText>
        <label>Documents Needed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentReceivedText__c</fullName>
        <description>Documents that have been received and are no longer sought.</description>
        <inlineHelpText>Documents that have been received and are no longer sought.</inlineHelpText>
        <label>Documents Received</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentReplacementNeededText__c</fullName>
        <description>Documents that were received but are incomplete, incorrect, illegible, or otherwise need replacing.</description>
        <inlineHelpText>Documents that were received but are incomplete, incorrect, illegible, or otherwise need replacing.</inlineHelpText>
        <label>Document Replacements Needed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployeeName__c</fullName>
        <label>EmployeeName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employee that all this information pertains to.</description>
        <inlineHelpText>The employee that all this information pertains to.</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period in question.</description>
        <inlineHelpText>The employment period in question.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HireDate__c</fullName>
        <description>The date this employee was hired at this location.</description>
        <inlineHelpText>The date this employee was hired at this location.</inlineHelpText>
        <label>Hire Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HireLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the employee was hired.</description>
        <inlineHelpText>The location where the employee was hired.</inlineHelpText>
        <label>Location of Hire</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs (Location of Hire)</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgramHire</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program begin screened for at this location.</description>
        <inlineHelpText>The program begin screened for at this location.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyDate__c</fullName>
        <description>The date and time that this employee was surveyed under this employment period, regardless of location of survey.</description>
        <inlineHelpText>The date and time that this employee was surveyed under this employment period, regardless of location of survey.</inlineHelpText>
        <label>Survey Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SurveyLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the employee was surveyed; may be different from the location of hire.</description>
        <inlineHelpText>The location where the employee was surveyed; may be different from the location of hire.</inlineHelpText>
        <label>Location of Survey</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs (Location of Survey)</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgramSurvey</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>wkt Location Employee Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Location Employee Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>wkt Location Employee Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Portal_Employee.cls
public with sharing class Portal_Employee {
	private string empId;
	public string employeeFirstName {get; set;}
	public string employeeLastName {get; set;}
	public string employeeLocationName {get; set;}
	public string employeeLocationID {get; set;}
	public list <ProgramListing> programList {get; set;} 
	/*********************************/
	public Portal_Employee(){
		empId = Apexpages.currentPage().getParameters().get('eId');
		list<wktLocationEmployeeProgram__c> wktList = [Select w.Program__r.ShortName__c, w.Program__r.Name, w.Program__c, 
																									w.HireLocation__r.StreetAddressText__c, w.HireLocation__r.State__c, 
																									w.HireLocation__r.CityName__c, w.HireLocation__r.Name, w.HireLocation__c, 
																									w.HireDate__c, w.Employee__c, w.EmployeeName__c, w.DocumentReplacementNeededText__c, 
																									w.DocumentReceivedText__c, w.DocumentNeededText__c, w.SurveyLocation__r.Name, 
																									w.SurveyLocation__c, w.SurveyDate__c, Employee__r.FirstName__c, Employee__r.LastName__c,
																									Employment__r.Location__r.Name, Employment__r.Location__r.Id
																									From wktLocationEmployeeProgram__c w
																									where Employee__c = :empId];
		programList = new list<ProgramListing>();
		if(wktList != null && wktList.size() > 0){
			employeeFirstName = wktList[0].Employee__r.FirstName__c;
			employeeLastName = wktList[0].Employee__r.LastName__c;
			employeeLocationName = wktList[0].Employment__r.Location__r.Name;
			employeeLocationID = wktList[0].Employment__r.Location__r.Id;
			for(wktLocationEmployeeProgram__c wkt : wktList){
				programList.add(new ProgramListing(wkt));
			}
		}
	}
	/******************************/
	/*****/
	public class ProgramListing{
		public String programName{get; set;}
		public list<string> receivedDocs {get;set;}
		public list<string> neededDocs {get; set;}
		public list<string> replaceDocs {get; set;}
		public string hireLoc		{get; set;}
		public string surveyLoc	{get; set;}
		public wktLocationEmployeeProgram__c wkt {get; set;}
		
		public ProgramListing(wktLocationEmployeeProgram__c wkt){
			this.wkt = wkt;
			this.programName = wkt.Program__r.Name + ' -- '+wkt.Program__r.shortName__c;
			
			if(wkt.SurveyLocation__c != null) surveyLoc = wkt.SurveyLocation__r.Name;
			else surveyLoc = 'NONE';
			if(wkt.Hirelocation__c != null) hireLoc = wkt.HireLocation__r.Name;
			else hireLoc = 'NONE';
			
			if(wkt.DocumentReceivedText__c != null) receivedDocs = wkt.DocumentReceivedText__c.split(';');
			if(wkt.DocumentNeededText__c != null) neededDocs = wkt.DocumentNeededText__c.split(';');
			if(wkt.DocumentReplacementNeededText__c != null) replaceDocs = wkt.DocumentReplacementNeededText__c.split(';');
		}	
	}
	/*****/ 
	/******************************/
}