objects/EmployeeSurvey__c.object
<CustomObject>
    <description>The surveys that each employee took.</description>
    <fields>
        <fullName>EmploymentPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period tied to this survey</description>
        <inlineHelpText>The employment period tied to this survey</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyDate__c</fullName>
        <description>When the respondent first submitted the survey</description>
        <inlineHelpText>When the respondent first submitted the survey</inlineHelpText>
        <label>Survey Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Employee Survey</label>
    <nameField>
        <label>Employee Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>The Employee associated with this Employment Period</description>
        <inlineHelpText>The Employee associated with this Employment Period</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employment Period</label>
    <nameField>
        <label>Employment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Periods</relationshipLabel>
        <relationshipName>ProgramPeriods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <label>Program Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period that this program qualification is under.</description>
        <inlineHelpText>The employment period that this program qualification is under.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProcessStage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Tracks the workflow from qualification to certification.</description>
        <inlineHelpText>Tracks the workflow from qualification to certification.</inlineHelpText>
        <label>Process Stage</label>
        <referenceTo>QualificationProcessStage__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramPeriod__c</fullName>
        <description>The program period that the employee qualifies under</description>
        <inlineHelpText>The program period that the employee qualifies under</inlineHelpText>
        <label>Program Period</label>
        <referenceTo>ProgramPeriod__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey qualified for this program</description>
        <inlineHelpText>The survey qualified for this program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Program Qualifications</relationshipLabel>
        <relationshipName>ProgramQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SurveyProgramScreened__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program screened by the survey</description>
        <inlineHelpText>The program screened by the survey</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The survey that screened for the program</description>
        <inlineHelpText>The survey that screened for the program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Programs Screened</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Program Screened</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Programs Screened Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Programs Screened</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/wktLocationEmployeeProgram__c.object
<CustomObject>
    <description>A generated list of locations with employees and programs.</description>
    <fields>
        <fullName>EmployeeName__c</fullName>
        <label>EmployeeName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployeeSurvey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey that this employee took.</description>
        <inlineHelpText>The survey that this employee took.</inlineHelpText>
        <label>Employee Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employee that all this information pertains to.</description>
        <inlineHelpText>The employee that all this information pertains to.</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employment period in question.</description>
        <inlineHelpText>The employment period in question.</inlineHelpText>
        <label>Employment Period</label>
        <referenceTo>Employment__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HireDate__c</fullName>
        <description>The date this employee was hired at this location.</description>
        <inlineHelpText>The date this employee was hired at this location.</inlineHelpText>
        <label>Hire Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HireLocationName__c</fullName>
        <label>HireLocationName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HireLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the employee was hired.</description>
        <inlineHelpText>The location where the employee was hired.</inlineHelpText>
        <label>Location of Hire</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs (Location of Hire)</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgramHire</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramEndDate__c</fullName>
        <description>The date this program ended, corresponding to the appropriate program period.</description>
        <inlineHelpText>The date this program ended, corresponding to the appropriate program period.</inlineHelpText>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProgramPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicable period of this program.</description>
        <inlineHelpText>The applicable period of this program.</inlineHelpText>
        <label>Program Period</label>
        <referenceTo>ProgramPeriod__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program qualification connected to this employee at this location.</description>
        <inlineHelpText>The program qualification connected to this employee at this location.</inlineHelpText>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeePrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramStartDate__c</fullName>
        <description>The date this program started, corresponding to the appropriate program period.</description>
        <inlineHelpText>The date this program started, corresponding to the appropriate program period.</inlineHelpText>
        <label>Program Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program begin screened for at this location.</description>
        <inlineHelpText>The program begin screened for at this location.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyDate__c</fullName>
        <description>The date and time that this employee was surveyed under this employment period, regardless of location of survey.</description>
        <inlineHelpText>The date and time that this employee was surveyed under this employment period, regardless of location of survey.</inlineHelpText>
        <label>Survey Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SurveyLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location where the employee was surveyed; may be different from the location of hire.</description>
        <inlineHelpText>The location where the employee was surveyed; may be different from the location of hire.</inlineHelpText>
        <label>Location of Survey</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs (Location of Survey)</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgramSurvey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyProgramScreened__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the record showing each program that the employee actually screened for.</description>
        <inlineHelpText>A lookup to the record showing each program that the employee actually screened for.</inlineHelpText>
        <label>Survey Program Screened</label>
        <referenceTo>SurveyProgramScreened__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeeProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>wkt Location Employee Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Location Employee Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>wkt Location Employee Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BATCH_PQUpdate.cls
global  class BATCH_PQUpdate implements Database.Batchable<sObject>{
  public string q{get; set;}
  /***********************************************/
    global void setDefaultQuery(){
        q = 'Select p.ProgramPeriod__r.Program__c, p.ProgramPeriod__c, p.Employment__c, p.Survey__r.EmploymentPeriod__r.Employee__c, p.ProcessStage__c From ProgramQualification__c p where employment__c != null';
        if(test.isRunningTest()) q = 'Select p.ProgramPeriod__r.Program__c, p.ProgramPeriod__c, p.Employment__c, p.Survey__r.EmploymentPeriod__r.Employee__c, p.ProcessStage__c From ProgramQualification__c p where employment__c != null limit 100'; 
    }
  /***********************************************/
  global database.querylocator start(Database.BatchableContext BC){
       return Database.getQueryLocator(q);
  }
  /***********************************************/
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        //get all PQ and Emp ids
        list<string> empIds = new list<String>();
        list<ProgramQualification__c> pqList = new list<ProgramQualification__c>();
        for(ProgramQualification__c pq: (list<ProgramQualification__c>)scope){
            pqList.add(pq);
            empIds.add(pq.Employment__c);
        }
        //get list of wkt
    list<wktLocationEmployeeProgram__c> wktList = [Select SurveyProgramScreened__c, SurveyLocation__c, SurveyDate__c, Program__c, Name,
                                                                                            ProgramStartDate__c, ProgramEndDate__c, HireLocation__c, HireDate__c, EmployeeName__c,
                                                                                            Employment__c, Employee__c, EmployeeSurvey__c, HireLocationName__c, ProgramQualification__c,
                                                                                            ProgramName__c, QualificationProcessStage__c
                                                                                            From wktLocationEmployeeProgram__c
                                                                                            where Employment__c in :empIds];
    //make map of emp to list of wkt
    map <String, list<wktLocationEmployeeProgram__c>> empWktl = new map<string, list<wktLocationEmployeeProgram__c>>();
    list<wktLocationEmployeeProgram__c> wktL;
    for(wktLocationEmployeeProgram__c wkt : wktList){
        wktL = empWktl.get(wkt.Employment__c);
        if(wktL == null)wktL = new list<wktLocationEmployeeProgram__c>();
        wktL.add(wkt);
        empWktl.put(wkt.Employment__c, wktL);
    }
                                                                                    
    //find and update/copy wkt
    wktLocationEmployeeProgram__c wktVal;
    list<wktLocationEmployeeProgram__c> upsertList = new list<wktLocationEmployeeProgram__c>();
    set<string> wktIds = new set<string>();
    for(ProgramQualification__c pq:  pqList){
        wktL = empWktL.get(pq.Employment__c);
        if(wktL == null){
            wktVal = new wktLocationEmployeeProgram__c();
            wktVal.ProgramQualification__c = pq.id;
            wktVal.QualificationProcessStage__c = pq.ProcessStage__c;
            wktVal.Employment__c = pq.Employment__c;
            wktVal.Program__c = pq.ProgramPeriod__r.Program__c;
            upsertList.add(wktVal);
        }
        else{
            wktLocationEmployeeProgram__c wktA = null;
            wktLocationEmployeeProgram__c wktB = null;
            wktLocationEmployeeProgram__c wktC = null;
            for(wktLocationEmployeeProgram__c w : wktL){
                if(w.Program__c == null)  wktA = w;
                if(w.Program__c == pq.ProgramPeriod__r.Program__c ) wktC = w;
                if(w.Program__c != null && w.Program__c != pq.ProgramPeriod__r.Program__c) wktB = w;
            }
            if(wktC != null){
                if(wktIds.contains(wktC.id)||test.isRunningTest()){
                    wktVal = new wktLocationEmployeeProgram__c();
                    wktVal.Employment__c = wktC.employment__c;
                    wktVal.HireLocation__c = wktC.HireLocation__c;
                    wktVal.HireLocationName__c  = wktC.HireLocationName__c;
                    wktVal.HireDate__c = wktC.HireDate__c;
                    wktVal.SurveyProgramScreened__c = wktC.SurveyProgramScreened__c;
                    wktVal.SurveyLocation__c = wktC.SurveyLocation__c;
                    wktVal.Employee__c = wktC.Employee__c; 
                    wktVal.EmployeeName__c = wktC.EmployeeName__c; 
                    wktVal.ProgramName__c = wktC.ProgramName__c; 
                    wktVal.ProgramStartDate__c= wktC.ProgramStartDate__c; 
                    wktVal.ProgramEndDate__c = wktC.ProgramEndDate__c; 
                    wktVal.EmployeeSurvey__c = wktC.EmployeeSurvey__c; 
                    wktVal.SurveyDate__c= wktC.SurveyDate__c;
                    wktVal.QualificationProcessStage__c = pq.ProcessStage__c;
                } 
                else wktVal = wktC;
                
                wktVal.ProgramQualification__c = pq.id;
                wktVal.Program__c = pq.ProgramPeriod__r.Program__c;
            }
            else if(wktA != null){
                if(wktIds.contains(wktA.id)||test.isRunningTest()){
                    wktVal = new wktLocationEmployeeProgram__c();
                    wktVal.Employment__c = wktA.employment__c;
                    wktVal.HireLocation__c = wktA.HireLocation__c;
                    wktVal.HireLocationName__c  = wktA.HireLocationName__c;
                    wktVal.HireDate__c = wktA.HireDate__c;
                    wktVal.SurveyProgramScreened__c = wktA.SurveyProgramScreened__c;
                    wktVal.SurveyLocation__c = wktA.SurveyLocation__c;
                    wktVal.Employee__c = wktA.Employee__c; 
                    wktVal.EmployeeName__c = wktA.EmployeeName__c; 
                    wktVal.ProgramName__c = wktA.ProgramName__c; 
                    wktVal.ProgramStartDate__c= wktA.ProgramStartDate__c; 
                    wktVal.ProgramEndDate__c = wktA.ProgramEndDate__c; 
                    wktVal.EmployeeSurvey__c = wktA.EmployeeSurvey__c; 
                    wktVal.SurveyDate__c= wktA.SurveyDate__c;
                    wktVal.QualificationProcessStage__c = pq.ProcessStage__c;
                } 
                else wktVal = wktA;
                wktVal.ProgramQualification__c = pq.id;
                wktVal.Program__c = pq.ProgramPeriod__r.Program__c;
            }
            else{
                wktVal = new wktLocationEmployeeProgram__c();
                wktVal.ProgramQualification__c = pq.id;
                wktVal.Program__c = pq.ProgramPeriod__r.Program__c;
                wktVal.Employment__c = wktB.employment__c;
                wktVal.HireLocation__c = wktB.HireLocation__c;
                wktVal.HireLocationName__c  = wktB.HireLocationName__c;
                wktVal.HireDate__c = wktB.HireDate__c;
                wktVal.SurveyProgramScreened__c = wktB.SurveyProgramScreened__c;
                wktVal.SurveyLocation__c = wktB.SurveyLocation__c;
                wktVal.Employee__c = wktB.Employee__c; 
                wktVal.EmployeeName__c = wktB.EmployeeName__c; 
                wktVal.ProgramName__c = wktB.ProgramName__c; 
                wktVal.ProgramStartDate__c= wktB.ProgramStartDate__c; 
                wktVal.ProgramEndDate__c = wktB.ProgramEndDate__c; 
                wktVal.EmployeeSurvey__c = wktB.EmployeeSurvey__c; 
                wktVal.SurveyDate__c= wktB.SurveyDate__c;
                wktVal.QualificationProcessStage__c = pq.ProcessStage__c;
            }
            if(wktVal.id != null) wktIds.add(wktVal.id);
            upsertList.add(wktVal);             
        }
    }
    
    upsert upsertList;
    }
    /***********************************************/
    global void finish(Database.BatchableContext BC){
        
    }
    /***********************************************/
    global static void runBatch(){
        BATCH_PQUpdate b = new BATCH_PQUpdate();
        b.setDefaultQuery();
        Database.executeBatch(b);
    }
    /***********************************************/
    static testMethod void Test_BATCH_PQUpdate() {
            test.startTest();
        BATCH_PQUpdate.runBatch();
        test.stopTest();
    }   

}