objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account, or client, that this entity belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>AccountEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EntityLocation__c.object
<CustomObject>
    <fields>
        <fullName>EntityLocationEID__c</fullName>
        <description>The Enterprise ID for this Entity Location.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Enterprise ID for this Entity Location.</inlineHelpText>
        <label>Entity Location EID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <description>Entity that has this location.</description>
        <inlineHelpText>Entity that has this location.</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location that hires under this entity.</description>
        <inlineHelpText>Location that hires under this entity.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Entity Location</label>
    <nameField>
        <label>Entity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetEntityLocationCount.cls
global class GetEntityLocationCount implements Process.Plugin{

    global Process.PluginResult invoke(Process.PluginRequest request){
    
        String locationRecord = (String)request.inputParameters.get('LocationRecord');
        Decimal entityLocationEID = 0;
        Integer entityLocationCount = 0;
        String entityLocationSFID = '';
        
       	entityLocationCount = [select count() from EntityLocation__c where Location__c =:locationRecord]; 
       	
       	if(entityLocationCount == 1)
       	{
       		EntityLocation__c entityLocation = [select Id, EntityLocationEID__c from EntityLocation__c where Location__c =:locationRecord limit 1];       		
       		
       		entityLocationEID = entityLocation.EntityLocationEID__c;
       		entityLocationSFID = entityLocation.Id;
       	}     
        
        Map<String, Object> result = new Map<String, Object>();
        result.put('EntityLocationCount', entityLocationCount);
        result.put('EntityLocationEID', entityLocationEID);
        result.put('EntityLocationSFID', entityLocationSFID);
        
        return new Process.PluginResult(result);    
    }
    
    global Process.PluginDescribeResult describe(){
        
        Process.PluginDescribeResult  result = new Process.PluginDescribeResult();
        
        result.inputParameters = new List<Process.PluginDescribeResult.InputParameter>{
            new Process.PluginDescribeResult.InputParameter('LocationRecord', Process.PluginDescribeResult.ParameterType.STRING, true)
        };
        result.outputParameters = new List<Process.PluginDescribeResult.OutputParameter>{
            new Process.PluginDescribeResult.OutputParameter('EntityLocationCount', Process.PluginDescribeResult.ParameterType.INTEGER),
            new Process.PluginDescribeResult.OutputParameter('EntityLocationEID', Process.PluginDescribeResult.ParameterType.DECIMAL),
            new Process.PluginDescribeResult.OutputParameter('EntityLocationSFID', Process.PluginDescribeResult.ParameterType.STRING)
        };
        
        return result;
            
    }
    
   public static testMethod void GetEntityLocationCount_TEST()
   {
   		Account a;
   		Location__c l;
   		Entity__c ent;
   		EntityLocation__c el;
   		 
  		a = new Account();
	   	a.Name = 'testa';
	   	insert a;
	    	
    	
		l = new Location__c();
	    l.Account__c = a.id;
	    l.Name = 'test';
	    	
	    ent = new Entity__c();
	    ent.Account__c = a.id;
	    ent.Name = 'test';
	    insert ent;
	    	
	    el = new EntityLocation__c();
	    el.Entity__c = ent.id;
	    el.Location__c = l.id;
        
        test.startTest();
        
	        GetEntityLocationCount plugin = new GetEntityLocationCount();
	        Map<String,Object> inputParams = new Map<String,Object>();
	
	        InputParams.put('LocationRecord', l.id);        
	
	        Process.PluginRequest request = new Process.PluginRequest(inputParams);           
	        
	        plugin.invoke(request);
	        
	        plugin.describe();
        
        test.stopTest();
    }
}