objects/Entity__c.object
<CustomObject>
    <description>An entity is a business entity that is formed or incorporated at the state and federal level.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account, or client, that this entity belongs to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>AccountEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ClientEntityId__c</fullName>
        <description>The client provided id for the entity</description>
        <inlineHelpText>The client provided id for the entity</inlineHelpText>
        <label>Client Entity ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EntityStructure__c.object
<CustomObject>
    <fields>
        <fullName>CityName__c</fullName>
        <inlineHelpText>Official address for this entity, for tax filing purposes. The city.</inlineHelpText>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EntityName__c</fullName>
        <inlineHelpText>The entity whose structure is being defined.</inlineHelpText>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Structure History</relationshipLabel>
        <relationshipName>EntityStructures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EntityType__c</fullName>
        <inlineHelpText>The structure of this business entity. Choose from the pull-down menu.</inlineHelpText>
        <label>Business Entity Type</label>
        <picklist>
            <picklistValues>
                <fullName>C Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Liability Company (LLC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Liability Limited Partnership (LLLP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Liability Partnership (LLP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Partnership (LP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Corporation (PC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Limited Liability Company (PLLC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sole Proprietorship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FederalTaxId__c</fullName>
        <inlineHelpText>The federally issued tax or employer identification number for the entity.</inlineHelpText>
        <label>Federal Tax ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <inlineHelpText>Official address for this entity, for tax filing purposes. The street address; include second line if applicable.</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <inlineHelpText>Official address for this entity, for tax filing purposes. The zip or postal code.</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Entity Structure</label>
    <nameField>
        <label>Entity Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Structures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PreventDuplicateFederalTaxId_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PreventDuplicateFederalTaxId_TEST {

    private static Account AccLocation;
    private static EntityStructure__c ents;
    private static Entity__c ef;
    
    static{
         AccLocation= new Account(name='test1',phone='2016742345',website='taxcreditco.com',BillingState='CA',BillingPostalCode='67890',BillingStreet='123 Anywhere',BillingCity='Somewhere',BillingCountry='United States');
        insert AccLocation;
        ef= new Entity__c (name='test2',ClientEntityId__c='1234567', Account__c=AccLocation.Id );
        insert ef;
        /*ents = new EntityStructure__c(EntityType__c='EntityType__c',CityName__c='Los Angeles',FederalTaxId__c='1234567890',
        StreetAddressText__c='400 North Hollywood',ZipCode__c='12345',EntityName__c=ef.id);
        insert ents;*/
    }
    static testMethod void PreventFederalTaxIdDuplicate(){
        EntityStructure__c entstructure = new EntityStructure__c();
        entstructure.EntityName__c=ef.id;
        entstructure.EntityType__c='C Corporation';
        entstructure.CityName__c='Los Angeles';
        entstructure.StreetAddressText__c='400 North Hollywood';
        entstructure.ZipCode__c='12345';
        entstructure.FederalTaxId__c='000000000';
        insert entstructure; 
        update entstructure;
        
    }
}