objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this location belongs.</description>
        <inlineHelpText>The account to which this location belongs.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CityName__c</fullName>
        <description>The location&apos;s city.</description>
        <inlineHelpText>The location&apos;s city.</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetAddressText__c</fullName>
        <description>The location street address</description>
        <inlineHelpText>The location street address</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>The location zip</description>
        <inlineHelpText>The location zip</inlineHelpText>
        <label>Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PreventDuplicateLocationAddress_TEST.cls
@isTest
Private class PreventDuplicateLocationAddress_TEST {

  private static Account AccLocation;
  private static Location__c Loc;
  
   Static{
       AccLocation= new Account(Name = 'Test Account',Type='Partner',Website='www.taxcreditco.com',BillingState ='VA',BillingPostalCode='23294',BillingStreet='Colchester Creek',BillingCity='Cumming',BillingCountry='United States');
       insert AccLocation;
     
       Loc = new Location__c(Name='Henrico Office',StreetAddressText__c='2490 Mariner Square Loop',CityName__c='Alameda',ZipCode__c='94501',Account__c=AccLocation.Id);
       insert Loc;
  } 
  static testmethod void PreventLocationDuplicate(){
       Location__c Locat = new Location__c();
       Locat.Account__c = AccLocation.Id;
       Locat.StreetAddressText__c = '2490 Mariner Square Loop'; 
       Locat.CityName__c ='Alameda';
       Locat.ZipCode__c='94501';
       //Locat.Account__c ='Test Account';
  
  insert Locat;
  update Locat;
  
 }

}