objects/PortalRole__c.object
<CustomObject>
    <label>Portal Role</label>
    <nameField>
        <label>Portal Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PortalUser__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Client_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PortalRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The role of the portal user</description>
        <inlineHelpText>The role of the portal user</inlineHelpText>
        <label>Portal Role</label>
        <referenceTo>PortalRole__c</referenceTo>
        <relationshipLabel>Portal Users</relationshipLabel>
        <relationshipName>PortalUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal User</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Portal User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalHomeController.cls
public with sharing class PortalHomeController 
{
    public string ContactId {get; set;}
    public string PortalRoleName {get; set;}
    public boolean ShowScreening {get; set;}
    public boolean IsLocationProcessManager {get; set;}

    
    public PortalHomeController()
    {
        if(ApexPages.currentPage().getParameters().get('id') != null)
        {
            ContactId = ApexPages.currentPage().getParameters().get('id');
            
            list<PortalRole__c> portalRoleObjects = [select Name from PortalRole__c where Id in (select PortalRole__c from PortalUser__c where Contact__c =:contactId) limit 1];
            if(portalRoleObjects != null && portalRoleObjects.size()>0)
            	PortalRoleName = portalRoleObjects[0].name;
            
            if(PortalRoleName!=null && PortalRoleName == 'Location Process Manager')
            {
                IsLocationProcessManager = true;
                ShowScreening = true;
            }
            else
            {
                IsLocationProcessManager = false;
                ShowScreening = false;
            }
            

        }
        else
        {
            return;
        }
    }    

	public static testmethod void testController(){
		
		Contact c = new Contact();
		c.firstName = 'test';
		c.LastName = 'test';
		insert c;
		
		PortalRole__c pr = new PortalRole__c();
		pr.Name = 'Location Process Manager';
		insert pr;
		
		PortalUser__c pu = new PortalUser__c();
		pu.Contact__c = c.id;
		pu.PortalRole__c = pr.id;
		insert pu;
		
		Apexpages.currentPage().getParameters().put('id', c.id);
		PortalHomeController phc = new PortalHomeController();
		System.assert(phc.ShowScreening == true);
		
		Contact c2 = new Contact();
		c2.FirstName = 'arf';
		c2.lastName = 'bark';
		insert c2;
		Apexpages.currentPage().getParameters().put('id', c2.id);
		phc = new PortalHomeController();
		System.assert(phc.ShowScreening == false);
	}

}