objects/ProgramCategory__c.object
<CustomObject>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The short name for this program category, for succinct reporting.</description>
        <inlineHelpText>The short name for this program category, for succinct reporting.</inlineHelpText>
        <label>Short Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Program Category</label>
    <nameField>
        <label>Program Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategoryPeriod__c.object
<CustomObject>
    <fields>
        <fullName>ProgramCategory__c</fullName>
        <description>The program category linked to this area</description>
        <inlineHelpText>The program category linked to this area</inlineHelpText>
        <label>Program Category</label>
        <referenceTo>ProgramCategory__c</referenceTo>
        <relationshipName>ProgramCategoryAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Category Period</label>
    <nameField>
        <label>Program Category Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Category Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramCategoryQualification__c.object
<CustomObject>
    <fields>
        <fullName>ProgramCategoryPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program category period associated with the program category qualification and program qualification</description>
        <inlineHelpText>The program category period associated with the program category qualification and program qualification</inlineHelpText>
        <label>Program Category Period</label>
        <referenceTo>ProgramCategoryPeriod__c</referenceTo>
        <relationshipLabel>Program Category Qualifications</relationshipLabel>
        <relationshipName>ProgramCategoryQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the qualified program for an employee</description>
        <inlineHelpText>Indicates the qualified program for an employee</inlineHelpText>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipLabel>Program Category Qualifications</relationshipLabel>
        <relationshipName>ProgramCategoryQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Readiness__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The state of readiness of a program category for vouchering or application.</description>
        <inlineHelpText>The state of readiness of a program category for vouchering or application.</inlineHelpText>
        <label>Readiness</label>
        <referenceTo>QualificationReadiness__c</referenceTo>
        <relationshipLabel>Program Category Qualifications</relationshipLabel>
        <relationshipName>ProgramCategoryQualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Category Qualification</label>
    <nameField>
        <label>Program Category Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Category Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProgramQualification__c.object
<CustomObject>
    <label>Program Qualification</label>
    <nameField>
        <label>Program Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QualificationReadiness__c.object
<CustomObject>
    <description>The state of readiness that a program category qualification is in.</description>
    <fields>
        <fullName>ExternalName__c</fullName>
        <description>The client-friendly term for this state of readiness.</description>
        <inlineHelpText>The client-friendly term for this state of readiness.</inlineHelpText>
        <label>External Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Document Readiness</label>
    <nameField>
        <label>Document Readiness Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Readinesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/wktLocationEmployeeProgram__c.object
<CustomObject>
    <description>A generated list of locations with employees and programs.</description>
    <fields>
        <fullName>ProgramQualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program qualification connected to this employee at this location.</description>
        <inlineHelpText>The program qualification connected to this employee at this location.</inlineHelpText>
        <label>Program Qualification</label>
        <referenceTo>ProgramQualification__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeePrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QualifiedCategoryText__c</fullName>
        <label>QualifiedCategoryText</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>wkt Location Employee Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Location Employee Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>wkt Location Employee Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PCQUpdateWktLEPCategories_helper.cls
public with sharing class PCQUpdateWktLEPCategories_helper {

	private list<String> pqIds;
	
	
	/***************************/
	public PCQUpdateWktLEPCategories_helper(list<string> l){
		pqIds =l;
	}
	/***************************/
	public list<wktLocationEmployeeProgram__c> makeUpdateList(){
		list<ProgramCategoryQualification__c> pcqList = getAllPCQs();
		map<string, set<String>> pqToCategoriesMap = makepqToCategoriesMap(pcqList);
		list<wktLocationEmployeeProgram__c> wktL = getWktLEPs();
		updateWktCategoryFields(wktL, pqToCategoriesMap);
		return wktL;
	}
	/***************************/
	private list<ProgramCategoryQualification__c> getAllPCQS(){
		list<ProgramCategoryQualification__c> pcqList = [Select p.ProgramQualification__c, 
																										p.ProgramCategoryPeriod__r.ProgramCategory__c, p.ProgramCategoryPeriod__c,
																										p.ProgramCategoryPeriod__r.ProgramCategory__r.Name, 
																										p.ProgramCategoryPeriod__r.ProgramCategory__r.ShortName__c,
																										p.Readiness__c, p.Readiness__r.ExternalName__c
																										From ProgramCategoryQualification__c p
																										where ProgramQualification__c in :pqIds
																										and Readiness__r.ExternalName__c != 'Disqualified'];
		return pcqList;
	}
	/***************************/
	private map<string, set<String>> makepqToCategoriesMap(list<ProgramCategoryQualification__c> pcqList){
		map<string, set<String>> rval = new map<string, set<String>>();
		set<String> cats;
		string c;
		for(ProgramCategoryQualification__c pcq : pcqList){
			cats = rval.get(pcq.ProgramQualification__c);
			if(cats==null) cats = new set<string>();
			if(pcq.ProgramCategoryPeriod__r.ProgramCategory__r.ShortName__c!=null) c= pcq.ProgramCategoryPeriod__r.ProgramCategory__r.ShortName__c;
			else c= pcq.ProgramCategoryPeriod__r.ProgramCategory__r.Name;
			
			if(c!=null) cats.add(c);
			rval.put(pcq.ProgramQualification__c, cats);
		}
		return rval;
	}
	/***************************/
	private list<wktLocationEmployeeProgram__c> getWktLEPs(){
		list<wktLocationEmployeeProgram__c> wktL = [Select  w.ProgramQualification__c,w.QualifiedCategoryText__c 
																								From wktLocationEmployeeProgram__c w
																								where ProgramQualification__c in :pqIds
																								and ProgramQualification__c != null];
		return wktL;
	}
	/***************************/
	private void updateWktCategoryFields(list<wktLocationEmployeeProgram__c>wktL, map<string, set<String>>pqToCategoriesMap){
		set<String>cats;
		for(wktLocationEmployeeProgram__c wkt: wktL){
			cats = pqToCategoriesMap.get(wkt.ProgramQualification__c);
			wkt.QualifiedCategoryText__c = makeCategoryText(cats);
		}
		
	}
	/***************************/
	private string makeCategoryText(set<string> cats){
		if(cats ==null || cats.size() ==0) return '';
		string val='';
		list<String> l = new list<String>();
		l.addAll(cats);
		l.sort();
		for(string s: l){
			val=val+s+',';
		}
		val = val.substring(0, val.length()-1);
		return val;
	}
}