objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SurveyProgramScreened__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>The program screened by the survey</description>
        <inlineHelpText>The program screened by the survey</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The survey that screened for the program</description>
        <inlineHelpText>The survey that screened for the program</inlineHelpText>
        <label>Survey</label>
        <referenceTo>EmployeeSurvey__c</referenceTo>
        <relationshipLabel>Programs Screened</relationshipLabel>
        <relationshipName>SurveyProgramsScreened</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Program Screened</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Programs Screened Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Programs Screened</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BATCH_UpdateSurveyProgramScreened.cls
global class BATCH_UpdateSurveyProgramScreened implements Database.Batchable<sObject>{
    
    public String query{get; set;}
    
    global void setDefaultQuery(){
        this.query = 'Select Program__c, Name, Survey__c,Id From SurveyProgramScreened__c where Program__c != null';
        if(test.isRunningTest()) this.query = 'Select Program__c, Name, Survey__c,Id From SurveyProgramScreened__c where Program__c != null limit 30';
    }
    
    global database.querylocator start(Database.BatchableContext BC){
            return Database.getQueryLocator(query);
    }
    
  global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<SurveyProgramScreened__c> obs = new List<SurveyProgramScreened__c>();
				String name;
        for(sObject s : scope){
          SurveyProgramScreened__c sps= (SurveyProgramScreened__c)s;
         	//name = sps.Survey__c;
         	//sps.Survey__c = name;   
          obs.add(sps);
        }

        update obs;
    }

    global void finish(Database.BatchableContext BC){
         
    }
    global static void runBatch(){
			BATCH_UpdateSurveyProgramScreened b = new BATCH_UpdateSurveyProgramScreened();
			b.setDefaultQuery();
			Database.executeBatch(b);
		}
		static testMethod void TEST_BATCH_UpdateSurveyProgramScreened() {
    		test.startTest();
        BATCH_UpdateSurveyProgramScreened.runBatch();
        test.stopTest();
    }
}