objects/QualificationProcessStage__c.object
<CustomObject>
    <description>The stages that a qualification can be in.</description>
    <label>Document Process Stage</label>
    <nameField>
        <label>Document Process Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Process Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/wktLocationEmployeeProgram__c.object
<CustomObject>
    <description>A generated list of locations with employees and programs.</description>
    <fields>
        <fullName>QPSFormula__c</fullName>
        <formula>ProgramQualification__r.ProcessStage__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QPSFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QualificationProcessStage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The current process stage of this employee for this program.</description>
        <inlineHelpText>The current process stage of this employee for this program.</inlineHelpText>
        <label>Qualification Process Stage</label>
        <referenceTo>QualificationProcessStage__c</referenceTo>
        <relationshipLabel>wkt Location Employee Programs</relationshipLabel>
        <relationshipName>wktLocationEmployeePrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>wkt Location Employee Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Location Employee Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>wkt Location Employee Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BATCH_UpdateWLEPQPS.cls
global class BATCH_UpdateWLEPQPS implements Database.Batchable<sObject>{
  //this runs the batch
    global static void runBatch(){
      BATCH_UpdateWLEPQPS  b = new BATCH_UpdateWLEPQPS ();
      b.setDefaultQuery();
      Database.executeBatch(b);
    }


    public String query{get; set;}
      
      global void setDefaultQuery(){
          this.query = 'Select Id, QualificationProcessStage__c, QPSFormula__c from wktLocationEmployeeProgram__c where QualificationProcessStage__c = null';
          if(test.isRunningTest())this.query = 'Select Id, QualificationProcessStage__c, QPSFormula__c from wktLocationEmployeeProgram__c where QualificationProcessStage__c = null limit 50';
      }
      
      
      global database.querylocator start(Database.BatchableContext BC){
              return Database.getQueryLocator(query);
      }
      
      global void execute(Database.BatchableContext BC, List<sObject> scope){
          List<wktLocationEmployeeProgram__c > obs = new List<wktLocationEmployeeProgram__c >();
          
          for(wktLocationEmployeeProgram__c  s :(list<wktLocationEmployeeProgram__c >)scope){
              s.QualificationProcessStage__c = s.QPSFormula__c;
              obs.add(s);
          }
 
          update obs;
    }
   
      global void finish(Database.BatchableContext BC){
           
      }

    
    static testMethod void TEST_BATCH_UpdateWLEPQPS () {
        test.startTest();
        BATCH_UpdateWLEPQPS.runBatch();
        BATCH_UpdateWLEPQPS b = new BATCH_UpdateWLEPQPS();
        b.setDefaultQuery();
        Database.executeBatch(b);
        test.stopTest();
    }
    

}